Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <inlineHelpText>Each individual contact is associated with a Household which lists information for the whole family.</inlineHelpText>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts (Address)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Proposal</relationshipLabel>
        <relationshipName>Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Pledges &amp; Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Pledge_Benefit__c.object
<CustomObject>
    <description>This includes the benefit details of the pledge</description>
    <fields>
        <fullName>Bulk_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bulk Load</label>
        <type>Checkbox</type>
    </fields>
    <label>Pledge Benefit</label>
    <nameField>
        <label>Pledge Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pledge Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations and Pledges</description>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipName>Recurring_Donations_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <label>Recurring Pledge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Salutation__c.object
<CustomObject>
    <description>TA Salutation</description>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salutations</relationshipLabel>
        <relationshipName>Salutations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Salutation</label>
    <nameField>
        <label>Salutation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salutations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TaPayment__c.object
<CustomObject>
    <description>Temporary Payment Object for closing Opportunities that were migrated from TA</description>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk load</label>
        <type>Checkbox</type>
    </fields>
    <label>TaPayment Temporary</label>
    <nameField>
        <label>Temp Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaPayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchBulkflagProcessor.cls
global class BatchBulkflagProcessor implements Database.Batchable<sObject> {
	global static final String HOUSEHOLD_CHAIN = 'Household';
	global static final String TRANSACTION_CHAIN = 'Transaction';
	global static final String INTERACTION_CHAIN = 'Interaction';
	
    global String[] objectNamesChainHousehold = new String[]{'Address__c', 'Classification__c', 'Contact', 'Household__c', 'Relationships__c', 'Salutation__c'}; 
    global String[] objectNamesChainTransaction = new String[]{'Opportunity', 'TaPayment__c', 'Recurring_Donation__c', 'Pledge_Benefit__c'};
    global String[] objectNamesChainInteraction = new String[]{'Case','Task'};
    
    global String chainName;
    global Integer objectNumber;
    global String query;
    global Boolean chainFlag = false;
    global Boolean chain = false;
    
    global BatchBulkflagProcessor(String chainName, Integer objectNumber) {
    	this.chain = true;
    	this.chainName = chainName;
        this.objectNumber = objectNumber;
        String objectName = null;
        if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.HOUSEHOLD_CHAIN)) {
        	objectName = objectNamesChainHousehold[objectNumber - 1];
        }
        else if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.TRANSACTION_CHAIN)) {
            objectName = objectNamesChainTransaction[objectNumber - 1];
        }
        else if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.INTERACTION_CHAIN)) {
            objectName = objectNamesChainInteraction[objectNumber - 1];
        }
        this.query = 'SELECT id, bulk_load__c FROM ' + objectName + ' WHERE bulk_load__c = true';
    }
    
    global BatchBulkflagProcessor(String chainName, Integer objectNumber, Boolean chainFlag) {
        this(chainName, objectNumber);
        this.chainFlag = chainFlag;
    }
    
    global BatchBulkflagProcessor(String objectName) {
    	this.chain = false;
        this.query = 'SELECT id, bulk_load__c FROM ' + objectName + ' WHERE bulk_load__c = true';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(Sobject s : scope) {
           s.put('bulk_load__c', false);
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        if(chain) {
        	Integer nextObjectNumber = 0;
        	if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.HOUSEHOLD_CHAIN)) {
	            if(objectNumber < objectNamesChainHousehold.size())
	               nextObjectNumber = objectNumber + 1;
	        }
	        else if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.TRANSACTION_CHAIN)) {
	            if(objectNumber < objectNamesChainTransaction.size())
                   nextObjectNumber = objectNumber + 1;
	        }
	        else if(chainName.equalsIgnoreCase(BatchBulkflagProcessor.INTERACTION_CHAIN)) {
	            if(objectNumber < objectNamesChainInteraction.size())
                   nextObjectNumber = objectNumber + 1;
	        }
	        
	        if(nextObjectNumber > 0) {
	        	bdie.dispatchChainBatch('BatchBulkflagProcessor', chainName, nextObjectNumber, chainFlag);
	        }
	        else {
            	bdie.dispatchBatch('BatchBulkflagProcessor', chainFlag);
	        }
        }
        else {
        	bdie.dispatchBatch('BatchBulkflagProcessor', chainFlag);
        }
    }
    
    public static testMethod void testBatch() {
        Account a = new Account(
    	   Name = 'Joe Dirt and Co', 
    	   TaAccountId__c = 23456, 
    	   bulk_load__c = true
    	); 
        insert a;
        
        Test.StartTest();
        BatchBulkflagProcessor batch = new BatchBulkflagProcessor('Account');
        batch.query += ' AND TaAccountId__c = 23456 LIMIT 3 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Account ta = [SELECT bulk_load__c FROM Account WHERE TaAccountId__c = :a.TaAccountId__c][0];
        System.AssertEquals(ta.bulk_load__c, false);
    }
}