Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Current Status of the Contact.</description>
        <inlineHelpText>Current Status of the Contact.</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <inlineHelpText>See Contact Status with real values that are mapped from these TA values</inlineHelpText>
        <label>TA Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecUpdateContactStatus.cls
global class BatchExecUpdateContactStatus implements Database.Batchable<sObject> {
    global final String Query;
    global BatchExecUpdateContactStatus (String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchUpdateContactStatus(scope);
    }    
    void DoBatchUpdateContactStatus(List<sObject> scope) {
        List<Contact> lstContact = (List<Contact>) scope;
        
        for(Contact c: lstContact) {
            if(c.STS__c == 'A'){
                c.Contact_Status__c = 'Active';
            }
        }
        Update lstContact;
    }    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }
    static testMethod void TestBatchExecUpdateContactStatus() {
       Test.startTest();
        Account acc = new Account(Name = 'Test Account');
        
        Contact ct =  new Contact (LastName = 'Test Contact',AccountId =acc.Id,Contact_Status__c = 'Active',STS__c = 'A');
        
        Contact ct1 =  new Contact (LastName = 'Test Contact1',AccountId =acc.Id,Contact_Status__c = 'Active',STS__c = 'A');
        
       /* Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 16;                
        insert o1;*/
        
       
        BatchExecUpdateContactStatus  reassign = new BatchExecUpdateContactStatus ('Select ID,Contact_Status__c,STS__c from Contact Limit 10');
        ID batchprocessid = Database.executeBatch(reassign,2);
      
        Test.StopTest();     
        
    }        
}