Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Salutation__c.object
<CustomObject>
    <description>TA Salutation</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salutations</relationshipLabel>
        <relationshipName>Salutations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Salutations</relationshipLabel>
        <relationshipName>Salutations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salutations</relationshipLabel>
        <relationshipName>Salutations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TA_Salutations_Id__c</fullName>
        <description>TA Salutations external Id</description>
        <externalId>true</externalId>
        <label>TA Salutations Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>salutation_code__c</fullName>
        <description>Salutation Code</description>
        <inlineHelpText>Salutation Code</inlineHelpText>
        <label>Salutation Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Salutation</label>
    <nameField>
        <label>Salutation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salutations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchSalutationLink.cls
global class BatchSalutationLink implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchSalutationLink(){
    	// original - WHERE TA_Salutations_Id__c != null and Contact__c = null and Household__c = null and Account__c = null';
        this.query = 'SELECT id, Contact__c, Account__c, TA_Salutations_Id__c, batch_process_count__c FROM Salutation__c WHERE batch_process_count__c = 1';
    }
    
    global BatchSalutationLink(Boolean chainFlag){
    	this();
    	this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Salutation__c c = (Salutation__c) s;
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }    
    

    global void execute(List<sObject> scope){
    }
    
    public static testMethod void testBatch() {
    	//this.query += ' LIMIT 1 '; 
    	Contact c = new Contact(
    	   FirstName = 'Joe', 
    	   LastName = 'Dirt', 
    	   TaContactId__c = '23456_01_I',
    	   bulk_load__c = true
    	);
    	insert c;   	
    	Account a = new Account(
    	   Name = 'Joe Dirt and Co', 
    	   TaAccountId__c = 23456,
    	   bulk_load__c = true
    	); 
    	insert a;    	     	
    	Salutation__c s1 = new Salutation__c(
    	   ta_salutations_Id__c = '23456_01_I_ENDOW',
    	   salutation_code__c = 'EDDOW',
    	   bulk_load__c = true,
    	   batch_process_count__c = 1
    	);
    	
    	insert s1;
    	Salutation__c s2 = new Salutation__c(
    	   ta_salutations_Id__c = '23456_00_I_ENDOW',
    	   salutation_code__c = 'EDDOW',
    	   bulk_load__c = true,
    	   batch_process_count__c = 1
    	);
    	insert s2;   
    	Salutation__c s3 = new Salutation__c(
    	   ta_salutations_Id__c = '23456_00_C_ENDOW',
    	   salutation_code__c = 'EDDOW',
    	   bulk_load__c = true,
    	   batch_process_count__c = 1
    	);
    	insert s3;        	 	
        
        Test.StartTest();
		BatchSalutationLink batch = new BatchSalutationLink();
		batch.query += ' and ta_salutations_Id__c in (\'23456_01_I_ENDOW\',\'23456_00_I_ENDOW\', \'23456_00_C_ENDOW\' ) LIMIT 3 ';
		ID batchprocessid = Database.executeBatch(batch);
		Test.StopTest();
    }
    
    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchSalutationLink', chainFlag);
    }
}