Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TA_Account_ID__c</fullName>
        <formula>TEXT(TaAccountId__c)</formula>
        <label>Legacy Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Classifications2</relationshipLabel>
        <relationshipName>Classifications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ta_classification_id__c</fullName>
        <externalId>true</externalId>
        <label>TA Classification ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>Ta_Account_Id__c</fullName>
        <label>Ta_Account_Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchClassificationsLink.cls
global class BatchClassificationsLink implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchClassificationsLink(){
    	// original - Where c.Contact__c = null and c.Organization__c = null and c.Household__c = null'
        // this.query = 'Select c.ta_classification_id__c , c.Contact__c, c.Organization__c, c.Id, c.Household__c From Classification__c c Where c.Contact__c = null and c.Organization__c = null and c.Household__c = null';
        this.query = 'Select c.ta_classification_id__c , c.Contact__c, c.Organization__c, c.Id, c.Household__c, c.batch_process_count__c From Classification__c c Where c.batch_process_count__c = 2';

    }
    
    global BatchClassificationsLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Classification__c c = (Classification__c) s;
            //Batch condition.
            if(c.Contact__c == null && c.Organization__c == null && c.Household__c == null) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	c.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }

    global void execute(List<sObject> scope){
        List<Integer> accountTaIds = new List<Integer>();
        List<Integer> householdTaIds = new List<Integer>();
        List<String> contactTaIds = new List<String>();
        
        // 0   1 2  3 4
        //xxx_00_C__a_b
		Orphan__c[] orphans = new List<Orphan__c>();         
        for(Sobject s : scope){
            Classification__c c = (Classification__c) s;
        	try {            
	            String[] cData = c.ta_classification_id__c.split('_');
	            
	            if(cData[2] == 'C' || cData[2] == 'G' || cData[2] == 'F' || cData[2] == 'O') {
	                accountTaIds.add(Integer.valueOf(cData[0]));
	            }
	            if(cData[2] == 'I') {
	                if(cData[1] == '00') {
	                    householdTaIds.add(Integer.valueOf(cData[0]));
	                }
	                else {
	                    contactTaIds.add(cData[0]+'_'+cData[1]+'_'+cData[2]);
	                }
	            }
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Classification__c',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchClassificationsLink',
        			ta_id__c=c.ta_classification_id__c,
        			object_id__c=s.id)
        		);
        	}	            
        }
        
        List<Account> accounts = [SELECT id, TaAccountId__c FROM Account WHERE TaAccountId__c IN :accountTaIds];
        Map<String, ID> accountsMap = new Map<String, ID>();
        for(Account account : accounts) {
            accountsMap.put(String.valueOf(account.TaAccountId__c), account.Id);
        }
        List<Household__c> households = [SELECT id, Ta_Account_Id__c FROM Household__c WHERE Ta_Account_Id__c IN :householdTaIds];
        Map<String, ID> householdsMap = new Map<String, ID>();
        for(Household__c household : households) {
            householdsMap.put(String.valueOf(household.Ta_Account_Id__c), household.Id);
        }
        List<Contact> contacts = [SELECT id, TaContactId__c FROM Contact WHERE TaContactId__c IN :contactTaIds];
        Map<String, ID> contactsMap = new Map<String, ID>();
        for(Contact contact : contacts) {
            contactsMap.put(contact.TaContactId__c, contact.Id);
        }
        
        for(Sobject s : scope){
            Classification__c c = (Classification__c) s;
            try {
	            String[] cData = c.ta_classification_id__c.split('_');
	            
	            if(cData[2] == 'C' || cData[2] == 'G' || cData[2] == 'F' || cData[2] == 'O') {
	                Id orgId = accountsMap.get(cData[0]);
	                if(orgId != null) {
	                    c.Organization__c = orgId;
	                }
	            }
	            else if(cData[2] == 'I') {
	                if(cData[1] == '00') {
	                    Id hhId = householdsMap.get(cData[0]);
	                    if(hhId != null) {
	                        c.Household__c = hhId;
	                    }
	                }
	                else {
	                    String contactId = contactsMap.get(cData[0]+'_'+cData[1]+'_'+cData[2]);
	                    if(contactId != null) {
	                        c.Contact__c = contactId;
	                    }
	                }
	            }
	            c.batch_process_count__c--;
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Classification__c',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchClassificationsLink',
        			ta_id__c=c.ta_classification_id__c,
        			object_id__c=s.id)
        		);
        	}	  	            
        }
        update scope;
		if(orphans.size()>0) insert orphans;          
    }

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchClassificationsLink', chainFlag);
    }
    
    public static testMethod void testBatch() {
        Contact c = new Contact(
           FirstName = 'Joe', 
           LastName = 'Dirt', 
           TaContactId__c = '12345_01_I',
           bulk_load__c = true
        );
        insert c;
        Classification__c c1 = new Classification__c(
           ta_classification_id__c = '12345_01_I_CODE_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 2
        );
        insert c1;
        
        Household__c h = new Household__c(
           Name = 'Mr. & Mrs. Joe Dirt', 
           Ta_Account_Id__c = 12345,
           bulk_load__c = true          
        );
        insert h;
        Classification__c c2 = new Classification__c(
           ta_classification_id__c = '12345_00_I_CODE_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 2
        );
        insert c2;
        
        Account a = new Account(
           Name = 'Joe Dirt and Co', 
           TaAccountId__c = 12345,
           bulk_load__c = true        
        );
        insert a;
        Classification__c c3 = new Classification__c(
           ta_classification_id__c = '12345_00_C_CODE_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 2
        );
        insert c3;
        
        Test.StartTest();
        BatchClassificationsLink batch = new BatchClassificationsLink();
        batch.query += ' and ta_classification_id__c in (\'12345_01_I_CODE_VALUE\',\'12345_00_I_CODE_VALUE\',\'12345_00_C_CODE_VALUE\' ) LIMIT 3 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Classification__c tc1 = [SELECT Contact__c FROM Classification__c WHERE ta_classification_id__c = :c1.ta_classification_id__c][0];
        System.AssertEquals(tc1.Contact__c, c.id);
        
        Classification__c tc2 = [SELECT Household__c FROM Classification__c WHERE ta_classification_id__c = :c2.ta_classification_id__c][0];
        System.AssertEquals(tc2.Household__c, h.id);
        
        Classification__c tc3 = [SELECT Organization__c FROM Classification__c WHERE ta_classification_id__c = :c3.ta_classification_id__c][0];
        System.AssertEquals(tc3.Organization__c, a.id);
    }
}