Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street1__c</fullName>
        <label>Street1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_message__c</fullName>
        <label>Response_message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Giving Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>installment_amount__c</fullName>
        <description>Installment Amount</description>
        <inlineHelpText>Installment Amount</inlineHelpText>
        <label>Installment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Giving__r.AccountId , Giving__r.Account.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Alias__c</fullName>
        <label>CC Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>IF(ISNULL(Giving__r.Recurring_Donation_Opportunity__c ), HYPERLINK(&apos;/&apos; + Giving__r.Oppty_Related_Contact__c, Giving__r.Oppty_Related_Contact__r.FirstName + &apos; &apos; + Giving__r.Oppty_Related_Contact__r.LastName) , HYPERLINK(&apos;/&apos; + Giving__r.Recurring_Donation_Opportunity__r.Oppty_Related_Contact__c, Giving__r.Recurring_Donation_Opportunity__r.Oppty_Related_Contact__r.FirstName + &apos; &apos; + Giving__r.Recurring_Donation_Opportunity__r.Oppty_Related_Contact__r.LastName) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giving__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Refund_Date__c</fullName>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_message__c</fullName>
        <label>Response_message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Refund #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <formula>if( ISPICKVAL(Transaction_Type__c ,&apos;PAYMENT&apos;),HYPERLINK(&quot;/&quot;&amp;Giving_Id__r.CC_EFT_Alias__c, Giving_Id__r.CC_EFT_Alias__r.Name),
HYPERLINK(&quot;/&quot;&amp; Refund__r.CC_Alias__c, Refund__r.CC_Alias__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CC &amp; EFT Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_NUMBER__c</fullName>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <formula>Account__r.Preferred_Address__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preferred Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REFERENCE__c</fullName>
        <externalId>true</externalId>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_URL__c</fullName>
        <label>Request URL</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <description>If the payment is rejected what is the message</description>
        <label>Response_Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sage_Response__c</fullName>
        <label>Sage_Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submit_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How many times the payment has been submitted for processing</description>
        <label>Submit_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecRefund_BATCH.cls
global class BatchExecRefund_BATCH implements Database.Batchable<sObject>,Database.AllowsCallouts {
    global final String Query;
 
    global BatchExecRefund_BATCH(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoRefundBatchStatus(scope);
    }

    void DoRefundBatchStatus(List<sObject> scope) {

        System.debug('###start1');

        Boolean Success;
        String strId;
        String M_ID;
        String M_KEY;

        String C_NAME;
        String C_ADDRESS;
        String C_CITY;
        String C_STATE;
        String C_ZIP;
        String C_COUNTRY;
        String C_EMAIL;
        String GUID;
        String T_CUSTOMER_NUMBER;
        String T_AMT;
        String T_SHIPPING;
        String T_TAX;
        String T_ORDERNUM;
        String C_TELEPHONE;
        String C_FAX;
        String C_SHIP_NAME;
        String C_SHIP_ADDRESS;
        String C_SHIP_CITY;
        String C_SHIP_STATE;
        String C_SHIP_ZIP;
        String C_SHIP_COUNTRY;

        for(sObject s : scope) {
            Transaction_Batch__c ObjTrasBatch = (Transaction_Batch__c)s;
            
            strId = BlankIsNull(ObjTrasBatch.Refund__c);
            M_ID = BlankIsNull(ObjTrasBatch.Merchant_id__c);
            M_KEY = BlankIsNull(ObjTrasBatch.Merchant_key__c);
            C_NAME = '';
            C_ADDRESS = '';
            C_CITY = '';
            C_STATE = '';
            C_ZIP = '';
            C_COUNTRY = '';
            C_EMAIL= '';
            GUID = BlankIsNull(ObjTrasBatch.GUID__c);
            T_CUSTOMER_NUMBER = '';
            T_AMT = '';
            T_SHIPPING = '';
            T_TAX = '';
            T_ORDERNUM = '';
            C_TELEPHONE = '';
            C_FAX = '';
            C_SHIP_NAME = '';
            C_SHIP_ADDRESS = '';
            C_SHIP_CITY = '';
            C_SHIP_STATE = '';
            C_SHIP_ZIP = '';
            C_SHIP_COUNTRY = '';

           If(strId != null && strId != ''){

                /*List<Opportunity> lstOpp = New List<Opportunity>
                ([Select ID, CC_EFT_Alias__r.Contact__r.Preferred_Address__r.City__c,CC_EFT_Alias__r.Account__r.Preferred_Address__r.City__c 
                    From Opportunity where ID=: strId]); */
                List<Refund__c> lstrefund = New List<Refund__c>
                ([Select ID
                    ,CC_Alias__r.Contact__r.Id
                    ,CC_Alias__r.Contact__r.Email
                    ,CC_Alias__r.Contact__r.FirstName
                    ,CC_Alias__r.Contact__r.LastName 
                    ,CC_Alias__r.Contact__r.Preferred_Address__r.Street_1__c
                    ,CC_Alias__r.Contact__r.Preferred_Address__r.City__c                     
                    ,CC_Alias__r.Contact__r.Preferred_Address__r.State__c
                    ,CC_Alias__r.Contact__r.Preferred_Address__r.Postal_Code__c
                    ,CC_Alias__r.Contact__r.Preferred_Address__r.Country__c
                    ,CC_Alias__r.Account__r.id
                    ,CC_Alias__r.Account__r.Name
                    ,CC_Alias__r.Account__r.Preferred_Address__r.Street_1__c
                    ,CC_Alias__r.Account__r.Preferred_Address__r.City__c 
                    ,CC_Alias__r.Account__r.Preferred_Address__r.State__c
                    ,CC_Alias__r.Account__r.Preferred_Address__r.Postal_Code__c
                    ,CC_Alias__r.Account__r.Preferred_Address__r.Country__c
                    ,Status__c,Response_message__c,Response_Code__c 
                    ,CC_Alias__r.Street1__c,CC_Alias__r.City__c,CC_Alias__r.State__c,CC_Alias__r.Zipcode__c
                    ,CC_Alias__r.Country__c
                   From Refund__c where id =: strId]);

                System.debug('###lstoppsize:' + lstrefund .size());
                if(lstrefund .size() == 1)
                {
                    Refund__c r = lstrefund[0];
                    
                    C_ADDRESS =  BlankIsNull(r.CC_Alias__r.Street1__c);
                    C_CITY =  BlankIsNull(r.CC_Alias__r.City__c);
                    C_STATE =  BlankIsNull(r.CC_Alias__r.State__c);
                    C_ZIP =   BlankIsNull(r.CC_Alias__r.Zipcode__c);
                    C_COUNTRY = BlankIsNull(r.CC_Alias__r.Country__c);
                    
                    String FullAddress = C_ADDRESS + C_CITY + C_STATE + C_ZIP + C_COUNTRY;
                    /*if(FullAddress != null || FullAddress !='') {
                        C_COUNTRY = BlankIsNull(System.Label.SageDefaultCountry);
                    }*/
                    
                    if (r.CC_Alias__r.Contact__c != null){
                        //C_NAME = '';
                        C_NAME = BlankIsNull(r.CC_Alias__r.Contact__r.FirstName) + '' + BlankIsNull(r.CC_Alias__r.Contact__r.LastName);
                        if(FullAddress == null || FullAddress =='') {
                            C_ADDRESS =  BlankIsNull(r.CC_Alias__r.Contact__r.Preferred_Address__r.Street_1__c);
                            C_CITY =  BlankIsNull(r.CC_Alias__r.Contact__r.Preferred_Address__r.City__c);
                            C_STATE =  BlankIsNull(r.CC_Alias__r.Contact__r.Preferred_Address__r.State__c);
                            C_ZIP =   BlankIsNull(r.CC_Alias__r.Contact__r.Preferred_Address__r.Postal_Code__c);
                            C_COUNTRY = BlankIsNull(r.CC_Alias__r.Contact__r.Preferred_Address__r.Country__c);
                        }
                        C_EMAIL = BlankIsNull(r.CC_Alias__r.Contact__r.Email);
                        T_CUSTOMER_NUMBER = BlankIsNull(r.CC_Alias__r.Contact__r.Id);

                    }
                    else if (r.CC_Alias__r.Account__c != null) {
                        C_NAME = BlankIsNull(r.CC_Alias__r.Account__r.Name);
                        if(FullAddress == null || FullAddress =='') {
                            C_ADDRESS =  BlankIsNull(r.CC_Alias__r.Account__r.Preferred_Address__r.Street_1__c);
                            C_CITY =  BlankIsNull(r.CC_Alias__r.Account__r.Preferred_Address__r.City__c);
                            C_STATE =  BlankIsNull(r.CC_Alias__r.Account__r.Preferred_Address__r.State__c);
                            C_ZIP =   BlankIsNull(r.CC_Alias__r.Account__r.Preferred_Address__r.Postal_Code__c);
                            C_COUNTRY = BlankIsNull(r.CC_Alias__r.Account__r.Preferred_Address__r.Country__c);
                        }
                        C_EMAIL = '';
                        T_CUSTOMER_NUMBER = BlankIsNull(r.CC_Alias__r.Account__r.Id);
                    }

                    String strAmt='';
                    if(ObjTrasBatch.Payment_Amount__c != null){
                        strAmt= ObjTrasBatch.Payment_Amount__c.toPlainString();
                    }
                    if(BlankIsNull(C_COUNTRY) == '') {
                        C_COUNTRY = BlankIsNull(System.Label.SageDefaultCountry);
                    }
                    
                    T_AMT = BlankIsNull(strAmt);
                    T_SHIPPING = '';
                    T_TAX = '';
                    T_ORDERNUM = '';
                    C_TELEPHONE = '';
                    C_FAX = '';
                    C_SHIP_NAME = '';
                    C_SHIP_ADDRESS = '';
                    C_SHIP_CITY = '';
                    C_SHIP_STATE = '';
                    C_SHIP_ZIP = '';
                    C_SHIP_COUNTRY  = '';
                                       
                    Success = false;
                     SageTransactionProcess objSageTP = new SageTransactionProcess();
                    
                    Success = objSageTP.SageRefundRequest(M_ID,M_KEY,C_NAME,C_ADDRESS,C_CITY,C_STATE,C_ZIP,C_COUNTRY,C_EMAIL,GUID,
                                        T_CUSTOMER_NUMBER,T_AMT,T_SHIPPING,T_TAX,T_ORDERNUM,C_TELEPHONE,C_FAX,C_SHIP_NAME,
                                        C_SHIP_ADDRESS,C_SHIP_CITY,C_SHIP_STATE,C_SHIP_ZIP,C_SHIP_COUNTRY);
                                        
                    ObjTrasBatch.Process_date__c = System.Today();                    
                    If(Success == true && objSageTP.strStatus =='A')
                    {
                      if(ObjTrasBatch.Status__c != null && ObjTrasBatch.Status__c == 'FAIL') {
                          ObjTrasBatch.Response_Code__c = '';
                          ObjTrasBatch.Response_message__c = '';
                      }
                      ObjTrasBatch.Status__c = 'SUCCESS';
                      ObjTrasBatch.Submit_count__c = ObjTrasBatch.Submit_count__c + 1 ;
                    } else
                    {
                       ObjTrasBatch.Submit_count__c = ObjTrasBatch.Submit_count__c + 1 ;
                       ObjTrasBatch.Response_message__c = objSageTP.Response_message;
                       if(objSageTP.isTimeoutError == true) {
                           ObjTrasBatch.Status__c = 'REVIEW';
                       } else {
                           ObjTrasBatch.Status__c = 'FAIL';
                       }
                       if(objSageTP.Response_Code != ''){                           
                           ObjTrasBatch.Response_Code__c = objSageTP.Response_Code;
                       }
                    }
                    ObjTrasBatch.Request_URL__c = objSageTP.ReqURL;
                    
                    ObjTrasBatch.ORDER_NUMBER__c =  objSageTP.ORDER_NUMBER;
                    ObjTrasBatch.Sage_Response__c = objSageTP.SageResponse;
                    ObjTrasBatch.REFERENCE__c = objSageTP.REFERENCE;
                    //lstbatch.add(ObjTrasBatch);
                    Update ObjTrasBatch;
                    /*
                    List<Opportunity> objOpp = new List<Opportunity>([Select Id From Opportunity Where Id =: strId]);
                    if(objOpp.Size()>0)
                    {
                        
                        Update objOpp;
                    } */
                    
                    r.Status__c =  ObjTrasBatch.Status__c;
                    r.Response_Code__c =  ObjTrasBatch.Response_Code__c;
                    r.Response_message__c = ObjTrasBatch.Response_message__c;
                    Update r;
                }               
            }
        }
        
        /*if(lstbatch != null && lstbatch.size()>0) 
        {
            //Insert lstbatch;
            
        }*/

    }
        
    Private String BlankIsNull(String Value)
    {
        if(Value == null) 
            return '';
        else
            return Value; 
    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

   /* static testMethod void TestBatchExecTransaction_Batch() {
       Test.startTest();
        Opportunity o = new Opportunity();
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 16;
        insert o1;
        
       
        BatchExecTransaction_Batch reassign = new BatchExecTransaction_Batch ('Select ID,Payment_Date__c,Payment_Amount__c,SFDC_GIVING_NUMBER__c from Opportunity Where Payment_Date__c = Today Limit 2');
        ID batchprocessid = Database.executeBatch(reassign,2);
 
        Test.StopTest();     
        
    }    
    */
    
    static testMethod void TestBatchExecRefund_BATCH() {
       Test.startTest();
        Account a = new Account(Name = 'Test Account');
        Contact c = new Contact(Lastname = 'Contact LastName' , AccountId = a.Id);
        
        CC_Alias__c ccA = new   CC_Alias__c();
        ccA.Account__c = a.Id;
        ccA.Contact__c = c.Id;
        insert ccA;
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        //o1.Payment_Amount__c= 16;
        o1.Installment_Amount__c= 16;
        
        insert o1;
               
        
        /*Refund__c re = new Refund__c();
        re.Giving__c = o1.Id;
        re.Status__c = 'Process';        
        re.CC_Alias__c = ccA.Id;
        re.Refund_Amount__c = 8;
        re.refund_Date__c = System.Today();
        insert re;*/
        
        Transaction_Batch__c tb = new Transaction_Batch__c();
        tb.Giving_Id__c = o1.Id;
        tb.Merchant_Id__c = o1.Id;
        tb.Merchant_Key__c = '66776666';
        tb.GUID__c = 'test';
        //tb.Refund__c = re.Id;
        tb.Transaction_Type__c = 'REFUND';
        insert tb;
        
        
        String strQ = '';
        
        StrQ = 'SELECT  Batch_Number__c,GUID__c,Merchant_Id__c,Merchant_Key__c,Giving_Id__c,Payment_Amount__c,Pledge_Number__c,Process_date__c,Response_Code__c,Response_Message__c,Status__c,Submit_Count__c,Transaction_Type__c ' +
            ' , ORDER_NUMBER__c , Sage_Response__c , REFERENCE__c , Refund__c ' +
            ' FROM transaction_batch__c WHERE id=\'' + tb.id + '\' Limit 1';

        BatchExecRefund_BATCH reassign = new BatchExecRefund_BATCH (StrQ);
        ID batchprocessid = Database.executeBatch(reassign,2);
 
        Test.StopTest();     
        
    }
}