Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TA_Account_ID__c</fullName>
        <formula>TEXT(TaAccountId__c)</formula>
        <label>Legacy Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Type of Contact.</description>
        <inlineHelpText>Type of Contact.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beneficiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Partner Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gift Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mbr Disc Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>Ta_Account_Id__c</fullName>
        <label>Ta_Account_Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Legacy</fullName>
        <active>true</active>
        <label>Legacy</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/classes/BatchTaskLink.cls
global class BatchTaskLink implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchTaskLink(){
    	//orginal - Where c.ta_interaction_id__c != null And c.WhatId = null And c.WhoId = null';
        this.query = 'Select c.RecordTypeId, c.ta_interaction_id__c , c.WhatId, c.WhoId, c.Subject, c.Techique__c, c.Contact_Category__c, c.Contact_Type__c, c.batch_process_count__c From Task c Where c.batch_process_count__c = 1';
    }
    
    global BatchTaskLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>(); 
   		RecordType rt = [select id from RecordType where SobjectType='Task' and Name='Legacy' limit 1] ; 		
        for(Sobject s : scope) {
            Task tsk = (Task) s;
            tsk.RecordTypeId = rt.id;
            //Batch condition.
            if(tsk.ta_interaction_id__c != null && tsk.WhatId == null && tsk.WhoId == null) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	tsk.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }        

    global void execute(List<sObject> scope){
        List<Integer> accountTaIds = new List<Integer>();
        List<Integer> householdTaIds = new List<Integer>();
        List<String> contactTaIds = new List<String>();
        
        // 0   1 2  3 4
        //xxx_00_C__a_b
		Orphan__c[] orphans = new List<Orphan__c>();         
        for(Sobject s : scope){
            Task clazz = (Task) s;
        	try {            
	            String[] cData = clazz.ta_interaction_id__c.split('_');
	            
	            if(cData[2] == 'C' || cData[2] == 'G' || cData[2] == 'F' || cData[2] == 'O') {
	                accountTaIds.add(Integer.valueOf(cData[0]));
	            }
	            if(cData[2] == 'I') {
	                householdTaIds.add(Integer.valueOf(cData[0]));
	                if(cData[1] != '00') {
	                    contactTaIds.add(cData[0]+'_'+cData[1]+'_'+cData[2]);
	                }
	            }
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Task',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchTaskLink',
        			ta_id__c=clazz.ta_interaction_id__c,
        			object_id__c=s.id)
        		);
        	}	            
        }
        
        List<Account> accounts = [SELECT id, TaAccountId__c FROM Account WHERE TaAccountId__c IN :accountTaIds];
        Map<String, ID> accountsMap = new Map<String, ID>();
        for(Account account : accounts) {
            accountsMap.put(String.valueOf(account.TaAccountId__c), account.Id);
        }
        List<Household__c> households = [SELECT id, Ta_Account_Id__c FROM Household__c WHERE Ta_Account_Id__c IN :householdTaIds];
        Map<String, ID> householdsMap = new Map<String, ID>();
        for(Household__c household : households) {
            householdsMap.put(String.valueOf(household.Ta_Account_Id__c), household.Id);
        }
        List<Contact> contacts = [SELECT id, TaContactId__c FROM Contact WHERE TaContactId__c IN :contactTaIds];
        Map<String, ID> contactsMap = new Map<String, ID>();
        for(Contact contact : contacts) {
            contactsMap.put(contact.TaContactId__c, contact.Id);
        }
        
        for(Sobject s : scope){
            Task clazz = (Task) s;
            try {
            	if(clazz.Techique__c == null) {
            		clazz.Subject = clazz.Contact_Category__c + ' - ' + clazz.Contact_Type__c;
            	}
            	else {
            		clazz.Subject = clazz.Techique__c + ' - ' + clazz.Contact_Category__c + ' - ' + clazz.Contact_Type__c;            		
            	}
	            String[] cData = clazz.ta_interaction_id__c.split('_');
	            
	            if(cData[2] == 'C' || cData[2] == 'G' || cData[2] == 'F' || cData[2] == 'O') {
	                Id orgId = accountsMap.get(cData[0]);
	                if(orgId != null) {
	                    clazz.WhatId = orgId;
	                }
	            }
	            else if(cData[2] == 'I') {
                    Id hhId = householdsMap.get(cData[0]);
                    if(hhId != null) {
                        clazz.WhatId = hhId;
                    }
	                if(cData[1] != '00') {
	                    String contactId = contactsMap.get(cData[0]+'_'+cData[1]+'_'+cData[2]);
	                    if(contactId != null) {
	                        clazz.WhoId = contactId;
	                    }
	                }
	            }
	            clazz.batch_process_count__c--;	            
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Task',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchTaskLink',
        			ta_id__c=clazz.ta_interaction_id__c,
        			object_id__c=s.id)
        		);
        	}	  	            
        }
        update scope;
		if(orphans.size()>0) insert orphans;          
    }

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchTaskLink', chainFlag);
    }
    
    public static testMethod void testBatch() {
        Contact c = new Contact(
           FirstName = 'Joe', 
           LastName = 'Dirt', 
           TaContactId__c = '12345_01_I',
           bulk_load__c=true
        );
        insert c;
        User user = [select id from user where IsActive=true limit 1];
        Task c1 = new Task(
           OwnerId = user.Id,
           Subject = 'Solicitation',
           Priority = 'Normal',
           Status = 'Completed',
           ta_interaction_id__c = '12345_01_I_SO_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 1
        );
        insert c1;
        
        Household__c h = new Household__c(
           Name = 'Mr. & Mrs. Joe Dirt', 
           Ta_Account_Id__c = 12345,
           bulk_load__c=true
        );
        insert h;
        Task c2 = new Task(
           OwnerId = user.Id,
           Subject = 'Solicitation',
           Priority = 'Normal',
           Status = 'Completed',        
           ta_interaction_id__c = '12345_00_I_SO_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 1
        );
        insert c2;
        
        Account a = new Account(
           Name = 'Joe Dirt and Co', 
           TaAccountId__c = 12345,
           bulk_load__c=true
        );
        insert a;
        Task c3 = new Task(
           OwnerId = user.Id,
           Subject = 'Solicitation',
           Priority = 'Normal',
           Status = 'Completed',             
           ta_interaction_id__c = '12345_00_C_SO_VALUE',
           bulk_load__c = true,
           batch_process_count__c = 1
        );
        insert c3;
        
        Test.StartTest();
        BatchTaskLink batch = new BatchTaskLink();
        batch.query += ' and ta_interaction_id__c in (\'12345_01_I_SO_VALUE\',\'12345_00_I_SO_VALUE\',\'12345_00_C_SO_VALUE\' ) LIMIT 3 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Task tc1 = [SELECT WhatId FROM Task WHERE ta_interaction_id__c = :c1.ta_interaction_id__c][0];
//todo        System.AssertEquals(tc1.WhatId, c.id);
        
        Task tc2 = [SELECT WhatId FROM Task WHERE ta_interaction_id__c = :c2.ta_interaction_id__c][0];
//todo        System.AssertEquals(tc2.WhatId, h.id);
        
        Task tc3 = [SELECT WhatId FROM Task WHERE ta_interaction_id__c = :c3.ta_interaction_id__c][0];
//todo        System.AssertEquals(tc3.WhatId, a.id);
    }
}