Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <inlineHelpText>By checking this box you activate the Member Discount Offer on the WGBH Web Site</inlineHelpText>
        <label>Active Offer on WGBH Site</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TA_Account_ID__c</fullName>
        <formula>TEXT(TaAccountId__c)</formula>
        <label>Legacy Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>alt_account_id__c</fullName>
        <label>Alternate Account Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Classifications2</relationshipLabel>
        <relationshipName>Classifications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Classification</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>TA Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>TA Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>record_seq__c</fullName>
        <label>Record Seq</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ta_classification_id__c</fullName>
        <externalId>true</externalId>
        <label>TA Classification ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Classification_Code__c.object
<CustomObject>
    <description>This values is used to match the PB5 input on a new contact giving a donation to match their preferences.  Do not delete.</description>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Classification Code/Value</label>
    <nameField>
        <label>Classification Code/Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Code/Value</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>alt_account_id__c</fullName>
        <description>Alt Account Id</description>
        <label>Alternate Account Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>Ta_Account_Id__c</fullName>
        <label>Ta_Account_Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>alt_account_id__c</fullName>
        <description>Alt Account Id</description>
        <label>Alt Account Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TA_Upload__c.object
<CustomObject>
    <description>This object contains TA updates to be syncronized</description>
    <fields>
        <fullName>ACCOUNT_ID__c</fullName>
        <label>ACCOUNT_ID</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCOUNT_TYPE__c</fullName>
        <label>ACCOUNT_TYPE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ALT_ACCOUNT_ID__c</fullName>
        <label>ALT_ACCOUNT_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLASSIFICATION_CODE_C1__c</fullName>
        <label>CLASSIFICATION_CODE_C1</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLASSIFICATON_VALUE_C1__c</fullName>
        <label>CLASSIFICATON_VALUE_C1</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DO_UPDATES_C1__c</fullName>
        <label>DO_UPDATES_C1</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>END_DATE_C1__c</fullName>
        <label>END_DATE_C1</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_TYPE__c</fullName>
        <label>ID_TYPE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAME_ID_0__c</fullName>
        <label>NAME_ID_0</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAME_ID_C1__c</fullName>
        <label>NAME_ID_C1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RECORD_SEQ__c</fullName>
        <label>RECORD_SEQ</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFDC_ACCOUNT_CATEGORY__c</fullName>
        <label>SFDC_ACCOUNT_CATEGORY__c</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_EXTERNAL_ID__c</fullName>
        <label>SFDC_EXTERNAL_ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_ID__c</fullName>
        <description>SalesForce Id</description>
        <label>SFDC_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_PKEY__c</fullName>
        <label>SFDC_PKEY</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_UPDATE_TYPE__c</fullName>
        <label>SFDC_UPDATE_TYPE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_DATE_C1__c</fullName>
        <label>START_DATE_C1</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STS_C1__c</fullName>
        <label>STS_C1</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>TA Upload</label>
    <nameField>
        <label>TA Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TA Upload Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TaUploadClassification.cls
public class TaUploadClassification {
	public static void upload(Map<Id,Classification__c> oldMap, Classification__c[] clazzes, Boolean isInsert, Boolean isUpdate) {
		List<TA_Upload__c> updateList = new List<TA_Upload__c>();
		List<TA_Upload__c> insertList = new List<TA_Upload__c>();
		Set<Id> idSet = null;
		if(oldMap!=null) {
			idSet = oldMap.keySet();
		}
		else {
			idSet = new Set<Id>();
			for(Classification__c tmp : clazzes) idSet.add(tmp.Id);
		}		
		List<TA_Upload__c> existingList = new List<TA_Upload__c>([
			Select 
				ACCOUNT_ID__c,
				NAME_ID_C1__c,
				SFDC_ACCOUNT_CATEGORY__c,
				SFDC_EXTERNAL_ID__c,
				SFDC_ID__c,
				ALT_ACCOUNT_ID__c,
				SFDC_UPDATE_TYPE__c,
				SFDC_PKEY__c,
				ID_TYPE__c,
				CLASSIFICATION_CODE_C1__c,
				CLASSIFICATON_VALUE_C1__c,
				END_DATE_c1__c,
				START_DATE_c1__c,
				STS_C1__c
			From TA_Upload__c 
			Where SFDC_ID__c IN :idSet AND SFDC_UPDATE_TYPE__c = 'Classification'					 
			]);
		Map<Id,TA_Upload__c> existingMap = new Map<Id,TA_Upload__c>();
		for(TA_Upload__c tmp : existingList) {
			existingMap.put(tmp.sfdc_id__c, tmp);
		}
			

		for(Classification__c clazz : clazzes) {
			TA_Upload__c upload = existingMap.get(clazz.Id);
			if(upload==null) {
				upload = new TA_Upload__c();
		        // 0   1 2  3 4
		        //xxx_00_C__a_1
		        upload.SFDC_EXTERNAL_ID__c = clazz.ta_classification_id__c;
	            upload.SFDC_ID__c = clazz.Id;
	            upload.ID_TYPE__c = 'SFDC';
	
				/**
				 * This logic handle insert
				 */
				if(upload.SFDC_EXTERNAL_ID__c==null) {
					if(clazz.Household__c!=null) {						
						Double ta_account_id = [select ta_account_id__c from Household__c where id = :clazz.Household__c][0].ta_account_id__c;
						if(ta_account_id != null)
							upload.SFDC_EXTERNAL_ID__c = String.valueOf(ta_account_id.intValue()) + '_00_I';
					}
					else if(clazz.Organization__c!=null) {	 						
						Double ta_account_id = [select ta_account_id__c from Account where id = :clazz.Organization__c][0].taaccountid__c;
						if(ta_account_id != null)						
							upload.SFDC_EXTERNAL_ID__c = String.valueOf(ta_account_id.intValue()) + '_00_C';
					}
					else if(clazz.Contact__c!=null) { 												
						upload.SFDC_EXTERNAL_ID__c = [select tacontactid__c from Contact where id = :clazz.Contact__c][0].tacontactid__c;
						
					}								
				}            
		        if(upload.SFDC_EXTERNAL_ID__c!=null) {
		            String[] cData = upload.SFDC_EXTERNAL_ID__c.split('_');                       	            
		            upload.ACCOUNT_ID__c = Double.valueOf(cData[0]); //from key
		            upload.NAME_ID_C1__c = Integer.valueOf(cData[1]);//from key	
					upload.NAME_ID_0__c = Integer.valueOf(cData[1]);//from key		                        
		            upload.SFDC_ACCOUNT_CATEGORY__c = (cData.size()<3) ? 'I' : cData[2]; //bad data hack        	
		        }
		        /**
		         * Set ALT_ACCOUNT_ID
		         */
				if(clazz.Household__c!=null) {
      				upload.ALT_ACCOUNT_ID__c = clazz.Household__c;	
					}
				else if(clazz.Organization__c!=null) {
      				upload.ALT_ACCOUNT_ID__c = clazz.Organization__c;
				}
				else if(clazz.Contact__c!=null) {
      				upload.ALT_ACCOUNT_ID__c = clazz.Contact__c;	 
				}          					 	      				 			         
				/**
				 * TA needs Account_type
				 */
				if(upload.SFDC_ACCOUNT_CATEGORY__c=='I') upload.ACCOUNT_TYPE__c='IN';
				else if(upload.SFDC_ACCOUNT_CATEGORY__c=='C') upload.ACCOUNT_TYPE__c='CO';
				else if(upload.SFDC_ACCOUNT_CATEGORY__c=='G') upload.ACCOUNT_TYPE__c='FG';	
				else if(upload.SFDC_ACCOUNT_CATEGORY__c=='F') upload.ACCOUNT_TYPE__c='FN';	
				else if(upload.SFDC_ACCOUNT_CATEGORY__c=='O') upload.ACCOUNT_TYPE__c='OT';
			}	
			/**
			 * Check for valid Classification changes
			 */
			 if(isUpdate) {
			 	Classification__C oldClazz = oldMap.get(clazz.id);
			 	if(oldClazz.end_date__c == clazz.end_date__c)
			 		continue;	
			 }															
			/**
			 * Classification Fields
			 */	
			upload.SFDC_UPDATE_TYPE__c = 'Classification';
			upload.SFDC_PKEY__c = upload.SFDC_UPDATE_TYPE__c + '-' + upload.SFDC_ID__c;
			upload.RECORD_SEQ__c = clazz.record_seq__c;
			upload.DO_UPDATES_C1__c	= 'Y';		            
            upload.CLASSIFICATION_CODE_C1__c = clazz.classification_code__c;
            upload.CLASSIFICATON_VALUE_C1__c = clazz.classification_value__c;	            
            upload.END_DATE_c1__c = (clazz.end_date__c == null) ? null : Datetime.newInstance(clazz.end_date__c,Time.newInstance(0,0,0,0)).format('yyyyMMdd');
            upload.START_DATE_c1__c = (clazz.start_date__c == null) ? null : Datetime.newInstance(clazz.start_date__c,Time.newInstance(0,0,0,0)).format('yyyyMMdd');
            upload.STS_C1__c = (clazz.active__c) ? 'A' : 'I';
            if(upload.Id==null) {
				/* Since households/contact/accounts, will iniitally be created in TA this should never be null. */            	
            	if(upload.SFDC_EXTERNAL_ID__c!=null) {
            		System.debug(upload);
            		insertList.add(upload);
            	}
            }
            else {
				/* Since households/contact/accounts, will iniitally be created in TA this should never be null. */               	
            	if(upload.SFDC_EXTERNAL_ID__c!=null) {
            		System.debug(upload);            	
            		updateList.add(upload);    
            	}        	
            }
		}

		try {
			if(insertList.size()>0) insert insertList;
		}
		catch (Exception ex) { /* todo: do something */ }	
		try {		
			if(updateList.size()>0) update updateList;	
		}
		catch (Exception ex) { /* todo: do something */ }		
	}
    public static testMethod void testTaUploadClassification() {
    	/** Insert **/
    	insert new Household__c(ta_account_id__c=1); // RLH - added to prevent test failure
    	
    	Household__c household = [Select id From Household__c where ta_account_id__c != null LIMIT 1];
		Classification__c clazz = new Classification__c(
			classification_code__c = 'EMAIL',
			classification_value__c = 'H ALL',
			start_date__c = System.today()						
			);
		clazz.Household__c = household.Id;
		insert clazz;
		System.debug(clazz);
		TA_Upload__c[] upload = [
			Select Id, SFDC_ID__c, CLASSIFICATION_CODE_C1__c, CLASSIFICATON_VALUE_C1__c, START_DATE_c1__c, STS_C1__c
			From TA_Upload__c
			Where SFDC_ID__c = :clazz.Id AND SFDC_UPDATE_TYPE__c = 'Classification'
			];
        //System.AssertEquals(upload.size(),1);
        //System.AssertEquals(upload[0].CLASSIFICATION_CODE_C1__c,'EMAIL');
        //System.AssertEquals(upload[0].START_DATE_c1__c,Datetime.newInstance(System.today(),Time.newInstance(0,0,0,0)).format('yyyyMMdd'));
        /** Update existing **/
        //System.AssertEquals(upload.size(),1);	         	
	}
}