Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <inlineHelpText>By checking this box you activate the Member Discount Offer on the WGBH Web Site</inlineHelpText>
        <label>Active Offer on WGBH Site</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Code_Value__c</fullName>
        <label>Classification Code Value</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preference_Value__c</fullName>
        <inlineHelpText>Related to Preference</inlineHelpText>
        <label>Preference Value</label>
        <picklist>
            <controllingField>Preference__c</controllingField>
            <picklistValues>
                <fullName>@89.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>@Cape &amp; Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>@Classical Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>@GBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>@GBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>@Parents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89.7 WGBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99.5 WCRB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledgments via Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address is Incorrect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aisle Seat for Ticket Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Opt Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analog Cable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Renewal Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Report via Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preference__c</fullName>
        <label>Preference</label>
        <picklist>
            <controllingField>Classification_Type__c</controllingField>
            <picklistValues>
                <fullName>Acknowledgement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Gift Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Handling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Range (pledge reported)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anonymous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Append</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Solicitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Subscribe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Unsubscribe via AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Unsubscribe via Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Survey: Email Update Sign-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Survey: First Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Survey: Likelihood to recommend event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Survey: Satisfaction with event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Survey: Send More Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Great Blue Hill Society</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Grouping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Donor Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gift Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MemberCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Classification</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>TA Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_tabname__c</fullName>
        <description>delete when you can untangle the visual force page</description>
        <label>Classification Tab Name X</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>TA Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Classification_Code__c.object
<CustomObject>
    <description>This values is used to match the PB5 input on a new contact giving a donation to match their preferences.  Do not delete.</description>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>code_description__c</fullName>
        <label>Classification Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value_description__c</fullName>
        <label>Classification Value Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Classification Code/Value</label>
    <nameField>
        <label>Classification Code/Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Code/Value</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>comments__c</fullName>
        <description>Comments</description>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/classes/TabsClassificationsControllerNew.cls
public class TabsClassificationsControllerNew {

    public List<Classification__c> classifications {
        get {
             return this.getClassifications();
        }
        set;
    }
    
    public String Delid{get;set;} 
    public string id{get;set;}
    public String Tablabel{get;set;}
    public String RecordType{get;set;}
    
    public String recordId {get; set;}
    public String recordName {get; set;}
    public String sObjectType {get; set;}
    public String labelAppeal {get;set;}
    public String labelBenefit {get;set;}
    public String labelCommunication {get;set;}
    public String labelDatatagging {get;set;}
    public String labelMemberCategory {get;set;}
    public String labelOngoingMembership {get;set;}
    public String labelBoards {get;set;}
    public String labelStation {get;set;}
    public String labelSurveyDisability {get;set;}
    public String labelVolunteer {get;set;}
    public String strObjectId {get;set;}
    public String strClsObjectId {get;set;}
        
    Public List<Classification__c> lstAppeal{get; set;}
    Public List<Classification__c> lstBenefit{get; set;}
    Public List<Classification__c> lstCommunication{get; set;}
    Public List<Classification__c> lstDatatagging{get; set;}
    Public List<Classification__c> lstMemberCategory{get; set;}
    Public List<Classification__c> lstOngoingMembership{get; set;}
    Public List<Classification__c> lstBoards{get; set;}
    Public List<Classification__c> lstStation{get; set;}
    Public List<Classification__c> lstSurveyDisability{get; set;}
    Public List<Classification__c> lstVolunteer{get; set;}
    
    public TabsClassificationsControllerNew() {
        
        Schema.DescribeSObjectResult resultkeyPrefix = Classification__c.sObjectType.getDescribe();
        strObjectId = resultkeyPrefix.getKeyPrefix();
        strClsObjectId = System.Label.classification_object_ID;
        id=ApexPages.CurrentPage().getParameters().get('id');
        Delid='aaa';
        system.debug('__10__'+sObjectType);
        labelAppeal = 'Appeal Preferences';
        labelBenefit = 'Benefit Preferences';        
        labelCommunication = 'Communication Preferences';
        labelDatatagging = 'Data Tagging & Scores';
        labelMemberCategory = 'Member Category';
        labelOngoingMembership = 'Ongoing Membership';
        labelBoards = 'Station Boards and Committees';
        labelStation = 'Station Partners';
        labelSurveyDisability = 'Survey, Disability and Event Information';
        labelVolunteer = 'Volunteer Preferences';
                
    }
    
    public Classification__c[] getClassifications() {
        List<Classification__c> classifications = null;           
                
        system.debug('__sObjectType__'+sObjectType); 
        
        if(sObjectType != null){
            
            if(sObjectType == 'Contact') {                
                lstAppeal= [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Appeal Preferences'];    
                if(lstAppeal.size()>0){                        
                    labelAppeal = 'Appeal Preferences' +' '+'['+String.valueof(lstAppeal.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstAppeal = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Appeal Preferences'];
                if(lstAppeal.size()>0){
                    labelAppeal = 'Appeal Preferences' +' '+'['+String.valueof(lstAppeal.size()) +']';
                }
            }           
        }    
               
        if(sObjectType != null){
            
            if(sObjectType == 'Contact') {                
                lstBenefit= [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Benefit Preferences'];    
                if(lstBenefit.size()>0){                        
                    labelBenefit = 'Benefit Preferences' +' '+'['+String.valueof(lstBenefit.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstBenefit = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Benefit Preferences'];
                if(lstBenefit.size()>0){
                    labelBenefit = 'Benefit Preferences' +' '+'['+String.valueof(lstBenefit.size()) +']';
                }
            }           
        }    
        
        
        if(sObjectType != null){            
            if(sObjectType == 'Contact') {
                lstCommunication = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Communication Preferences'];    
                if(lstCommunication.size()>0){    
                    labelCommunication = 'Communication Preferences' +' '+'['+String.valueof(lstCommunication.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstCommunication = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Communication Preferences'];
                if(lstCommunication.size()>0){
                    labelCommunication = 'Communication Preferences' +' '+'['+String.valueof(lstCommunication.size()) +']';
                        
                }
            }           
        }
        
        if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstDatatagging= [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Data Tagging & Scores'];                   
                if(lstDatatagging.size()>0){                        
                    labelDatatagging = 'Data Tagging & Scores' +' '+'['+String.valueof(lstDatatagging.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstDatatagging = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Data Tagging & Scores'];
                if(lstDatatagging.size()>0){                        
                    labelDatatagging = 'Data Tagging & Scores' +' '+'['+String.valueof(lstDatatagging.size()) +']';
                }
            }           
         }
         
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstMemberCategory = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Member Category'];                   
                if(lstMemberCategory.size()>0){                        
                    labelMemberCategory = 'Member Category' +' '+'['+String.valueof(lstMemberCategory.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstMemberCategory = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Member Category'];
                if(lstMemberCategory.size()>0){                        
                    labelMemberCategory = 'Member Category' +' '+'['+String.valueof(lstMemberCategory.size()) +']';
                }
            }           
         }
         
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstOngoingMembership = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Ongoing Membership'];                   
                if(lstOngoingMembership.size()>0){                        
                    labelOngoingMembership = 'Ongoing Membership' +' '+'['+String.valueof(lstOngoingMembership.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstOngoingMembership = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Ongoing Membership'];
                if(lstOngoingMembership.size()>0){                        
                    labelOngoingMembership = 'Ongoing Membership' +' '+'['+String.valueof(lstOngoingMembership.size()) +']';
                }
            }           
         }
        
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstBoards = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Station Boards and Committees'];                   
                if(lstBoards.size()>0){                        
                    labelBoards = 'Station Boards and Committees' +' '+'['+String.valueof(lstBoards.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstBoards = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Station Boards and Committees'];
                if(lstBoards.size()>0){                        
                    labelBoards = 'Station Boards and Committees' +' '+'['+String.valueof(lstBoards.size()) +']';
                }
            }           
         }
         
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstStation = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Station Partners'];                   
                if(lstStation.size()>0){                        
                    labelStation = 'Station Partners' +' '+'['+String.valueof(lstStation.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstStation= [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Station Partners'];
                if(lstStation.size()>0){                        
                    labelStation = 'Station Partners' +' '+'['+String.valueof(lstStation.size()) +']';
                }
            }           
         }
         
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstSurveyDisability = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Survey, Disability and Event Information'];                   
                if(lstSurveyDisability.size()>0){                        
                    labelSurveyDisability = 'Survey, Disability and Event Information' +' '+'['+String.valueof(lstSurveyDisability.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstSurveyDisability = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Survey, Disability and Event Information'];
                if(lstSurveyDisability.size()>0){                        
                    labelSurveyDisability = 'Survey, Disability and Event Information' +' '+'['+String.valueof(lstSurveyDisability.size()) +']';
                }
            }           
         }
         
         if(sObjectType != null){            
            if(sObjectType == 'Contact') {                
                lstVolunteer = [Select c.start_date__c, c.end_date__c, c.comments__c,c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId  and c.Contact__c!=null and RecordType.Name =: 'Volunteer Preferences'];                   
                if(lstVolunteer.size()>0){                        
                    labelVolunteer = 'Volunteer Preferences' +' '+'['+String.valueof(lstVolunteer.size()) +']';
                }
            }
            else if(sObjectType == 'Account') {                
                lstVolunteer = [Select c.start_date__c, c.end_date__c, c.comments__c, c.Preference__c,c.Preference_Value__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId and c.Account__c!=null and RecordType.Name =: 'Volunteer Preferences'];
                if(lstVolunteer.size()>0){                        
                    labelVolunteer = 'Volunteer Preferences' +' '+'['+String.valueof(lstVolunteer.size()) +']';
                }
            }           
         }
          
               
        return classifications;
    }
        
    public PageReference Delmet() {
        System.debug('Deleteing classification: '+Delid);
        try {
            Classification__c c= [SELECT Id from Classification__c where id=:DelId];
            delete c;
        }
        catch(Exception e) {
            System.debug('Unable to delete classification: '+Delid+', ex: '+e);
        }
        pagereference pg = ApexPages.currentPage();
        return pg;
    }
    
    public static testmethod void test(){
        Contact c = new Contact();
        c.Lastname='test';
        insert c;
                       
        Account a = new Account();
        a.Name='test123';
        insert a;
        Classification__c ccBenefit = new Classification__c(Account__c = a.Id);
        insert ccBenefit;
        
        
        
        List<Classification__c> bb = [Select id from Classification__c limit 1];
        
        //Apexpages.CurrentPage().getParameters().put('id', c.id);
        TabsClassificationsControllerNew tcc = new TabsClassificationsControllerNew();
        
        tcc.sobjectType='Contact';
        Classification__c[] cc= tcc.getClassifications();
        
        if(Cc!=null){
            try{
                tcc.delid=cc[0].id;
                
                tcc.delmet();
            }catch(Exception e){}
                
        }       
        
        tcc.sobjectType='Account';
        tcc.RecordType = 'Appeal Preferences';        
        Classification__c[] acc= tcc.getClassifications();        
        
        tcc.recordid=a.id;
        tcc.RecordType = 'Benefit Preferences';     
        acc= tcc.getClassifications();  
        
        tcc.RecordType = 'Communication Preferences';     
        acc= tcc.getClassifications();
        
        tcc.RecordType = 'Data Tagging & Scores';     
        acc= tcc.getClassifications();
                       
        tcc.sobjectType='Account';
        Classification__c[] hcc= tcc.getClassifications();
        
        tcc.sobjectType='Contact';
        tcc.RecordType = 'Appeal Preferences';
        hcc= tcc.getClassifications();
        
        List<Classification__c> lc =tcc.classifications; 
        
        tcc.classifications = lc;        
        //tcc.getClassifications('Appeal');

        //List<Classification__c> b = new List<Classification__c>([SELECT id from Classification__c limit 1]); 
        //tcc.delId = b[0].id;
        PageReference p=tcc.delmet();
    }
 
}