Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>TA Account Type</description>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Association/Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney/Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Childcare/Preschool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial TV Station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Local Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate National Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation acting as an Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation- Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation- Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual as a Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual as a Personal Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-size Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary School</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Create_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <inlineHelpText>Date new address was created or date they moved to this new address</inlineHelpText>
        <label>Address Create Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Address_Status__c</fullName>
        <inlineHelpText>Select where the address is active or inactive, add the end date if they have moved or it becomes inactive.  If the address is undeliverable do not pull for mailings, exclude this value.</inlineHelpText>
        <label>Address Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undeliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing &amp; Shipping Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreferredAddress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seasonal_Start_Date__c</fullName>
        <inlineHelpText>MMDD Format</inlineHelpText>
        <label>Seasonal Address Start Date</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <inlineHelpText>This would be additional mailing information for delivery for ex. C/O or 3rd floor Suite 107</inlineHelpText>
        <label>Address Additional Line</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Country__c.object
<CustomObject>
    <description>Country objects</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/testPopulateseasonalAddress.cls
@istest
Private class testPopulateseasonalAddress {

    static testMethod void testPopulateseasonalAddress() {


        Date MyDate = System.today();
        integer month = MyDate.Month();
        integer day = MyDate.Day();    
        String StartMonth = String.ValueOf(month);
        String StartDate = String.ValueOf(day);
        String FinalDate = StartMonth+'/'+StartDate;
        
        Account a= new Account(name='test',AccountType__c='Household');
        insert a;
        List<Address__c> lstadd= new List<Address__c>();
        Address__c temp =new Address__c();
        
       
        temp.name='testname';
        temp.PreferredAddress__c=True;
        temp.Account_Household__c=a.id;
        temp.Address_Type__c='Seasonal';
        temp.Seasonal_Start_Date__c = FinalDate;
  
        temp.City__c='temp city';
        temp.State__c='temp state';
        temp.Street_1__c='temp street1';
        temp.Street_2__c='temp street2';
        temp.Postal_Code__c='02772';
        temp.Address_Create_Date__c=MyDate ;
        temp.Address_Status__c='Active';
        temp.Country__c='IND';
        insert temp;
        lstadd.add(temp);
        PopulateseasonalAddress p= new PopulateseasonalAddress();
        PopulateseasonalAddress p1= new PopulateseasonalAddress(lstadd);
    }
}