Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Current Status of the Contact.</description>
        <inlineHelpText>Current Status of the Contact.</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <inlineHelpText>See Contact Status with real values that are mapped from these TA values</inlineHelpText>
        <label>TA Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecUpdateContactStatusCall.cls
global class BatchExecUpdateContactStatusCall {
    Public static void BatchExecUpdateContactStatusCall () {
        ID batchprocessid;
        BatchExecUpdateContactStatus status;
        
        String query = 'Select ID,STS__c,Contact_Status__c from Contact where TaContactId__c != null && TaContactId__c != \'\'';
        if(Test.isRunningTest()) query += ' Limit 100';
        
        status = new BatchExecUpdateContactStatus(query);
        batchprocessid = Database.executeBatch(status,200);
    }
    
    static testMethod void TestBatchExecUpdateContactStatusCall() {
        Test.startTest();
        Account acc = new Account(Name = 'Test Account');
        Contact ct =  new Contact (LastName = 'Test Contact',AccountId =acc.Id,Contact_Status__c = 'Active',STS__c = 'A');
        Contact ct1 =  new Contact (LastName = 'Test Contact1',AccountId =acc.Id,Contact_Status__c = 'Active',STS__c = 'A');
                  
        //BatchExecUpdateContactStatus  beUpdateS = new BatchExecUpdateContactStatus ();
        BatchExecUpdateContactStatusCall.BatchExecUpdateContactStatusCall(); 
        Test.StopTest();    
        
    } 
    
    
}