Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade Sustainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Sustainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Pledge Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade/Reset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade Giving Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade Sustainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade to Major Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade to Mid-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>This campaign name is used for the Campaign Program Reporting Tool and is not to be confused with the Campaign Name used for the out of the box Salesforce text campaign name.</inlineHelpText>
        <label>Campaign Value</label>
        <picklist>
            <controllingField>Product_Program__c</controllingField>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <controllingField>Campaign_Group__c</controllingField>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Join</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kids Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed/Rejoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tickets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>The radio/tv station call letters that the campaign is representing.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Owner_Name__c</fullName>
        <label>Bank Account Owner Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <label>Card Holder Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Charge Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WGBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classical Radio Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gift_kind__c</fullName>
        <label>Gift Kind</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustaining Gift</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations</description>
        <label>Annual</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Giving__r.AccountId , Giving__r.Account.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Alias__c</fullName>
        <label>CC Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Giving__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Refund #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <recordTypes>
        <fullName>Refund_by_Charge_Card</fullName>
        <active>true</active>
        <label>Refund by Charge Card</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/RefundIDSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>FieldAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RendaredValue__c</fullName>
        <label>RendaredValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RefundIDSetting</label>
</CustomObject>

Git_WGBH_QC/src/classes/RefundNewOverride.cls
public class RefundNewOverride{

    String GivingRenderId;
    String CCRenderId;
    String AmountRenderId;
    String RefundPrefix;
    public RefundNewOverride(ApexPages.StandardController controller) {
        List<RefundIDSetting__c> lstRendIDs = new List<RefundIDSetting__c>([Select name,FieldAPIName__c,RendaredValue__c From RefundIDSetting__c]);
        if(lstRendIDs != null && lstRendIDs.size() > 0){
            for(RefundIDSetting__c RID: lstRendIDs){
                if(RID.FieldAPIName__c == 'Giving__c') GivingRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'CC_Alias__c') CCRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'Refund_Amount__c') AmountRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'RefundPrefix') RefundPrefix = RID.RendaredValue__c;            
            }        
        }
    }
    List<Opportunity> getGiving(String oppId){
        List<Opportunity> lstOpp =
        [Select Payment_Amount__c, CC_EFT_Alias__c, CC_EFT_Alias__r.name from Opportunity
        Where Id=:oppId];
        
        return lstOpp;
    }
    public PageReference RedirectToStandardPage() {
        string retURL = ApexPages.CurrentPage().getParameters().get('retURL');
        string GivingId = ApexPages.CurrentPage().getParameters().get(GivingRenderId + '_lkid');
        string GivingName = ApexPages.CurrentPage().getParameters().get(GivingRenderId);
        string RecordType = ApexPages.CurrentPage().getParameters().get('RecordType');
        string ent = ApexPages.CurrentPage().getParameters().get('ent');
        List<Opportunity> lstGiving = getGiving(GivingId);
        string url = '';
        url = '/' + RefundPrefix + '/e';
        url += '?' + GivingRenderId + '=' + EncodingUtil.urlEncode(GivingName, 'UTF-8');
        url += '&' + GivingRenderId + '_lkid=' + EncodingUtil.urlEncode(GivingId, 'UTF-8');
        if(lstGiving != null && lstGiving.size()>0){
            if(lstGiving[0].Payment_Amount__c != null){
                url += '&' + AmountRenderId + '=' + lstGiving[0].Payment_Amount__c;
            }
            if(lstGiving[0].CC_EFT_Alias__c != null){
                url += '&' + CCRenderId + '_lkid=' + EncodingUtil.urlEncode(lstGiving[0].CC_EFT_Alias__c, 'UTF-8');
                url += '&' + CCRenderId + '=' + EncodingUtil.urlEncode(lstGiving[0].CC_EFT_Alias__r.name, 'UTF-8');
            }
        }
        url += '&retURL=' + retURL;
        url += '&RecordType=' + RecordType;
        url += '&ent=' + ent;        
        url += '&nooverride=1';
        
        PageReference redirect = new PageReference(url);
        redirect.SetRedirect(true);        
        return redirect;
    }
    Static TestMethod void TestRefundNewOverride(){
        Account a = new Account(Name = 'Test');
        insert a;
        
        Campaign c = new Campaign(Name = 'Test');
        c.Station__c = 'WGBH';
        c.Campaign_Name__c = 'Annual';
        Insert c;
        
        List<RecordType> lstGivingRecordType = [Select Id from RecordType Where DeveloperName = 'Annual'];
        
        CC_Alias__c cc = new CC_Alias__c();
        cc.Account__c = a.Id;
        cc.Amount__c = 500;
        cc.Bank_Account_Owner_Name__c = 'test';
        cc.Bank_Name__c = 'test';
        cc.Card_Holder_Name__c = 'test';
        cc.Card_Type__c = 'Mastercard';
        insert cc;
        
        Opportunity opp = New Opportunity();
        opp.AccountID = a.Id;
        opp.Name = 'Test';
        opp.Gift_Kind__c = 'One Payment';
        opp.Gift_Type__c = 'New';
        opp.Giving_Amount__c = 500;
        opp.Payment_Amount__c = 500;
        opp.CloseDate = system.Today().AddDays(15);
        opp.StageName = 'Pledged';
        opp.CampaignID = c.Id;
        opp.CC_EFT_Alias__c = cc.Id;
        if(lstGivingRecordType != null && lstGivingRecordType.size()>0){
            opp.RecordTypeId = lstGivingRecordType[0].Id;
        }
        insert opp; 
        /////////////
        String testGivingRenderId = '';
        String testCCRenderId = '';
        String testAmountRenderId = '';
        String testRefundPrefix = '';
        List<RefundIDSetting__c> lstTest = new List<RefundIDSetting__c>([Select name,FieldAPIName__c,RendaredValue__c From RefundIDSetting__c]);
        if(lstTest != null && lstTest.size() > 0){
            for(RefundIDSetting__c RID: lstTest){
                if(RID.FieldAPIName__c == 'Giving__c') testGivingRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'CC_Alias__c') testCCRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'Refund_Amount__c') testAmountRenderId = RID.RendaredValue__c;
                else if(RID.FieldAPIName__c == 'RefundPrefix') testRefundPrefix = RID.RendaredValue__c;            
            }        
        }        
        /////////////
        Refund__c r = new Refund__c();
        List<RecordType> RefundRecordType = [Select DeveloperName from RecordType where DeveloperName='Refund_by_Charge_Card'];
        if(RefundRecordType != null && RefundRecordType.size()>0){
            ApexPages.CurrentPage().getParameters().put('RecordType',RefundRecordType[0].Id);
        }
        ApexPages.CurrentPage().getParameters().put('retURL','/' + opp.Id);
        if(testGivingRenderId != ''){
            ApexPages.CurrentPage().getParameters().put(testGivingRenderId + '_lkid', opp.Id);
            ApexPages.CurrentPage().getParameters().put(testGivingRenderId, opp.Name);
        }
        ApexPages.StandardController controller = new ApexPages.StandardController(r);
        RefundNewOverride clsTest = new RefundNewOverride(controller);
        clsTest.RedirectToStandardPage();
    }   
}