Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Major Gift Account Manager who deals with this organization.</description>
        <inlineHelpText>Major Gift Account Manager who deals with this organization.</inlineHelpText>
        <label>Major Gift Acct Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Bios__c.object
<CustomObject>
    <description>Object utilized for listing the various ways in which a Contact is related to the Organization and/or personal highlights that are important for profiling a person.  This object will has multiple record types and field dependencies to represent the different types of records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(School__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>school_code__c</fullName>
        <description>School Name</description>
        <inlineHelpText>Name of school, university, college, community college, continuing education</inlineHelpText>
        <label>School Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bio</label>
    <nameField>
        <displayFormat>Bio-{00000000}</displayFormat>
        <label>Bio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bios</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s Personal Profile.</description>
        <label>Education</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Account Manager who are responsible for contact and household relationships for Annual Giving/Foundations/Planned Giving/Underwriting/Trustee &amp; Overseer Relations/Events/Development</description>
        <inlineHelpText>Account Manager who are responsible for contact and household relationships for Annual Giving/Foundations/Planned Giving/Underwriting/Trustee &amp; Overseer Relations/Events/Development</inlineHelpText>
        <label>Account Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Davi Axinn Levine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abby Ballou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jessica Connolly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kaja Fickes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ellen Frank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kathleen McCarthy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeanmarie Roberts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Susanne Salerno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanya Tulenko</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Win Lenihan</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Acccount Manager and/or Business Member Partner users who deal with an organization</description>
        <inlineHelpText>Add the users from WGBH who deal with this organization or have an ongoing relationship</inlineHelpText>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Households</relationshipLabel>
        <relationshipName>Households</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Prospect_Research_Reports__c.object
<CustomObject>
    <description>Prospect Research Reports are utilized for profiling of members, prospective members and constituents by the Prospect Research Team.</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Prospect_Research_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Born_Day__c</fullName>
        <formula>Contact__r.Birth_Day__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Born Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Born_Month__c</fullName>
        <formula>Contact__r.Birth_Month__c</formula>
        <label>Born Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Born_Year__c</fullName>
        <formula>Contact__r.Birth_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Born Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Affiliations__c</fullName>
        <label>Business Affiliations</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CPRT__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account__r.Preferred_Address__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Family_Foundation__c</fullName>
        <label>Family Foundation</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Financial_Information__c</fullName>
        <label>Financial Information</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Interests__c</fullName>
        <label>Interests</label>
        <picklist>
            <picklistValues>
                <fullName>Hunting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fishing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>MG_Rating__c</fullName>
        <label>MG Rating</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Most_recent_College__c</fullName>
        <label>Most recent College</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Philanthropic_Activities__c</fullName>
        <label>Charitable Giving</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Personal_Summary__c</fullName>
        <label>Bio Summary</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Recent_College__c</fullName>
        <formula>Most_recent_College__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recent College</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recent_Company__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recent Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spouse_Name_Formula__c</fullName>
        <formula>IF(Spouse_Name__c != null, HYPERLINK(&quot;/&quot;+Spouse_Name__c,Spouse_Name__r.FirstName +&apos; &apos;+ Spouse_Name__r.LastName,&quot; _self&quot;),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spouse Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spouse_Name__c</fullName>
        <label>Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports (Spouse Name)</relationshipLabel>
        <relationshipName>Prospect_Research_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account__r.Preferred_Address__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGBH_Connections__c</fullName>
        <label>WGBH Connections</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <label>Prospect Research Report</label>
    <nameField>
        <label>PRR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Research Reports</pluralLabel>
    <recordTypes>
        <fullName>Event_Bio</fullName>
        <active>true</active>
        <description>PRR for Cultivation Events (i.e. 1 paragraph with a picture)</description>
        <label>Event Bio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Profile</fullName>
        <active>true</active>
        <description>Detailed PRR for major gift/board prospects (i.e. 1-3 pages)</description>
        <label>Profile</label>
    </recordTypes>
    <recordTypes>
        <fullName>Research_Note</fullName>
        <active>true</active>
        <description>PRR for brief notes on new information on a prospect (i.e. an obituary, news articles, etc.)</description>
        <label>Research Note</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/ProspectResearchIDSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>FieldAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RendaredValue__c</fullName>
        <label>RendaredValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ProspectResearchIDSetting</label>
</CustomObject>

Git_WGBH_QC/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>People__c</fullName>
        <label>People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_AccHousehold__c</fullName>
        <label>Related To Account for the Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To Household)</relationshipLabel>
        <relationshipName>Relationships3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_People__c</fullName>
        <label>Related To People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related To People)</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/NewProspectResearchReports.cls
Public Class NewProspectResearchReports{
    public String testURL{get;set;}
    String strRecordType='';
    String strObject='';
    
    Public String AccountRendId = '';
    Public String ContactRendId = '';
    Public String CollegeRendId = '';
    Public String SpouseRendId = '';
    Public String PRR_Prefix = '';
    
    public NewProspectResearchReports(ApexPages.StandardController controller){
        List<ProspectResearchIDSetting__c> lstRendIDs = new List<ProspectResearchIDSetting__c>([Select name,FieldAPIName__c,RendaredValue__c From ProspectResearchIDSetting__c]);
        for(ProspectResearchIDSetting__c RID: lstRendIDs){
            if(RID.FieldAPIName__c == 'Account__c') AccountRendId = RID.RendaredValue__c;
            else if(RID.FieldAPIName__c == 'Contact__c') ContactRendId = RID.RendaredValue__c;
            else if(RID.FieldAPIName__c == 'Most_recent_College__c') CollegeRendId = RID.RendaredValue__c;
            else if(RID.FieldAPIName__c == 'Spouse_Name__c') SpouseRendId = RID.RendaredValue__c;
            else if(RID.FieldAPIName__c == 'PRR Prefix') PRR_Prefix = RID.RendaredValue__c;
            
        }
    }    
    public string getCurrentURL() {
        PageReference currPage = ApexPages.currentPage();
        String currPageURL = currPage.getUrl();
        return currPageURL;
    }
    public String getSchoolName(String strID){
        String autoData='';
        List<Bios__c> lstBio = new List<Bios__c>();
        try{
            List<RecordType> lstRc = [select id from RecordType where developername =: 'Master'];
            lstBio = [SELECT Id, school_code__c FROM Bios__c WHERE Related_To__c =: strID AND RecordType.Id =: lstRc[0].Id order by createddate desc limit 1];        
            if(lstBio != null && lstBio.size()>0){
               autoData = '&'+ CollegeRendId + '=' + lstBio[0].school_code__c;
            }
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));
        }
        return autoData;
    }
    
    public String getSpouse(String strId){
        //if(strRecordType != 'Event_Bio') return '';
        if(strRecordType == 'Research_Note') return '';
        List<Relationships__c> lstRel = new List<Relationships__c>();
        string strSpouse='';
        if(strObject == 'Contact'){
         //Related_To_People__c, People__c
            lstRel = [Select id, name from Relationships__c Where Related_To_People__c =: strId OR People__c =: strId order by createddate desc limit 1];             
        }
        else if(strObject == 'Account'){
         //Related_To_Account, Account
            lstRel = [Select id, name from Relationships__c Where Related_To_AccHousehold__c =: strId OR Account_Household__c =: strId order by createddate desc limit 1];                      
        }
        if(lstRel != null && lstRel.size()>0){
            strSpouse = '&CF' + SpouseRendId + '=' + lstRel[0].name;
        }
        return strSpouse;
    }    
    
    Public String AutoPopulateData(String strId){
        String autoData='';
        List<Bios__c> lstBio = new List<Bios__c>();
        strId = strId.replace('/' , '');
        strId = strId.replace('%2F' , '');
        String HouseHoldName='';
        DateTime HouseHoldDate=null;
        //strObject = CommonApex.getObjectNameById(strID);
        if(strId.trim().substring(0,3)=='003')
            strObject = 'Contact';
        else if(strId.trim().substring(0,3)=='001')
            strObject = 'Account';
        system.debug('#######strobject : ' + strObject);
        if(strObject == 'Contact'){
            //Getting most recent collage name
            if(strRecordType=='Event_Bio' || strRecordType=='Profile')
                //autoData += getSchoolName(strId);
            //Contact
            try{
                List<Contact> lstContact = [SELECT firstname, lastname, AccountID, Account_Household__r.name, Account_Household__r.createddate FROM Contact WHERE Id =: strId];
                if(lstContact != null && lstContact.size()>0){
                    autoData += '&CF' + ContactRendId + '_lkid=' + strID;    
                    autoData += '&CF' + ContactRendId +'=' + lstContact[0].firstname + '+' + lstContact[0].lastname;
                    
                    //system.debug('Household name--------------------->' + lstContact[0].Household__r.name);
                    system.debug('Household id--------------------->' + lstContact[0].Account);
                    //Household name
                    if(lstContact[0].Account != null){
                        autoData += '&CF' + AccountRendId +'_lkid=' + lstContact[0].AccountID;    
                        autoData += '&CF' + AccountRendId +'=' + lstContact[0].Account_Household__r.name;
                        //autoData += '&Name=' + getPRRName(lstContact[0].Household__r.name, lstContact[0].Household__r.createddate);
                        HouseHoldName = lstContact[0].Account_Household__r.name;
                        HouseHoldDate = lstContact[0].Account_Household__r.createddate;
                    }
                }
            }catch(Exception ex1){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex1.getMessage()));
            }
        } 
        system.debug('############## AccountId : ' + strId);
        if(strObject == 'Account'){
            List<Account> lstHO = [SELECT id, name, createddate FROM Account WHERE Id =: strId];
            if(lstHO != null && lstHO.size()>0){
                autoData += '&CF' + AccountRendId +'_lkid=' + lstHO[0].id;    
                autoData += '&CF'+ AccountRendId +'=' + lstHO[0].name;
                HouseHoldName = lstHO[0].name;
                HouseHoldDate = lstHO[0].createddate;
            }
        }
        autoData += '&Name=' + getPRRName(HouseHoldName, HouseHoldDate);
        //System.debug('COLLAGE------------------------>' + collegeName);
        //autoData += getSpouse(strId);
        return autoData;
    }


    String getPRRName(String HouseHoldName, DateTime dtCreated){
        String PRRName = HouseHoldName;
        String dt;
        if(dt != null && dt.trim().length()>0){
            dt = String.valueOf(date.valueOf(String.valueOf(dtCreated)));
        }
        else{
            dt = String.valueOf(System.today());
        }
        dt = dt.replace('00:00:00','').trim().replace('-','/');
        
        PRRName += ' ' + dt;
        
        system.debug('PRR NAME--------------------->' + PRRName);
        return PRRName.trim();
    }
    public PageReference RedirectToStandardPage() {
        string URL1='';
        
                
        //AccountRendId ='00NF0000008NcKf';
        string retURL1 = ApexPages.CurrentPage().getParameters().get('retURL');        
        String currPageURL =  ApexPages.currentPage().getUrl();
        string Accountid = ApexPages.CurrentPage().getParameters().get('CF'+ AccountRendId +'_lkid');
        string RecordType1 = ApexPages.CurrentPage().getParameters().get('RecordType');
        //Boolean recordfound = false;
        ID PRRId; //= 'a17Q0000000rK4V';
        String AccName='';
        DateTime AccCreated = System.now();
        If(Accountid != null && Recordtype1 != null) {
            list<Prospect_Research_Reports__c> lstPRR = new List<Prospect_Research_Reports__c>([
            Select Id,Name,Account__c, Account_Manager__c,Author__c,Born_Day__c,Born_Month__c,Born_Year__c,Business_Affiliations__c,City__c,CPRT__c,
                    Education__c,Family_Foundation__c,Financial_Information__c,Interests__c,MG_Rating__c,Most_recent_College__c,Notes__c,Other_Philanthropic_Activities__c,
                    Personal_Summary__c,Contact__c,Recent_College__c,Recent_Company__c,Spouse_Name__c,Spouse_Name_Formula__c,State__c,WGBH_Connections__c 
                    FROM Prospect_Research_Reports__c  WHERE Account__c =:Accountid AND RecordTypeID =:Recordtype1 order by CreatedDate Desc limit 1]);
            if(lstPRR.Size() >0) PRRId = lstPRR[0].Id;
             
        }
        List<Account> lstHO = [SELECT id, name, createddate FROM Account WHERE Id =: Accountid ];
        If(lstHO.size()>0) {
            AccName = lstHO[0].name;
            AccCreated = lstHO[0].createddate;
        }
        If(PRRId != null){
            //PRRId = System.Label.PospectDefaultID;//'a17Q0000000rK4V';
            URL1 = '/'+PRRId +'/e?clone=1';
            //URL1 += '&Name=' + getPRRName(AccName, AccCreated ); 
            URL1 += '&CF' + AccountRendId + '=' +EncodingUtil.urlEncode(AccName, 'UTF-8');
            URL1 += '&CF' + AccountRendId + '_lkid=' +Accountid;
            URL1 += '&nooverride=1&RecordType=' +Recordtype1;
            URL1 += '&retURL=%2F' +Accountid;                       
        }
        else{
            String FinalURL = currPageURL;
            if (FinalURL!=null) {
                FinalURL = FinalURL.Replace('/apex/NewProspectResearchReports','');
                FinalURL = FinalURL.Replace('&save_new=1&scontrolCaching=1&sfdc.override=1','');
                FinalURL = FinalURL.Replace('&save_new=1&sfdc.override=1','');
                FinalURL = '/' + PRR_Prefix + '/e' + FinalURL + '&nooverride=1';
    
                URL1 = FinalURL;
            }
        }


        system.debug('###0#:' + URL1);
        system.debug('###1#:' + retURL1);
        system.debug('###2#:' + currPageURL);
        
        PageReference PRClone = new PageReference(URL1);
        PRClone.SetRedirect(true);        
        return PRClone;  
    }
   /* public PageReference RedirectToStandardPage() {
        string URL='';
        string retURL = ApexPages.CurrentPage().getParameters().get('retURL');
        string RecordType = ApexPages.CurrentPage().getParameters().get('RecordType');
        string ent = ApexPages.CurrentPage().getParameters().get('ent');
        string save_new= ApexPages.CurrentPage().getParameters().get('save_new');
        RecordType r = [Select DeveloperName from RecordType where ID=:RecordType];
        strRecordType = r.DeveloperName;
        Schema.DescribeSObjectResult resultkeyPrefix = Prospect_Research_Reports__c.sObjectType.getDescribe();
        URL += '/'+resultkeyPrefix.getKeyPrefix()+'/e?retURL=' + retURL + '&RecordType=' + RecordType + '&ent=' + ent;
        //if(r.DeveloperName == 'Event_Bio'){
            URL += '&CF00NQ0000000mKs9=' + UserInfo.getName();  
            URL += AutoPopulateData(retURL.replace('%2F',''));
        //}
        URL += '&nooverride=1';        
        system.debug('URL----------------------->' + URL);
        PageReference P = new PageReference(URL);
        P.SetRedirect(true);  
        return P;
        //return null;
    }*/
    
     Static TestMethod void TestNewProspectResearchReports() {
        Recordtype record = [select id  from recordtype where DeveloperName='Household' And SobjectType='Account' limit 1];
        Account a = new Account(Name = 'Test123');
        a.Recordtypeid=record.id;
        insert a;
        
        Contact cnt = new Contact();
        cnt.firstName = 'Test';
        cnt.lastName = 'test';
        cnt.AccountID = a.Id;
        insert cnt;   

        Prospect_Research_Reports__c p = new Prospect_Research_Reports__c();
        RecordType r = [Select DeveloperName from RecordType where DeveloperName='Event_Bio'];
        
        ApexPages.CurrentPage().getParameters().put('RecordType',r.Id);
        ApexPages.CurrentPage().getParameters().put('retURL','/' + a.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(p);
        NewProspectResearchReports clsTest = new NewProspectResearchReports(controller);
        clsTest.getCurrentURL();
        clsTest.AutoPopulateData(a.id);
        clsTest.AutoPopulateData(cnt.id);
        clsTest.RedirectToStandardPage();
        clsTest.getSchoolName(cnt.id);
        clstest.getSpouse(cnt.id);
        clsTest.getSpouse(a.id);
    }   
}