Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>If the case is in reference to a program, search and select the applicable program.  One program may be selected per case.</inlineHelpText>
        <label>TV/Radio Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>Specific station in which the case is in reference to. WGBH should be selected for non station-specific requests.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WGBH</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH News Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH Classical Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>contact_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Contact Date</description>
        <inlineHelpText>Date case is opened, date of first contact.</inlineHelpText>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ta_interactions_Id__c</fullName>
        <description>TA Interactions external Id</description>
        <externalId>true</externalId>
        <label>TA Interactions Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Program__c.object
<CustomObject>
    <description>These are the programs that are showing on TV or playing on the radio.</description>
    <fields>
        <fullName>Series__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates whether the Show is a Series.</description>
        <label>Series</label>
        <type>Checkbox</type>
    </fields>
    <label>Program/Show</label>
    <nameField>
        <label>Program Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TesttrgCaseAfterInsert.cls
@isTest
private class TesttrgCaseAfterInsert{
    static testMethod void myTest() {
         Account h = new Account();
            h.Name = 'Mr. & Mrs. Joe Dirt';
            h.TaAccountId__c = 23456; 
        insert h;     

        Contact c = new Contact();
            c.FirstName = 'Joe';
            c.LastName = 'Dirt'; 
            c.TaContactId__c = '23456_01_I';
            c.Account_Household__c = h.id;
        insert c;
        
        Program__c prg = new Program__c();
            prg.name = 'test show';
            prg.Series__c = true;
        insert prg;       
       
        Case case1 = new Case();  
            case1.program__c = prg.Id;    
            case1.ta_interactions_Id__c = '23456_01_I_SO_BAR';
            case1.Origin='Email';
            case1.Station__c='WGBH';
            case1.Type='Jazz';
            case1.Status='Open';
            case1.ContactId = c.id;
            case1.AccountID = h.Id;
            case1.contact_date__c=System.today();
        insert case1;
    }
}