Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Proposal</relationshipLabel>
        <relationshipName>Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Balance__c</fullName>
        <formula>Giving_Amount__c - payment_amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Pledges &amp; Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gift_date__c</fullName>
        <description>Gift Date</description>
        <inlineHelpText>Gift Date</inlineHelpText>
        <label>Gift Date OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>new_installment_amount__c</fullName>
        <label>Installment Amt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>paid_amount__c</fullName>
        <description>Paid Amount</description>
        <inlineHelpText>Paid Amount</inlineHelpText>
        <label>Paid Amt $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_number__c</fullName>
        <label>Installment Number</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations and Pledges</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipName>Recurring_Donations_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Balance__c</fullName>
        <formula>pledge_amount__c -  paid_amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RecurringDonations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gift_date__c</fullName>
        <description>Gift Date</description>
        <inlineHelpText>Gift Date</inlineHelpText>
        <label>Gift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>paid_amount__c</fullName>
        <description>Paid Amount</description>
        <inlineHelpText>Paid Amount</inlineHelpText>
        <label>Paid Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <label>Recurring Pledge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TaPayment__c.object
<CustomObject>
    <description>Temporary Payment Object for closing Opportunities that were migrated from TA</description>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gift_date__c</fullName>
        <description>Gift Date</description>
        <inlineHelpText>Gift Date</inlineHelpText>
        <label>Gift Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>paid_amount__c</fullName>
        <description>Paid Amount</description>
        <inlineHelpText>Paid Amount</inlineHelpText>
        <label>Paid Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>TaPayment Temporary</label>
    <nameField>
        <label>Temp Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaPayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchOppPaymentProcessor.cls
global class BatchOppPaymentProcessor implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;
    
    global static final Integer TOLERANT_ROUND_AMOUNT = 1;

    global BatchOppPaymentProcessor(){
    	// original - Where r.TaTransactions_Id__c != null and New_Balance__c >= 0';
        this.query = 'Select r.TaTransactions_Id__c, batch_process_count__c, New_Balance__c, ' + 
                        '(Select TaTransactions_Id__c, gift_date__c, payment_amount__c From Payments__r order by gift_date__c), ' +  
                        '(Select Name, StageName, Amount, CloseDate, TaTransactions_Id__c, new_installment_amount__c, payment_number__c From Donations__r order by payment_number__c) ' +  
                     'From Recurring_Donation__c r WHERE batch_process_count__c = 2';
    }
    
    global BatchOppPaymentProcessor(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Recurring_Donation__c rd = (Recurring_Donation__c) s;
            //Batch condition.
            if(rd.TaTransactions_Id__c != null && rd.New_Balance__c >= 0) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	rd.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }        
    
    global void execute(List<sObject> scope){
    	List<Opportunity> opps = new List<Opportunity>();
		Orphan__c[] orphans = new List<Orphan__c>();      	
        for(Sobject s : scope){
            Recurring_Donation__c rd = (Recurring_Donation__c) s;
            try {
	            List<Opportunity> opportunities = rd.Donations__r;
	            List<TaPayment__c> payments = rd.Payments__r;
	            
	            if(opportunities != null && opportunities.size() > 0 && payments != null && payments.size() > 0) {
	            	for(Opportunity opp : opportunities) {
	                    opp.Amount = opp.new_installment_amount__c;
	                }
	            	processPayments(opportunities, 0, payments, 0);
	            	partialCloseOpps(opportunities);
	            }
	            opps.addAll(opportunities);
            	rd.batch_process_count__c--;
            }
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Recurring_Donation__c',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchOppPaymentProcessor',
        			ta_id__c=rd.TaTransactions_Id__c,
        			object_id__c=s.id)
        		);
        	}            
        }
        update opps;
		if(orphans.size()>0) insert orphans;          
    }
    
    global void processPayments(List<Opportunity> opportunities, Integer oppIndex, List<TaPayment__c> payments, Integer paymentIndex) {
    	if(oppIndex < opportunities.size() && paymentIndex < payments.size()) {
	    	Opportunity currentOpportunity = opportunities[oppIndex];
	    	TaPayment__c currentPayment = payments[paymentIndex];
	    	
	    	Decimal balance = currentPayment.payment_amount__c - currentOpportunity.Amount;
	    	if(Math.abs(balance) < BatchOppPaymentProcessor.TOLERANT_ROUND_AMOUNT) {
	    		currentPayment.payment_amount__c = currentOpportunity.Amount;
	    		balance = currentPayment.payment_amount__c - currentOpportunity.Amount;
	    	}
	    	System.debug('o: '+oppIndex+', p: '+paymentIndex+', balance: '+balance+', opp amt: '+currentOpportunity.Amount+', payment amt: '+currentPayment.payment_amount__c);
	    	
	    	if(balance == 0) {
	    		closeOpportunity(currentOpportunity, currentPayment.gift_date__c, currentOpportunity.new_installment_amount__c);
	    		processPayments(opportunities, oppIndex + 1, payments, paymentIndex + 1);
	    	}
	    	else if(balance > 0) {
	    		if(oppIndex == opportunities.size() - 1) {
     	    		closeOpportunity(currentOpportunity, currentPayment.gift_date__c, currentPayment.payment_amount__c);
	    		}
	    		else {
	    			currentPayment.payment_amount__c -= currentOpportunity.Amount;
     	    		closeOpportunity(currentOpportunity, currentPayment.gift_date__c, currentOpportunity.new_installment_amount__c);
     	    		processPayments(opportunities, oppIndex + 1, payments, paymentIndex);
	    		}
	        }
	    	else if(balance < 0) {
	    		currentOpportunity.Amount -= currentPayment.payment_amount__c;
	    		processPayments(opportunities, oppIndex, payments, paymentIndex + 1);
	        }
    	}
    }
    
    global void partialCloseOpps(List<Opportunity> opportunities) {
    	if(opportunities != null && opportunities.size() > 0) {
            boolean allClosed = true;
            for(Opportunity opp : opportunities) {
                if(opp.StageName != 'Closed Won') {
                    allClosed = false;
                    break;
                }
            }
            for(Opportunity opp : opportunities) {
                if(opp.StageName == 'Closed Won' && allClosed == false) {
                    opp.StageName = 'Partial Close';
                }
            }
        }
    }
    
    global void closeOpportunity(Opportunity opportunity, Date closeDate, Decimal amount) {
    	System.debug('Closing opp: '+opportunity.name+', opp amt: '+opportunity.Amount+', paid amt: '+amount);
    	opportunity.CloseDate = closeDate;
    	opportunity.StageName = 'Closed Won';
    	opportunity.Amount = amount;
    }
    
    public static testMethod void testBatch() {
        Recurring_Donation__c rd1 = new Recurring_Donation__c(
           TaTransactions_Id__c = '23456_01_I_1230987_03',
           Name = 'Test RD 1',
           gift_date__c = Date.today(),
           paid_amount__c = 100, 
           Amount__c = 200,  
           bulk_load__c = true,
           batch_process_count__c = 1
        );
        insert rd1;
        Opportunity o11 = new Opportunity(
           tatransactions_Id__c = '23456_01_I_1230987_03_01',
           Name = 'Test Opporutnity 1',
           StageName = 'Cultivation',
           CloseDate = Date.today() - 5, 
           gift_date__c = Date.today() - 5, 
           Recurring_Donation__c = rd1.Id, 
           new_installment_amount__c = 100, 
           amount = 100, 
           payment_number__c = 1
        );
        insert o11;
        Opportunity o12 = new Opportunity(
           tatransactions_Id__c = '23456_01_I_1230987_03_02',
           Name = 'Test Opporutnity 2',
           StageName = 'Cultivation',
           CloseDate = Date.today() - 5, 
           gift_date__c = Date.today() - 5, 
           Recurring_Donation__c = rd1.Id, 
           new_installment_amount__c = 100, 
           amount = 100, 
           payment_number__c = 2
        );
        insert o12;
        Opportunity o13 = new Opportunity(
           tatransactions_Id__c = '23456_01_I_1230987_03_03',
           Name = 'Test Opporutnity 3',
           StageName = 'Cultivation',
           CloseDate = Date.today() - 5, 
           gift_date__c = Date.today() - 5, 
           Recurring_Donation__c = rd1.Id, 
           new_installment_amount__c = 100, 
           amount = 100, 
           payment_number__c = 3
        );
        insert o13;
        TaPayment__c p11 = new TaPayment__c(
           TaTransactions_Id__c = '23456_01_I_1230987_03_01',
           Name = 'Test Payment 1',
           gift_date__c = Date.today() - 3, 
           Recurring_Donation__c = rd1.Id, 
           payment_amount__c = 100
        );    
        insert p11;
        TaPayment__c p12 = new TaPayment__c(
           TaTransactions_Id__c = '23456_01_I_1230987_03_02',
           Name = 'Test Payment 2',
           gift_date__c = Date.today() - 2, 
           Recurring_Donation__c = rd1.Id, 
           payment_amount__c = 80
        );    
        insert p12;
        TaPayment__c p13 = new TaPayment__c(
           TaTransactions_Id__c = '23456_01_I_1230987_03_03',
           Name = 'Test Payment 3',
           gift_date__c = Date.today() - 1, 
           Recurring_Donation__c = rd1.Id, 
           payment_amount__c = 800
        );    
        insert p13;
        /*Recurring_Donation__c rd2 = new Recurring_Donation__c(
           TaTransactions_Id__c = '23456_00_I_1234387_03',
           Name = 'Test Household RD',
           gift_date__c = Date.today()         
        );
        insert rd2;      
        Recurring_Donation__c rd3 = new Recurring_Donation__c (
           TaTransactions_Id__c = '23456_00_C_1344987_03',
           Name = 'Test Account RD',
           gift_date__c = Date.today()         
        );                      
        insert rd3;*/
        
        Test.StartTest();
        BatchOppPaymentProcessor batch = new BatchOppPaymentProcessor();
        batch.query += ' AND TaTransactions_Id__c IN (\'23456_01_I_1230987_03\') LIMIT 3 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Opportunity[] to = [SELECT CloseDate, Amount FROM Opportunity WHERE tatransactions_Id__c IN (:o11.tatransactions_Id__c, :o12.tatransactions_Id__c, :o13.tatransactions_Id__c)];
//todo        System.AssertEquals(to[0].CloseDate, Date.today() - 3);
//todo        System.AssertEquals(to[1].CloseDate, Date.today() - 1);
//todo        System.AssertEquals(to[2].CloseDate, Date.today() - 1);
        
//todo        System.AssertEquals(to[0].Amount, 100);
//todo        System.AssertEquals(to[1].Amount, 100);
//todo        System.AssertEquals(to[2].Amount, 780);
        
        //Recurring_Donation__c trd1 = [SELECT Contact__c, Household__c, Organization__c FROM Recurring_Donation__c WHERE TaTransactions_Id__c = :rd1.TaTransactions_Id__c][0];
        //System.AssertEquals(trd1.Contact__c, c.id);
        //Recurring_Donation__c trd2 = [SELECT Contact__c, Household__c, Organization__c FROM Recurring_Donation__c WHERE TaTransactions_Id__c = :rd2.TaTransactions_Id__c][0];
        //System.AssertEquals(trd2.Household__c, h.id);        
        //Recurring_Donation__c trd3 = [SELECT Contact__c, Household__c, Organization__c FROM Recurring_Donation__c WHERE TaTransactions_Id__c = :rd3.tatransactions_Id__c][0];
        //System.AssertEquals(trd3.Organization__c, a.id);                               
    }    

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchOppPaymentProcessor', chainFlag);
    }
}