Git_WGBH_QC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TA_Account_ID__c</fullName>
        <formula>TEXT(TaAccountId__c)</formula>
        <label>Legacy Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaAccountId__c</fullName>
        <description>TA Account Id</description>
        <label>TA Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <inlineHelpText>Each individual contact is associated with a Household which lists information for the whole family.</inlineHelpText>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>If the case is in reference to a program, search and select the applicable program.  One program may be selected per case.</inlineHelpText>
        <label>TV/Radio Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>Specific station in which the case is in reference to. WGBH should be selected for non station-specific requests.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WGBH</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH News Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH Classical Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>contact_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Contact Date</description>
        <inlineHelpText>Date case is opened, date of first contact.</inlineHelpText>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>program_code__c</fullName>
        <description>Program</description>
        <label>Program</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_interactions_Id__c</fullName>
        <description>TA Interactions external Id</description>
        <externalId>true</externalId>
        <label>TA Interactions Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>Ta_Account_Id__c</fullName>
        <label>Ta_Account_Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Program__c.object
<CustomObject>
    <description>These are the programs that are showing on TV or playing on the radio.</description>
    <label>Program/Show</label>
    <nameField>
        <label>Program Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchCaseLink.cls
global class BatchCaseLink implements Database.Batchable<sObject> {
    global String query;
    global Boolean chainFlag = false;

    global BatchCaseLink(){
    	// original - 'WHERE ta_interactions_Id__c != null and ContactId = null and Household__c = null and AccountId = null';
        this.query = 
        	'Select ta_interactions_Id__c, program_code__c, Program__c, Household__c, ContactId, CaseNumber, AccountId, batch_process_count__c ' + 
        	'From Case ' +
        	'Where batch_process_count__c = 2';
    }
    
    global BatchCaseLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Case c = (Case) s;
            //Batch condition.
            if(c.ta_interactions_Id__c != null && c.ContactId == null && c.Household__c == null && c.AccountId == null) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	c.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }    

    global void execute(List<sObject> scope){
    	List<Integer> accountTaIds = new List<Integer>();
        List<Integer> householdTaIds = new List<Integer>();
        List<String> contactTaIds = new List<String>();
        
        // 0     1  2  3  4   5          6  7
        //328858_02_I_SO_BAR_MM-DD-YYYY_01_01
        //328858_02_I_SO_BAR   
		Orphan__c[] orphans = new List<Orphan__c>();               
        for(Sobject s : scope){
            Case cas = (Case) s;
        	try {            
	            String[] sData = cas.ta_interactions_Id__c.split('_');
	            
	            if(sData[2] == 'C' || sData[2] == 'G' || sData[2] == 'F' || sData[2] == 'O') {
	                accountTaIds.add(Integer.valueOf(sData[0]));
	            }
	            if(sData[2] == 'I') {
	                if(sData[1] == '00') {
	                    householdTaIds.add(Integer.valueOf(sData[0]));
	                }
	                else {
	                    contactTaIds.add(sData[0] + '_' + sData[1] + '_' + sData[2]);
	                }
	            }
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Case',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchCaseLink',
        			ta_id__c=cas.ta_interactions_Id__c,
        			object_id__c=s.id)
        		);
        	}	            
        }
        
        List<Account> accounts = [SELECT id, TaAccountId__c FROM Account WHERE TaAccountId__c IN :accountTaIds];
        Map<String, ID> accountsMap = new Map<String, ID>();
        for(Account account : accounts) {
            accountsMap.put(String.valueOf(account.TaAccountId__c), account.Id);
        }
        List<Household__c> households = [SELECT id, Ta_Account_Id__c FROM Household__c WHERE Ta_Account_Id__c IN :householdTaIds];
        Map<String, ID> householdsMap = new Map<String, ID>();
        for(Household__c household : households) {
            householdsMap.put(String.valueOf(household.Ta_Account_Id__c), household.Id);
        }
        List<Contact> contacts = [SELECT id, TaContactId__c FROM Contact WHERE TaContactId__c IN :contactTaIds];
        Map<String, ID> contactsMap = new Map<String, ID>();
        for(Contact contact : contacts) {
            contactsMap.put(contact.TaContactId__c, contact.Id);
        }
        
        for(Sobject s : scope){
            Case cas = (Case) s;
			try {            
	            String[] sData = cas.ta_interactions_Id__c.split('_');
	            
	            if(sData[2] == 'C' || sData[2] == 'G' || sData[2] == 'F' || sData[2] == 'O') {
	                cas.AccountId = accountsMap.get(sData[0]);
	            }
	            if(sData[2] == 'I') {
	                if(sData[1] == '00') {
	                    cas.Household__c = householdsMap.get(sData[0]);
	                }
	                else {
	                    cas.ContactId = contactsMap.get(sData[0] + '_' + sData[1] + '_' + sData[2]);
	                }
	            }
	            cas.batch_process_count__c--;
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Case',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchCaseLink',
        			ta_id__c=cas.ta_interactions_Id__c,
        			object_id__c=s.id)
        		);
        	}		            
        }
        
        update scope;
		if(orphans.size()>0) insert orphans;           
    }
    
    public static testMethod void testBatch() {
    	//this.query += ' LIMIT 1 '; 
    	Contact c = new Contact(
    	   FirstName = 'Joe', 
    	   LastName = 'Dirt', 
    	   TaContactId__c = '23456_01_I',
    	   bulk_load__c=true
    	);
    	insert c;   	
    	Account a = new Account(
    	   Name = 'Joe Dirt and Co', 
    	   TaAccountId__c = 23456,
    	   bulk_load__c=true
    	); 
    	insert a;    	     	
    	Household__c h = new Household__c(
    	   Name = 'Mr. & Mrs. Joe Dirt', 
    	   Ta_Account_Id__c = 23456,
    	   bulk_load__c=true
    	);  
    	insert h;  	     	   	
    	Case case1 = new Case(
    	   ta_interactions_Id__c = '23456_01_I_SO_BAR',
    	   Origin='Email',
    	   Station__c='WGBH',
    	   Type='Jazz',
    	   Status='Open',
    	   contact_date__c=System.today(),
    	   bulk_load__c=true,
    	   batch_process_count__c=2
    	);   	
    	insert case1; 
    	Case case2 = new Case(
    	   ta_interactions_Id__c = '23456_00_I_SO_BAR',
    	   Origin='Email',
    	   Station__c='WGBH',
    	   Type='Jazz',
    	   Status='Open',
    	   contact_date__c=System.today(),
    	   bulk_load__c=true,
    	   batch_process_count__c=2
    	);   	
    	insert case2;   
    	Case case3 = new Case(
    	   ta_interactions_Id__c = '23456_00_C_SO_BAR',
    	   Origin='Email',
    	   Station__c='WGBH',
    	   Type='Jazz',
    	   Status='Open',
    	   contact_date__c=System.today(),
    	   bulk_load__c=true,
    	   batch_process_count__c=2
    	);   	
    	insert case3;       	    	  	 	
        
        Test.StartTest();
		BatchCaseLink batch = new BatchCaseLink();
		batch.query += ' AND ta_interactions_Id__c IN (\'23456_01_I_SO_BAR\', \'23456_00_I_SO_BAR\', \'23456_00_C_SO_BAR\') LIMIT 10 ';
		ID batchprocessid = Database.executeBatch(batch);
		Test.StopTest();
		
		Case tcase1 = [SELECT ContactId, Household__c, AccountId FROM Case WHERE ta_interactions_Id__c = :case1.ta_interactions_Id__c][0];
		System.AssertEquals(tcase1.ContactId, c.id);
		Case tcase2 = [SELECT ContactId, Household__c, AccountId FROM Case WHERE ta_interactions_Id__c = :case2.ta_interactions_Id__c][0];
		System.AssertEquals(tcase2.Household__c, h.id);		
		Case tcase3 = [SELECT ContactId, Household__c, AccountId FROM Case WHERE ta_interactions_Id__c = :case3.ta_interactions_Id__c][0];
		System.AssertEquals(tcase3.AccountId, a.id);								
    }
    
    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchCaseLink', chainFlag);
    }
}