Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreferredAddress</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TesttrgAddressToAccountNew.cls
@IsTest
private class TesttrgAddressToAccountNew {
 public static testmethod void TesttrgAddressToAccountNew (){
        Test.startTest();
        
        
        Account a = new Account(Name = 'TestAccount',BillingStreet = 'baccteststreet',BillingCity = 'bacctestcity',BillingState = 'baccteststate',BillingCountry = 'tb',ShippingStreet = 'saccteststreet',ShippingCity = 'sacctestcity',ShippingState = 'saccteststate',ShippingCountry = 'ts');
        insert a;
        
        Address__c adr = new Address__c();
        adr.PreferredAddress__c  = true;
        adr.Account_Household__c = a.id;
        insert adr;
        
        //Account a1 = new Account(Id= a.id,Name = 'TestAccount',ShippingStreet = 'saccteststreet1',ShippingCity = 'sacctestcity1',ShippingState = 'saccteststate1',ShippingCountry = 'us');
        //update a1;
        
        Test.stopTest();
     }
}