Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing &amp; Shipping Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreferredAddress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seasonal_End_Date__c</fullName>
        <inlineHelpText>MMDD format</inlineHelpText>
        <label>Seasonal Address End Date</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seasonal_Start_Date__c</fullName>
        <inlineHelpText>MMDD Format</inlineHelpText>
        <label>Seasonal Address Start Date</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Country__c.object
<CustomObject>
    <description>Country objects</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchRemoveSeasonalAddress.cls
global class BatchRemoveSeasonalAddress {
    Public static void BatchRemoveSeasonalAddress () {
        String query = 'Select ID,Name, Street_1__c, City__c, State__c, Country__c, PreferredAddress__c, Postal_Code__c, Address_Type__c, Account_Household__c, Account_Household__r.Id,Seasonal_Start_Date__c,Seasonal_End_Date__c from Address__c';
        if(Test.isRunningTest()) query += ' Limit 100';
        BatchExecRemoveSeasonalAddress reassign = new BatchExecRemoveSeasonalAddress(query);
        ID batchprocessid = Database.executeBatch(reassign,100);
    }
}