Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing &amp; Shipping Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreferredAddress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seasonal_Start_Date__c</fullName>
        <inlineHelpText>MMDD Format</inlineHelpText>
        <label>Seasonal Address Start Date</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Country__c.object
<CustomObject>
    <description>Country objects</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/PopulateseasonalAddress.cls
Public class PopulateseasonalAddress {


    public PopulateseasonalAddress() { }
   
    public PopulateseasonalAddress(List<Address__c> lstAddress) {
   
             
    Map<Id, Address__c> NewAddresses = new Map<Id, Address__c>();
    
    Integer i = 0;
   
    
    for (Address__c adr : lstAddress) 
     {
        if(adr.PreferredAddress__c == true && adr.Account_Household__c != null)
        {
            if(NewAddresses.containsKey(adr.Account_Household__c)==false) NewAddresses.put(adr.Account_Household__c,adr);
        }
         i++;
    }
    

    List<Account> lstAccount = [Select Id,Name,BillingStreet,BillingCity,BillingState,BillingCountry,
            BillingPostalCode,ShippingStreet,ShippingCity,ShippingState,ShippingCountry,
            ShippingPostalCode from Account where Id IN :NewAddresses.keySet()];
             
            Date MyDate = System.today();
            integer month = MyDate.Month();
            integer day = MyDate.Day();
            
            String StartMonth = String.ValueOf(month);
            String StartDate = String.ValueOf(day);
            String FinalDate = StartMonth+'/'+StartDate;
            
            List<Account> updatedAccount = new List<Account>();

            for (Account a : lstAccount) 
            {

                Address__c parentAddress = NewAddresses.get(a.Id);
                   
                          if(parentAddress.Address_Type__c == 'Seasonal'  && parentAddress.Account_Household__c == a.Id && parentAddress.Seasonal_Start_Date__c == FinalDate)
                          {
                            a.BillingStreet = parentAddress.Street_1__c;
                            a.BillingCity = parentAddress.City__c;
                            a.BillingState = parentAddress.State__c;
                            a.BillingCountry = parentAddress.Country__c;
                            a.BillingPostalCode = parentAddress.Postal_Code__c;
                            a.ShippingStreet = parentAddress.Street_1__c;
                            a.ShippingCity = parentAddress.City__c;
                            a.ShippingState = parentAddress.State__c;
                            a.ShippingCountry = parentAddress.Country__c;
                            a.ShippingPostalCode = parentAddress.Postal_Code__c;
                            updatedAccount.add(a);
                          }      
                      }
         
             
            if(updatedAccount.size()>0 && updatedAccount!= null)
            { 
                 system.debug('updatedAccount :'+updatedAccount.size());   
                 update updatedAccount;
            
            }
       
       
     }   

}