Git_WGBH_QC/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Bios__c.object
<CustomObject>
    <description>Object utilized for listing the various ways in which a Contact is related to the Organization and/or personal highlights that are important for profiling a person.  This object will has multiple record types and field dependencies to represent the different types of records.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bio</label>
    <nameField>
        <displayFormat>Bio-{00000000}</displayFormat>
        <label>Bio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Campaign_Criteria_Template__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Criteria Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Criteria Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Campaign_Criteria_Template_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Campaign_Criteria_Template__c</referenceTo>
        <relationshipLabel>Campaign Criteria Template Detail</relationshipLabel>
        <relationshipName>Campaign_Criteria_Template_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Criteria Template Detail</label>
    <nameField>
        <displayFormat>TEMP-{0000}</displayFormat>
        <label>Template No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Criteria Template Detail</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Campaign_Member_Criteria__c.object
<CustomObject>
    <description>This object will have all the list of fields which will used to search campaign members.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <inlineHelpText>Field API Name</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Object_API_Name__c</fullName>
        <label>Parent Object API Name</label>
        <picklist>
            <picklistValues>
                <fullName>ACCOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADDRESS__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bios__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CASE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classification__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AccountActivity__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPPORTUNITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OpportunityLineItem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salutation__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giving_Summary__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CampaignMember</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <inlineHelpText>Object Label</inlineHelpText>
        <label>Parent Object Name</label>
        <picklist>
            <picklistValues>
                <fullName>ACCOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADDRESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CASES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLASSIFICATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTACTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIVING SUMMARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEADS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPPORTUNITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPPORTUNITY PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RELATIONSHIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SALUTATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAMPAIGN/PROGRAM MEMBER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign Member Criteria</label>
    <nameField>
        <label>Field label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member Criterias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations</description>
        <label>Annual</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>User__c</fullName>
        <description>Relationship with the user in the salesforce.com</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Requested_Search__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Search</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Requested Search#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Request__c.object
<CustomObject>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Campaign_Criteria_Template__c</referenceTo>
        <relationshipLabel>Search Request</relationshipLabel>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Request</label>
    <nameField>
        <displayFormat>REQ-{0000000000}</displayFormat>
        <label>Search Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Search Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Search Result</label>
    <nameField>
        <displayFormat>RES-{0000000000}</displayFormat>
        <label>Search Result#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/CampaignMemberResult.cls
public class CampaignMemberResult{

    List<SelectOption> tempFieldList;
    List<SelectOption> tempOperators;
        
    List<SelectOption> memberFieldList;
    
    Public String CampaignId{get;set;}
    Public String ActiveTab{get;set;}
    Public Integer TabIndex{get;set;}
    Public boolean blnAddmember{get;set;}
    Public boolean blnExistingMember{get;set;}
    Public String lblExistingMembers{get;set;}
    Public boolean blnAction{get;set;}    
    Public boolean blnAdvanceFilter{get;set;}
    Public String AdvanceFilter{get;set;}
    public String selectedStatusExisting{get;set;}
    String emptyTableText = 'There are no members to display. Use the search options to find and add members.';
    String queryLimit = '25';    
    string mode='';
    public CampaignMemberResult (ApexPages.StandardController controller) {
        lstContactResult = new List<ContactResult>();
        blnLoadDiv = false;
        
        blnAction = false;
        blnAdvanceFilter = true;
        CampaignId = ApexPages.currentPage().getParameters().get('id');
        mode = ApexPages.currentPage().getParameters().get('mode');
        /////////////
        /////////////
        resetPaging();
        try{
            //setDefaultTab();
            LoadDataForBatch();
        }Catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
        }
        /*
        if(mode == 'batch'){
            setDefaultTab();
            tempFieldList = getFieldList();            
            memberFieldList = getMemberField();
            PopulateListCriteriaAdd();
            PopulateListCriteriaExisting();
            LoadDataForBatch();
        }
        else{
            setDefaultTab();
            tempFieldList = getFieldList();
            
            memberFieldList = getMemberField();
            PopulateListCriteriaAdd();
            PopulateListCriteriaExisting();
        }
        */
        //////////////////////////////////For Batch
        
    }
    String batchRequestId = '';
    void LoadDataForBatch(){
        if(mode=='batch'){
            batchRequestId = ApexPages.currentPage().getParameters().get('RequestID');
            if(NVL(batchRequestId) != ''){
                List<Search_Request__c> lstSearchRequest = [Select Id, Criteria__c, Status__c, Template__c, User__c
                From Search_Request__c Where Id=:batchRequestId];
                if(lstSearchRequest != null && lstSearchRequest.size()>0){
                    SelectedView = lstSearchRequest[0].Template__c;
                    AdvanceFilter = lstSearchRequest[0].Criteria__c;
                    
                    List<AggregateResult> lstQuery = [Select Max(Index__c) total From Requested_Search__c Where Request__c =: batchRequestId];
                    if(lstQuery != null && lstQuery.size()>0){
                        String total = NVL(String.valueOf(lstQuery[0].get('total')));
                        noOfConditions = Integer.valueOf(total);
                    }
                } 
                //changeExistingView();
                QueryFinalResult(batchRequestId);
            }
        }
    }
    Public PageReference resetFilterExisting(){
        return null;
    }
    public boolean IsTest{get;set;}  
    Public String selectedStatus{get;set;}
   
    public List<SelectOption> getStatus() {
        List<SelectOption> options = new List<SelectOption>();
        List<CampaignMemberStatus> lstStatus = new List<CampaignMemberStatus>();
        Boolean blnInsertedFound = false;
        Integer sortOrder = 1;
        lstStatus = [Select Id, Label, IsDefault, SortOrder From CampaignMemberStatus Where CampaignId =: CampaignId];
        if(lstStatus != null && lstStatus.size()>0){
            for(CampaignMemberStatus status:lstStatus){
                options.add(new SelectOption(status.Label,status.Label)); 
                sortOrder++;
                if(status.Label.trim().toUpperCase() == 'INSERTED')
                    blnInsertedFound = true;
                if(status.IsDefault == true)
                    selectedStatus = status.Label;
            }
        }
        If(blnInsertedFound == false){
            CampaignMemberStatus objInserted = new CampaignMemberStatus();
            objInserted.Label = 'Inserted';
            objInserted.IsDefault = true;
            objInserted.CampaignId = CampaignId;
            objInserted.SortOrder = SortOrder;
            //insert objInserted;
            //options.add(new SelectOption('Inserted','Inserted')); 
        }
        return options; 
    }
    Public PageReference SelectSearchType(){
        tempFieldList = getFieldList();
        
        memberFieldList = getMemberField();
        
        //PopulateListCriteriaAdd();
        
        resetPaging();
        lstContactResult = new List<ContactResult>();
        lstPagingAddContact = new List<ContactResult>();
        
        lstLeadResult = new List<LeadResult>();
        lstPagingAddLead = new List<LeadResult>();
        return null;
    }

    String SelectedSearch = 'CONTACT';
               
    public String getSelectedSearch() {
        return SelectedSearch;
    }
                    
    public void setSelectedSearch(String SelectedSearch) { this.SelectedSearch= SelectedSearch; }
    
    public List<SelectOption> ExistingViews;
    public string SelectedView{get;set;}
    
    
    private List<SelectOption> getMemberField() {        
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('--None--','--None--'));
        //System.Label.RecurringDonationStageName
        options.add(new SelectOption('CampaignMember;ContactId;text',getLabel('CampaignMember') + ' Contact ID' ));
        options.add(new SelectOption('CampaignMember;LeadId;text',getLabel('CampaignMember') + ' Lead ID' ));
        options.add(new SelectOption('CampaignMember;Type;text','Type' ));//custom
        options.add(new SelectOption('CampaignMember;Id;text',getLabel('CampaignMember') + ' ID' ));   
        options.add(new SelectOption('CampaignMember;Status;picklist','Status' ));  
        options.add(new SelectOption('CampaignMember;Name;text','Name')); 
        options.add(new SelectOption('CampaignMember;FirstName;text','First Name'));
        options.add(new SelectOption('CampaignMember;LastName;text','Last Name'));
        options.add(new SelectOption('CampaignMember;Campaign.Name;text',getLabel('Campaign') + ' Name'));
        options.add(new SelectOption('CampaignMember;Title;text','Title'));
        options.add(new SelectOption('CampaignMember;Company;text','Company'));
        options.add(new SelectOption('CampaignMember;Phone;text','Phone'));
        options.add(new SelectOption('CampaignMember;Mobile;text','Mobile'));
        options.add(new SelectOption('CampaignMember;Fax;text','Fax'));
        options.add(new SelectOption('CampaignMember;Email;text','Email'));
        options.add(new SelectOption('CampaignMember;Email_opt_out;text','Email Opt-out'));
        options.add(new SelectOption('CampaignMember;Donotcall;text','Do not Call'));
        options.add(new SelectOption('CampaignMember;OwnerAlias;text',getLabel('Lead') + '/' + getLabel('Contact') + ' Owner Alias' ));
        options.add(new SelectOption('CampaignMember;OwnerFirstName;text',getLabel('Lead') + '/' + getLabel('Contact') + ' Owner First Name' ));
        options.add(new SelectOption('CampaignMember;OwnerLastName;text',getLabel('Lead') + '/' + getLabel('Contact') + ' Owner Last Name' ));
        options.add(new SelectOption('CampaignMember;OwnerFullName;text',getLabel('Lead') + '/' + getLabel('Contact') + ' Owner Full Name' ));
        options.add(new SelectOption('CampaignMember;AccOwnerAlias;text',getLabel('Account') + ' Owner Alias' ));
        options.add(new SelectOption('CampaignMember;AccOwnerFirstName;text',getLabel('Account') + ' Owner First Name' ));
        options.add(new SelectOption('CampaignMember;AccOwnerLastName;text',getLabel('Account') + ' Owner Last Name' ));
        options.add(new SelectOption('CampaignMember;AccOwnerFullName;text',getLabel('Account') + ' Owner Full Name' ));
        
        options.add(new SelectOption('CampaignMember;Street;text','Street'));
        options.add(new SelectOption('CampaignMember;City;text','City'));
        options.add(new SelectOption('CampaignMember;State;text','State'));
        options.add(new SelectOption('CampaignMember;Zip;text','Zip'));
        options.add(new SelectOption('CampaignMember;Country;text','Country'));
        options.add(new SelectOption('CampaignMember;LastModifiedDate;text','Last Modified Date'));
        
        return options;          
    }
    String getSelectFields(){
        String fields = 'Id, LeadId, CampaignId, ContactId, Lead.Name, Lead.Company, Status, LastModifiedDate,'; 
        fields += 'Contact.Name, Contact.Title, Lead.Title, Lead.Email, Contact.Account.Name, Contact.Email';
        
        return fields;
    }
    String getCondition(String fieldName, String operator, String value, String fieldType){
        String Condition = '';
        if(fieldName != null && fieldName.trim().length()>0){
            if(fieldName == 'ContactId'){
                Condition = 'Contact.Id ' +  getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'LeadId'){
                Condition = 'Lead.Id ' +  getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'Type'){
                if(value.trim().length()>0){
                    if(value.trim().toUpperCase() == 'CONTACT' || value.trim().toUpperCase() == getLabel('Contact').toUpperCase()){
                        if(operator == 'n')// not equal to
                            Condition = ' (Contact.Id = null Lead.Id <> null) ';
                        if(operator == 'e')// equal to
                            Condition = ' (Lead.Id = null And Contact.Id <> null) ';
                    }
                    if(value.trim().toUpperCase() == 'LEAD' || value.trim().toUpperCase() == 'LEADS' || value.trim().toUpperCase() == getLabel('Lead').toUpperCase()){
                        if(operator == 'n')// not equal to
                            Condition = ' (Lead.Id = null Contact.Id <> null) ';
                        if(operator == 'e')// equal to
                            Condition = ' (Contact.Id = null And Lead.Id <> null) ';
                    }
                }
            }
            if(fieldName == 'Id'){
                Condition = ' Id ' +  getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'Status'){
                Condition = ' Status ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'LastModifiedDate'){
                Condition = ' LastModifiedDate ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'Name'){
                Condition = ' (Contact.Name ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Name ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'FirstName'){
                Condition = ' (Contact.FirstName ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.FirstName ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'LastName'){
                Condition = ' (Contact.LastName ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.LastName ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Campaign.Name'){
                Condition = ' Campaign.Name ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'Title'){
                Condition = ' (Contact.Title ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Title ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Company'){
                Condition = ' (Contact.Account.Name ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Company ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Phone'){
                Condition = ' (Contact.Phone ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Phone ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Mobile'){
                Condition = ' (Contact.MobilePhone ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.MobilePhone ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Fax'){
                Condition = ' (Contact.Fax ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Fax ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Email'){
                Condition = ' (Contact.Email ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Email ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Email_opt_out'){
                Condition = ' (Contact.HasOptedOutOfEmail ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.HasOptedOutOfEmail ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Donotcall'){
                Condition = ' (Contact.DoNotCall ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.DoNotCall ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'OwnerAlias'){
                Condition = ' (Contact.Owner.Alias ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Owner.Alias ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'OwnerFirstName'){
                Condition = ' (Contact.Owner.FirstName ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Owner.FirstName ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'OwnerLastName'){
                Condition = ' (Contact.Owner.LastName ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Owner.LastName ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'OwnerFullName'){
                Condition = ' (Contact.Owner.Name ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Owner.Name ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            
            
            if(fieldName == 'AccOwnerAlias'){
                Condition = ' Contact.Account.Owner.Alias ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'AccOwnerFirstName'){
                Condition = ' Contact.Account.Owner.FirstName ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'AccOwnerLastName'){
                Condition = ' Contact.Account.Owner.LastName ' + getOperatorSymbol(operator, value, fieldType);
            }
            if(fieldName == 'AccOwnerFullName'){
                Condition = ' Contact.Account.Owner.Name ' + getOperatorSymbol(operator, value, fieldType);
            }
            
            if(fieldName == 'State'){
                Condition = ' (Contact.MailingState ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.State ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Street'){
                Condition = ' (Contact.MailingStreet ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Street ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'City'){
                Condition = ' (Contact.MailingCity ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.City ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Zip'){
                Condition = ' (Contact.MailingPostalCode ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.PostalCode ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
            if(fieldName == 'Country'){
                Condition = ' (Contact.MailingCountry ' + getOperatorSymbol(operator, value, fieldType);
                Condition += ' OR Lead.Country ' + getOperatorSymbol(operator, value, fieldType) + ') ';
            }
        }
        Return Condition;
    }
    
    Public List<ExistingMember> lstExistingMember{get;set;}
    Public Class ExistingMember{
        Public boolean selected{get;set;}
        Public ID memberId{get;set;}
        Public ID contactId{get;set;}
        Public ID leadId{get;set;}
        Public String Name{get;set;}
        Public String MemberType{get;set;}
        Public String Title{get;set;}
        Public String Company{get;set;}
        Public String Email{get;set;}
        Public String Status{get;set;}
        Public DateTime LastModifiedDate{get;set;}
    }
    string getLabel(String objectName){
        String strResult = '';

        Map<String, Schema.SObjectType> m = Schema.getGlobalDescribe() ;
        Schema.SObjectType s = m.get(objectName) ;
        Schema.DescribeSObjectResult r = s.getDescribe() ;
        System.debug('The label for this Object is '+r.getLabel() ) ;
        strResult = r.getLabel();
        return strResult;
    }
    string getLabel(String objectName, String FieldName){
        String strResult = '';

    Map<String, Schema.SObjectType> m = Schema.getGlobalDescribe() ;
    Schema.SObjectType s = m.get(objectName) ;
    Schema.DescribeSObjectResult r = s.getDescribe() ;
    // we can get various attributes and propeties on the SObject
    System.debug('The label for this Object is '+r.getLabel() ) ;
    strResult = r.getLabel();
    //if(r.isCustom())
    //    System.debug(' Custom object' ) ;
    // etc..
    // Get all the fields 
    //Map<String, Schema.SObjectField> fields = r.fields.getMap() ;
    // Can now retrieve a particular field and get additional properties
    //Schema.SObjectField f = fields.get('BillingCity' ) ;
    //Schema.DescribeFieldResult r2 = f.getDescribe() ;
    //System.debug( 'The label for this field is '+r2.getLabel() ) ;
        
        return strResult;
    }
    private List<SelectOption> getFieldList() {
        List<Campaign_Member_Criteria__c> lstCampaignCriteria = [Select ID,Name,Lead__c,Contact__c,Field_Name__c,Parent_Object__c,Parent_Object_API_Name__c,Field_Type__c from Campaign_Member_Criteria__c order by Parent_Object__c,Name];
        
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('--None--','--None--'));
        
        for(Campaign_Member_Criteria__c c: lstCampaignCriteria) {
            if(SelectedSearch == 'LEAD'){
                if(c.Lead__c == true)
                    options.add(new SelectOption(c.Parent_Object_API_Name__c + ';' + c.Field_Name__c + ';' + c.Field_Type__c, c.Parent_Object__c + '.' + c.Name));
            }
            if(SelectedSearch == 'CONTACT'){
                if(c.Contact__c == true)
                    options.add(new SelectOption(c.Parent_Object_API_Name__c + ';' + c.Field_Name__c + ';' + c.Field_Type__c, c.Parent_Object__c + '.' + c.Name));
            }
        }
        return options;
    }   
    public PageReference AddNewSearchRow() {
        //ListCriteria.add(new SearchingCriteria(tempFieldList,tempOperators,'',tempCondition,ListCriteria.size()+1 ));
        return null;
    }
    public PageReference AddNewSearchRowExisting() {
        //ListCriteriaExisting.add(new SearchingCriteria(memberFieldList,tempOperators,'',tempCondition ));
        return null;
    }
        
    public List<CampaignMember> getNewCampaignMembers() {
        List<CampaignMember> lstMem = new List<CampaignMember>();
        return lstMem;
    }
    
    


    Public String templateName{get;set;}
    public List<SelectOption> getExistingViewsOld() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('--None--','--None--'));
        List<Campaign_Criteria_Template__c> lstTemplate = new List<Campaign_Criteria_Template__c>();
        lstTemplate = [select id, name, Lead__c, Contact__c from Campaign_Criteria_Template__c];        
        
        if(lstTemplate.size()>0){
            for(Campaign_Criteria_Template__c t:lstTemplate){
                if(SelectedSearch == 'LEAD')
                    if(t.Lead__c == true)
                        options.add(new SelectOption(t.id,t.name));
                if(SelectedSearch == 'CONTACT')
                    if(t.Contact__c == true)
                        options.add(new SelectOption(t.id,t.name));
            }
        }
        
        return options;
    } 
    public List<SelectOption> getExistingViews() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('--None--','--None--'));
        List<Campaign_Criteria_Template__c> lstTemplate;
        if(selectedGroup != null && selectedGroup != '--None--'){
            lstTemplate = new List<Campaign_Criteria_Template__c>();
            lstTemplate = [select id, name, Lead__c, Contact__c 
            from Campaign_Criteria_Template__c Where Group__c =: selectedGroup];
        }
        else{
            lstTemplate = new List<Campaign_Criteria_Template__c>();
            lstTemplate = [select id, name, Lead__c, Contact__c 
            from Campaign_Criteria_Template__c];       
        } 
        
        if(lstTemplate.size()>0){
            for(Campaign_Criteria_Template__c t:lstTemplate){
                if(SelectedSearch == 'LEAD')
                    if(t.Lead__c == true)
                        options.add(new SelectOption(t.id,t.name));
                if(SelectedSearch == 'CONTACT')
                    if(t.Contact__c == true)
                        options.add(new SelectOption(t.id,t.name));
            }
        }
        SelectedView = '--None--';
        return options;
    } 
    public String selectedGroup{get;set;}
    public List<SelectOption> getTemplateGroup() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Campaign_Criteria_Template__c.Group__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('--None--', '--None--'));
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }               
        SelectedView = '--None--';
        return options;
    } 
    
    Public PageReference addMember(){
        List<CampaignMember> lstMemberInsert = new List<CampaignMember>();
        List<CampaignMember> lstMemberUpdate = new List<CampaignMember>();
        if(SelectedSearch=='CONTACT'){
            if(lstContactResult != null && lstContactResult.size()>0){
                for(ContactResult result:lstContactResult){
                    if(result.selected == true){
                        if(result.memberId == null){
                            CampaignMember mem = new CampaignMember();
                            mem.CampaignId = CampaignId;
                            mem.ContactId = result.objContact.Id;
                            mem.status = selectedStatus;
                            
                            lstMemberInsert.add(mem);
                        }
                        if(result.memberId != null){
                            result.objMember.status = selectedStatus;
                            lstMemberUpdate.add(result.objMember);
                        }
                    }
                }
            }        
        }
        else if(SelectedSearch == 'LEAD'){
            if(lstLeadResult != null && lstLeadResult.size()>0){
                for(LeadResult result:lstLeadResult){
                    if(result.selected == true){
                        if(result.memberId == null){
                            CampaignMember mem = new CampaignMember();
                            mem.CampaignId = CampaignId;
                            mem.LeadId = result.objLead.Id;
                            mem.status = selectedStatus;
                            
                            lstMemberInsert.add(mem);
                        }
                        if(result.memberId != null){
                            result.objMember.status = selectedStatus;
                            lstMemberUpdate.add(result.objMember);
                        }
                    }
                }
            }        
        }
        
        if(lstMemberInsert != null && lstMemberInsert.size()>0){
            try{
                insert lstMemberInsert;
                ActiveTab = 'EXISTINGMEMBER';
                //selectTab();
                String msg;
                msg = 'You have successfully added ' + String.valueOf(lstMemberInsert.size()) + ' member(s).';
                msg += '\nYou can add more members to this campaign using the \'Add Members\' tab.';
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,msg)); 
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
            }
        }
        if(lstMemberUpdate != null && lstMemberUpdate.size()>0){
            try{
                update lstMemberUpdate;
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
            }
        }
        //LoadExistingMembers();
        return null;
    }
    Public List<ContactResult> lstContactResult{get;set;}
    Public Class ContactResult{
        Public boolean selected{get;set;}
        Public Contact objContact{get;set;}
        Public String MemberStatus{get;set;}
        Public ID memberId{get;set;}
        Public CampaignMember objMember{get;set;}
    }
    Public List<LeadResult> lstLeadResult{get;set;}
    Public Class LeadResult{
        Public boolean selected{get;set;}
        Public Lead objLead{get;set;}
        Public String MemberStatus{get;set;}
        Public ID memberId{get;set;}
        Public CampaignMember objMember{get;set;}
    }
    Public String refreshed{get;set;}
    String getContactFieldName(String ObjectName){
        if(ObjectName.trim().length()>0){
            if(ObjectName.trim().toUpperCase() == 'OPPORTUNITY' || ObjectName.trim().toUpperCase() == 'GIVING')
                return 'Oppty_Related_Contact__c';
            if(ObjectName.trim().toUpperCase() == 'BIO' || ObjectName.trim().toUpperCase() == 'BIOS' || ObjectName.trim().toUpperCase() == 'BIOS__C')
                return 'Related_To__c';
            if(ObjectName.trim().toUpperCase() == 'ADDRESS' || ObjectName.trim().toUpperCase() == 'ADDRESS__C')
                return 'Contact__c';
            if(ObjectName.trim().toUpperCase() == 'CASE' || ObjectName.trim().toUpperCase() == 'CASES')
                return 'ContactId';
            if(ObjectName.trim().toUpperCase() == 'CLASSIFICATION' || ObjectName.trim().toUpperCase() == 'CLASSIFICATIONS' || ObjectName.trim().toUpperCase() == 'CLASSIFICATION__C')
                return 'Contact__c';
            if(ObjectName.trim().toUpperCase() == 'GIVING SUMMARY' || ObjectName.trim().toUpperCase() == 'GIVING_SUMMARY__C' || ObjectName.trim().toUpperCase() == 'GIVINGSUMMARY')
                return 'Account__r.One2OneContact__c';
            if(ObjectName.trim().toUpperCase() == 'OPPORTUNITY PRODUCT' || ObjectName.trim().toUpperCase() == 'OPPORTUNITYPRODUCT' || ObjectName.trim().toUpperCase() == 'OPPORTUNITYLINEITEM')
                return 'Opportunity.Oppty_Related_Contact__c';
            if(ObjectName.trim().toUpperCase() == 'RELATIONSHIP' || ObjectName.trim().toUpperCase() == 'RELATIONSHIPS__C')
                return 'People__c';
            if(ObjectName.trim().toUpperCase() == 'EVENT')
                return 'WhoId';
            if(ObjectName.trim().toUpperCase() == 'TASK')
                return 'WhoId';
            if(ObjectName.trim().toUpperCase() == 'CAMPAIGNMEMBER' || ObjectName.trim().toUpperCase() == 'CAMPAIGN MEMBER' || ObjectName.trim().toUpperCase() == 'CAMPAIGN/PROGRAM MEMBER')
                return 'ContactId';  
            if(ObjectName.trim().toUpperCase() == 'TASK')
                return 'WhoId';  
            if(ObjectName.trim().toUpperCase() == 'ACCOUNT')
                return 'One2OneContact__c';  
            if(ObjectName.trim().toUpperCase() == 'CONTACT' || ObjectName.trim().toUpperCase() == 'LEAD')
                return 'Id';  
            else
                return '';
        }
        else
            return '';
    }
    String getObjectName(String ObjectName){
        if(ObjectName.trim().length()>0){
            if(ObjectName.trim().toUpperCase() == 'OPPORTUNITY' || ObjectName.trim().toUpperCase() == 'GIVING')
                return 'Opportunity';
            if(ObjectName.trim().toUpperCase() == 'BIO' || ObjectName.trim().toUpperCase() == 'BIOS' || ObjectName.trim().toUpperCase() == 'BIOS__C')
                return 'Bios__c';
            if(ObjectName.trim().toUpperCase() == 'ADDRESS' || ObjectName.trim().toUpperCase() == 'ADDRESS__C')
                return 'Address__c';
            if(ObjectName.trim().toUpperCase() == 'CASE' || ObjectName.trim().toUpperCase() == 'CASES')
                return 'Case';
            if(ObjectName.trim().toUpperCase() == 'CLASSIFICATION' || ObjectName.trim().toUpperCase() == 'CLASSIFICATIONS' || ObjectName.trim().toUpperCase() == 'CLASSIFICATION__C')
                return 'Classification__c';
            if(ObjectName.trim().toUpperCase() == 'GIVING SUMMARY' || ObjectName.trim().toUpperCase() == 'GIVING_SUMMARY__C' || ObjectName.trim().toUpperCase() == 'GIVINGSUMMARY')
                return 'Giving_Summary__c';
            if(ObjectName.trim().toUpperCase() == 'OPPORTUNITY PRODUCT' || ObjectName.trim().toUpperCase() == 'OPPORTUNITYPRODUCT' || ObjectName.trim().toUpperCase() == 'OPPORTUNITYLINEITEM')
                return 'OpportunityLineItem';
            if(ObjectName.trim().toUpperCase() == 'RELATIONSHIP' || ObjectName.trim().toUpperCase() == 'RELATIONSHIPS__C')
                return 'Relationships__c';
            if(ObjectName.trim().toUpperCase() == 'EVENT')
                return 'Event';
            if(ObjectName.trim().toUpperCase() == 'TASK')
                return 'Task';
            if(ObjectName.trim().toUpperCase() == 'CAMPAIGNMEMBER' || ObjectName.trim().toUpperCase() == 'CAMPAIGN MEMBER' || ObjectName.trim().toUpperCase() == 'CAMPAIGN/PROGRAM MEMBER')
                return 'CampaignMember'; 
            if(ObjectName.trim().toUpperCase() == 'CONTACT')
                return 'Contact';  
            if(ObjectName.trim().toUpperCase() == 'LEAD')
                return 'Lead';  
            if(ObjectName.trim().toUpperCase() == 'ACCOUNT')
                return 'Account';  
            else
                return '';
        }
        else
            return '';
    }
    Public Boolean blnSelectAll{get;set;}
    Public PageReference SubmitRequest(){
    
        system.debug('########## Submit Request ############');
        Search_Request__c objRequest = new Search_Request__c();
        objRequest.Criteria__c = AdvanceFilter;
        objRequest.User__c = UserInfo.getUserId();
        if(SelectedView != null && SelectedView != '--None--'){
            objRequest.Template__c = SelectedView;
        }else{
            //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,msg)); 
            
            templateName = 'Temp';
            templateName += String.valueOf(System.Now().Year());
            templateName += String.valueOf(System.Now().Month());
            templateName += String.valueOf(System.Now().Day());
            templateName += String.valueOf(System.Now().Hour());
            templateName += String.valueOf(System.Now().Minute());
            templateName += String.valueOf(System.Now().Second());
            this.SaveTemplate();
            objRequest.Template__c = SelectedView;
        }
        objRequest.Campaign__c = CampaignId;
        objRequest.Status__c = 'In Progress';
        if(SelectedSearch == 'CONTACT'){
            objRequest.IsContact__c = true;
        }
        else{
            objRequest.IsContact__c = false;
        }
        Insert objRequest;
        ReqID = objRequest.Id;
        QueryRequest(objRequest.Id);
        return null;
    }
    ID ReqID;
    String QueryRequest(ID RequestId){
        List<String> lstQuery = new List<String>();
        List<Requested_Search__c> lstSearch = new List<Requested_Search__c>();
        Integer index = 1;
        
        String query = '';
        List<String> lstCondition = new List<String>();
        String objectName = '';
        String Field = '';
        String Condition = '';
        String innerCondition = '';
        String conditionalOperator = 'And';
        query = 'Select ' + Queryfields() + ' from ' + SelectedSearch;
        Integer i = 0;
        Integer NextRow = 0;
        return query;
    } 
    public string QueryId{get;set;}
    Public String currentIndex{get;set;}
    Integer noOfConditions;
    public boolean blnLoadDiv{get;set;}
    public boolean QuerySubmitted;
    public string strBatchAddCampaignMemberId{get;set;}
    
    public pageReference batchAddMember(){    
        blnLoadDiv = true;            
        if(SelectedSearch == 'LEAD'){
            BatchAddCampaignMember.BatchSearchContact(reqId, CampaignId, selectedStatus, false);
        }
        else if(SelectedSearch == 'CONTACT'){
            BatchAddCampaignMember.BatchSearchContact(reqId, CampaignId, selectedStatus, true);
        }
        //LoadExistingMembers();
        return null;
    }
    
    Public Pagereference reloadExistingMembers(){
        //if(lstMemberInsert != null && lstMemberInsert.size()>0){
            try{
                ActiveTab = 'EXISTINGMEMBER';
                //selectTab();
                String msg;
                //msg = 'You have successfully added ' + String.valueOf(lstMemberInsert.size()) + ' member(s).';
                msg = 'You have successfully added member(s).';
                msg += '\nYou can add more members to this campaign using the \'Add Members\' tab.';
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,msg)); 
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
            }
        //}        
        //LoadExistingMembers();
        blnLoadDiv = false;
        return null;
    }
    
    public pagereference batch() {
        
        return null;
    }
    void QueryFinalResult(String queryRequestId){
        List<sObject> lstFinal;
        system.debug('############## Batch Apex Called ################');
        String query = 'Select ' + Queryfields() + ' from ' + SelectedSearch + ' ';
            
        String rQuery;
        if(SelectedSearch == 'CONTACT'){
            rQuery = 'Select ContactLookup__c From Search_Result__c';
        }else{
            rQuery = 'Select LeadLookup__c From Search_Result__c';
        }
        String strAdv = '';
        if(NVL(AdvanceFilter)!=''){
            strAdv = AdvanceFilter;
            if(noOfConditions > 0){
                for(integer i=1;i<=noOfConditions;i++){
                    strAdv = strAdv.replace(string.valueOf(i), 'col' + string.valueOf(i) + '__c = true');
                }
            }
        }else{
            if(noOfConditions > 0){
                for(integer i=1;i<=noOfConditions;i++){
                    strAdv = strAdv.replace(string.valueOf(i), 'col' + string.valueOf(i) + '__c');
                    if(strAdv == ''){
                        strAdv = 'col' + string.valueOf(i) + '__c = true';
                    }
                    else{
                        strAdv += ' or col' + string.valueOf(i) + '__c = true';
                    }
                }
            }
        }
        rQuery += ' Where (' + strAdv + ') And Request__c = \'' + queryRequestId + '\'';
        system.debug('################## rQuery : ' + rQuery);
        Query += ' Where id in(' + rQuery + ')';
        Query += ' Limit 2000';
        lstFinal = Database.Query(Query);
        system.debug('############# Final Query : ' + Query);
        if(lstFinal != null && lstFinal.size()>0){
            FinalResult(lstFinal);
        }
        blnCallBatch = false;
        blnLoadDiv = false;
    }
    Public PageReference FinalResult(List<sObject> lstResult){
        try{
            resetPaging();
            //String Query = generateQuery();
            lstContactResult = new List<ContactResult>();
            lstLeadResult = new List<LeadResult>();
            List<CampaignMember> lstMember;
            
                if(lstResult != null && lstResult.size()>0){                
                    if(SelectedSearch == 'CONTACT'){
                        system.debug('############ Contact');
                        lstMember = [Select Id, ContactId, Status
                        From CampaignMember Where ContactId != null and CampaignId =: CampaignId];
                    }
                    else if(SelectedSearch == 'LEAD'){
                        system.debug('############ Lead');
                        lstMember = [Select Id, LeadId, Status
                        From CampaignMember Where LeadId != null and CampaignId =: CampaignId];
                    }
                    for(sObject s:lstResult){
                        if(SelectedSearch == 'CONTACT'){
                            Contact c = new Contact();
                            CampaignMember objMember = new CampaignMember();
                            c = (Contact) s;
                            ContactResult result = new ContactResult();
                            result.selected = false;
                            result.objContact = c;
                            result.memberId = null;
                            result.MemberStatus = '';
                            result.objMember = null;
                            for(CampaignMember mem:lstMember){
                                if(c.Id == mem.ContactId){
                                    result.memberId = mem.Id;
                                    result.MemberStatus = mem.Status;
                                    result.objMember = mem;
                                }
                            }
                            lstContactResult.add(result);
                        }
                        else if(SelectedSearch == 'LEAD'){
                            Lead L = new Lead();
                            CampaignMember objMember = new CampaignMember();
                            L = (Lead) s;
                            LeadResult result = new LeadResult();
                            result.selected = false;
                            result.objLead = L;
                            result.memberId = null;
                            result.MemberStatus = '';
                            result.objMember = null;
                            for(CampaignMember mem:lstMember){
                                if(L.Id == mem.LeadId){
                                    result.memberId = mem.Id;
                                    result.MemberStatus = mem.Status;
                                    result.objMember = mem;
                                }
                            }
                            lstLeadResult.add(result);
                        }
                    }
                }
            refreshed = '';
            system.debug('$$$$$$$$$$$##### lstContactResult ' + lstContactResult);
            if((SelectedSearch == 'LEAD' && lstLeadResult.size()<=0) || (SelectedSearch == 'CONTACT' && lstContactResult.size()<=0)){
                refreshed = emptyTableText;
                system.debug('$$$$$$$$$$$ lstContactResult ' + lstContactResult);
            }
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
        }
        /*}catch(System.DmlException e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage())); 
        }*/
        return null;
    }
    Public PageReference Go(){
        try{
            resetPaging();
            String Query = generateQuery();
            List<sObject> lstResult = new List<sObject>();
            lstContactResult = new List<ContactResult>();
            lstLeadResult = new List<LeadResult>();
            List<CampaignMember> lstMember;
            
            if(Query != null && Query.trim().Length()>0){
                try{
                    lstResult = Database.Query(Query);
                }catch(System.DmlException e){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage())); 
                }
                if(lstResult != null && lstResult.size()>0){                
                    if(SelectedSearch == 'CONTACT'){
                        lstMember = [Select Id, ContactId, Status
                        From CampaignMember Where ContactId != null and CampaignId =: CampaignId];
                    }
                    else if(SelectedSearch == 'LEAD'){
                        lstMember = [Select Id, LeadId, Status
                        From CampaignMember Where LeadId != null and CampaignId =: CampaignId];
                    }
                    for(sObject s:lstResult){
                        if(SelectedSearch == 'CONTACT'){
                            Contact c = new Contact();
                            CampaignMember objMember = new CampaignMember();
                            c = (Contact) s;
                            ContactResult result = new ContactResult();
                            result.selected = false;
                            result.objContact = c;
                            result.memberId = null;
                            result.MemberStatus = '';
                            result.objMember = null;
                            for(CampaignMember mem:lstMember){
                                if(c.Id == mem.ContactId){
                                    result.memberId = mem.Id;
                                    result.MemberStatus = mem.Status;
                                    result.objMember = mem;
                                }
                            }
                            lstContactResult.add(result);
                        }
                        else if(SelectedSearch == 'LEAD'){
                            Lead L = new Lead();
                            CampaignMember objMember = new CampaignMember();
                            L = (Lead) s;
                            LeadResult result = new LeadResult();
                            result.selected = false;
                            result.objLead = L;
                            result.memberId = null;
                            result.MemberStatus = '';
                            result.objMember = null;
                            for(CampaignMember mem:lstMember){
                                if(L.Id == mem.LeadId){
                                    result.memberId = mem.Id;
                                    result.MemberStatus = mem.Status;
                                    result.objMember = mem;
                                }
                            }
                            lstLeadResult.add(result);
                        }
                    }
                }
            }
            refreshed = '';
            if((SelectedSearch == 'LEAD' && lstLeadResult.size()<=0) || (SelectedSearch == 'CONTACT' && lstContactResult.size()<=0)){
                refreshed = emptyTableText;
            }
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
        }
        /*}catch(System.DmlException e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage())); 
        }*/
        return null;
    }
    String Queryfields(){
        String fields = '';
        if(SelectedSearch == 'LEAD'){
            fields = ' id, FirstName, LastName, Title, Company, Email ';
        }
        else if(SelectedSearch == 'CONTACT'){
            fields = ' id, FirstName, LastName, Title, Account.Name, Email, AccountId ';
        }
        return fields;
    }
    public boolean blnCallBatch{get;set;}    
    public void checkStatus(){
        List<Requested_Search__c> lstRequest = [Select Status__c From Requested_Search__c Where Id=:QueryId];
        if(lstRequest != null && lstRequest.size()>0){
            if(lstRequest[0].Status__c == 'Pending'){
                blnCallBatch = true;
            }
            else{
                blnCallBatch = false;
            }
        }
    }
    String generateQuery(){
        return '';
    }
    String NVL(string val){
        if(val == null)
            return '';
        else return val.trim();
    }
    String getObjectNameById(String objId){
        String objName = '';
        String prefix = '';
        try{
            objId = NVL(objId);
            if(objId.length()>3){
                prefix = NVL(objId).trim().substring(0,3);
                if(prefix == '003')
                    objName = 'CONTACT';
            }
            Return objName;
        }catch(Exception ex){
            Return '';
        }
    }
    String setValueBasedonType(String Value, String dataType){
        String retValue = '';
        if (dataType.trim().toUpperCase()=='TEXT'){
            retValue =  '\'' + Value + '\'';
        }
        else if (dataType.trim().toUpperCase()=='NUMBER'){
            retValue =  Value;
        }
        else if (dataType.trim().toUpperCase()=='PICKLIST'){
            retValue =  '\'' + Value + '\'';
        }
        else if(dataType.trim().toUpperCase() == 'CHECKBOX'){
            retValue = Value;
        }
        else if (dataType.trim().toUpperCase()=='DATETIME'){
            //retValue =  '\'' + Value + '\'';
            //retValue = DateTime.valueof(value).format('YYYY-MM-DDThh:mm:ssZ');  
            retValue = DateTime.valueof(value).format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'');      
        }
        else if (dataType.trim().toUpperCase()=='DATE'){
            retValue = value;
            system.debug('####### value of Date:  ' + value);
        }
        return retValue;
    }
    String PicklistCondition(String Code, String Originalvalue){
        code = code.trim().toLowerCase();
        String operator = '';
        String Condition = '';
        //
        List<String> lstValues = OriginalValue.split(',');
        if(lstValues != null && lstValues.size()>0){
            for(string strVal:lstValues){
                String value =  setValueBasedonType(strVal, 'PickList');
                String temp = '';
                temp = value;
                /*if(code == 'n')//not equal to
                    operator = ' != ' + value;
                else if(code == 'e')//equal to
                    operator = ' = ' + value;
                else if(code == 's')//starts with
                    operator = ' \'%' + Originalvalue + '\'';
                else if(code == 'c')//contains
                    operator = ' Like \'%' + Originalvalue + '%\''; 
                else if(code == 'k')//does not contain
                    operator = ' Not Like \'%' + Originalvalue + '%\''; 
                else if(code == 'l')//less than
                    operator = ' <' + value; 
                else if(code == 'g')//greter than
                    operator = ' >' + value; 
                else if(code == 'm')//less or equal
                    operator = ' <=' + value; 
                else if(code == 'h')//greater or equal
                    operator = ' >=' + value; 
                else if(code == 'u')//includes
                    operator = ' Like \'%' + Originalvalue + '%\''; 
                else if(code == 'x')//excludes
                    operator = ' Like \'%' + Originalvalue + '%\''; */
                    
                if(Condition.trim().length()==0){
                    Condition = temp;
                }else{
                    Condition += ',' + temp;
                }
            }
            if(Condition.trim().length()>0){
                Condition = ' IN (' + Condition + ')';
            }
        }
        
        
        return Condition;
    }
    String getOperatorSymbol(String code, String Originalvalue, String dataType){
        code = code.trim().toLowerCase();
        String operator = '';
        if(datatype.trim().toUpperCase() == 'PICKLIST' && Originalvalue.trim().indexOf(',')>0){
            return PicklistCondition(code, OriginalValue);
        }
        String value =  setValueBasedonType(OriginalValue, dataType);
        if(code == 'n')//not equal to
            operator = ' != ' + value;
        else if(code == 'e')//equal to
            operator = ' = ' + value;
        else if(code == 's')//starts with
            operator = ' \'%' + Originalvalue + '\'';
        else if(code == 'c')//contains
            operator = ' Like \'%' + Originalvalue + '%\''; 
        else if(code == 'k')//does not contain
            operator = ' Not Like \'%' + Originalvalue + '%\''; 
        else if(code == 'l')//less than
            operator = ' <' + value; 
        else if(code == 'g')//greter than
            operator = ' >' + value; 
        else if(code == 'm')//less or equal
            operator = ' <=' + value; 
        else if(code == 'h')//greater or equal
            operator = ' >=' + value; 
        else if(code == 'u')//includes
            operator = ' Like \'%' + Originalvalue + '%\''; 
        else if(code == 'x')//excludes
            operator = ' Like \'%' + Originalvalue + '%\''; 
        
        return operator;
    }  
    Campaign_Criteria_Template__c getTemplate(){
        Campaign_Criteria_Template__c objTemplate = new Campaign_Criteria_Template__c();        
        Boolean blnLead = false;
        Boolean blnContact = false;
        if(SelectedSearch == 'LEAD'){
            blnLead = true;
        }
        if(SelectedSearch == 'CONTACT'){
            blnContact = true;
        }
        List<Campaign_Criteria_Template__c> lstTemplate = new List<Campaign_Criteria_Template__c>();
        lstTemplate = [Select Id From Campaign_Criteria_Template__c
        Where name =: templateName.trim() and Lead__c =:blnLead and Contact__c =: blnContact];
        if(lstTemplate != null && lstTemplate.size()>0){
            objTemplate = lstTemplate[0];
        }
        return objTemplate;
    }
    public void removeChild(String parentId){
        List<Campaign_Criteria_Template_Detail__c> lstChild = new List<Campaign_Criteria_Template_Detail__c>();
        lstChild = [select id from Campaign_Criteria_Template_Detail__c where Template__c =: parentId];
        if(lstChild != null && lstChild.size()>0){    
            delete lstChild;
        }
    }
    Public PageReference SaveTemplate(){
        return null;
    }
     

   
    List<ExistingMember> setListMember(List<CampaignMember> lstMember){
        List<ExistingMember> lstTemp = new List<ExistingMember>();
        if(lstMember != null && lstMember.size()>0){
            lblExistingMembers = 'Existing Members (' + String.valueOf(lstMember.size()) + ')' ;
        }
        else{
            lblExistingMembers = 'Existing Members';
        }
        if(lstMember != null && lstMember.size()>0){
            //lblExistingMembers = 'Existing Members (' + String.valueOf(lstMember.size()) + ')' ;
            for(CampaignMember mem:lstMember){
                ExistingMember existing = new ExistingMember();
                existing.memberId = mem.Id;
                existing.status = mem.status;
                existing.LastModifiedDate = mem.LastModifiedDate;
                if(mem.ContactId != null && String.ValueOf(mem.ContactId).Trim().Length()>0){//Contact
                    existing.Name = mem.Contact.Name;
                    existing.Title = mem.Contact.Title;
                    existing.Company = mem.Contact.Account.Name;
                    existing.Email = mem.Contact.Email;
                    existing.MemberType = 'CONTACT';
                    existing.contactId = mem.ContactId;
                }
                else{
                    existing.Name = mem.Lead.Name;
                    existing.Title = mem.Lead.Title;
                    existing.Company = mem.Lead.Company;
                    existing.Email = mem.Lead.Email;
                    existing.MemberType = 'LEAD';
                    existing.LeadId = mem.LeadId;
                }
                lstTemp.add(existing);
            }
        }
        return lstTemp;
    }
    public boolean blnAllMemberSelected{get;set;}
    Public PageReference selectAllMember(){
        if(blnAllMemberSelected == null)blnAllMemberSelected=true;
        if(lstExistingMember != null && lstExistingMember.size()>0){
            for(ExistingMember mem:lstExistingMember){
                mem.selected = blnAllMemberSelected;
            }
        }
        return null;
    }
    public boolean blnAllRowSelected{get;set;}
    Public PageReference selectAll(){
        if(blnAllRowSelected == null)blnAllRowSelected=true;
        if(SelectedSearch == 'LEAD')
            for(LeadResult led:lstLeadResult){
                led.selected = blnAllRowSelected;
            }
        if(SelectedSearch == 'CONTACT')
            for(ContactResult con:lstContactResult){
                con.selected = blnAllRowSelected;
            }
        return null;
    }    
////////////////////////Paging//////////////////////////
    public integer recordCount{get;set;}
    public string AssetName{get;set;}    
      
    public integer TotalCall {get;set;}
    public integer pageNumber {get;set;}
    private integer pageSize;
    public boolean nextPg {get;set;}
    public boolean previousPg {get;set;}
    public boolean isPaging {get;set;}
    public integer totalPage {get;set;}
    public integer totalRecords {get;set;}
    public integer FromRecords {get;set;}
    public integer ToRecords {get;set;}   
    
    void resetPaging(){
        system.debug('#######resetPaging called');
        blnAllMemberSelected = false;
        blnAllRowSelected = false;
        pageNumber=0;
        pageSize = 10;
        totalPage=0;
        totalRecords=0;
        FromRecords=0;
        ToRecords=0;

        nextPg = false;
        previousPg = false;
        isPaging = false;    
    }
    
public string event{get;set;}
    public PageReference NextPage()
    {
        system.debug('#######Next page called');
        //event = 'NextPage';
        if (pageNumber < totalPage ) 
            pageNumber++;
            
        if (pageNumber < totalPage) 
        {
            nextPg = false;
            if (pageNumber > 1) 
            {
                previousPg = false;
            } 
        }
        else 
        {
            nextPg = true;
            previousPg = false;
        }
        event = 'PageNumber ' + pageNumber;
        return null;
    }
    public void PreviousPage()
    {
        system.debug('#######Previous page called');
        event = 'PreviousPage';
        if (pageNumber > 0) 
        {
            pageNumber--;
        }
        if (pageNumber > 1) 
        {
            previousPg = false;
            if (pageNumber < totalPage) 
            {
                nextPg = false;
            }
        }
        else 
        {
            previousPg = true;
            nextPg = false;
        }
        //return null;
    }
    Public List<ExistingMember> lstPagingExisting{get;set;}
    Public List<ExistingMember> getExistingMember(){
        totalRecords = lstExistingMember.size();
        
        
        if (pageNumber == null || pageNumber == 0) 
        {
            pageNumber = 2;
            PreviousPage();
        }

        FromRecords = ((pageNumber - 1) * pageSize) + 1;
        ToRecords = FromRecords + pageSize -1 ;
        
        if (ToRecords>totalRecords) ToRecords = totalRecords;

        if (lstExistingMember.size() <= pageSize)
        {
            totalPage = 1;
            nextPg = true;
            previousPg = true;       
        }
        else
        {
            totalPage = Integer.valueof(lstExistingMember.size()/pageSize);
            if (Math.mod(lstExistingMember.size(), pageSize) > 0)
            {
                totalPage++;
            }
        }
        
        integer totalCountForPage = pageNumber * pageSize;
        if (lstExistingMember.size() < pageSize)
        {
            totalCountForPage = lstExistingMember.size();
        }
        lstPagingExisting = new List<ExistingMember>();
        for (integer i=((pageNumber - 1) * pageSize);i<totalCountForPage;i++)
        {
            if (i < lstExistingMember.size()) {
                ExistingMember existing = new ExistingMember();
                existing = lstExistingMember[i];
                lstPagingExisting.add(existing);
            }
        }
        
        if (totalRecords==0) FromRecords=0; 
        
        
        
        return lstPagingExisting;
    }
    
    
    Public List<ContactResult> lstPagingAddContact{get;set;}
    integer counter = 0;
    Public List<ContactResult> getContactResult(){
        if(SelectedSearch != 'CONTACT') return null;
        totalRecords = lstContactResult.size();
        if (pageNumber == null || pageNumber == 0) 
        {
            pageNumber = 2;
            PreviousPage();
        }

        FromRecords = ((pageNumber - 1) * pageSize) + 1;
        ToRecords = FromRecords + pageSize -1 ;
        
        if (ToRecords>totalRecords) ToRecords = totalRecords;

        if (lstContactResult.size() <= pageSize)
        {
            totalPage = 1;
            nextPg = true;
            previousPg = true;       
        }
        else
        {
            totalPage = Integer.valueof(lstContactResult.size()/pageSize);
            if (Math.mod(lstContactResult.size(), pageSize) > 0)
            {
                totalPage++;
            }
        }
        
        integer totalCountForPage = pageNumber * pageSize;
        if (lstContactResult.size() < pageSize)
        {
            totalCountForPage = lstContactResult.size();
        }
        //event='counter ' + string.valueof(counter++);
        lstPagingAddContact = new List<ContactResult>();
        for (integer i=((pageNumber - 1) * pageSize);i<totalCountForPage;i++)
        {
            if (i < lstContactResult.size()) {                
                
                ContactResult result = new ContactResult();
                result = lstContactResult[i];
                lstPagingAddContact.add(result);
            }
        }
        //if(lstPagingAddContact.size()>0)
        //event='--> ' + lstPagingAddContact[0].objContact.FirstName + '  ' + string.valueof(counter++);
        if (totalRecords==0) FromRecords=0; 
        system.debug('########## From Paging : ' + lstPagingAddContact);
        return lstPagingAddContact;
    }
    
    Public List<LeadResult> lstPagingAddLead{get;set;}
    Public List<LeadResult> getLeadResult(){
        if(SelectedSearch != 'LEAD') return null;
        totalRecords = lstLeadResult.size();
        
        
        if (pageNumber == null || pageNumber == 0) 
        {
            pageNumber = 2;
            PreviousPage();
        }

        FromRecords = ((pageNumber - 1) * pageSize) + 1;
        ToRecords = FromRecords + pageSize -1 ;
        
        if (ToRecords>totalRecords) ToRecords = totalRecords;

        if (lstLeadResult.size() <= pageSize)
        {
            totalPage = 1;
            nextPg = true;
            previousPg = true;       
        }
        else
        {
            totalPage = Integer.valueof(lstLeadResult.size()/pageSize);
            if (Math.mod(lstLeadResult.size(), pageSize) > 0)
            {
                totalPage++;
            }
        }
        
        integer totalCountForPage = pageNumber * pageSize;
        if (lstLeadResult.size() < pageSize)
        {
            totalCountForPage = lstLeadResult.size();
        }
        lstPagingAddLead = new List<LeadResult>();
        for (integer i=((pageNumber - 1) * pageSize);i<totalCountForPage;i++)
        {
            if (i < lstLeadResult.size()) {
                /*AssetsWrapper tempAsset = new AssetsWrapper();
                tempAsset.objAsset = results[i];
                objAssetsWrapper.add(tempAsset);*/
                LeadResult result = new LeadResult();
                result = lstLeadResult[i];
                lstPagingAddLead.add(result);
            }
        }
        
        if (totalRecords==0) FromRecords=0; 
        
        
        
        return lstPagingAddLead;
    }

//////////////////////////////////////////////////////// 

  
    
    static testMethod void TestCampaignMemberResult() {
        Campaign objCampaign = new Campaign();
        objCampaign.name = 'Test Campaign';
        objCampaign.Campaign_Name__c = 'Annual';
        objCampaign.Station__c = 'WGBH';
        
        insert objCampaign;
        
        Contact objContact = new Contact();
        objContact.FirstName = 'test first name';
        objContact.LastName = 'test last name';
        
        insert objContact;
        
       /* Select ID,Name,Lead__c,Contact__c,Field_Name__c,Parent_Object__c
        ,Parent_Object_API_Name__c,Field_Type__c from Campaign_Member_Criteria__c order
         by Parent_Object__c,Name];*/
        Campaign_Member_Criteria__c cmc = new Campaign_Member_Criteria__c();
        cmc.Contact__c = true;
        cmc.Field_Name__c = 'TestField';
        cmc.Field_Type__c = 'TestFieldType';
        cmc.Parent_Object_API_Name__c = 'TestObject';
        insert cmc;
        
        Contact objContact1 = new Contact();
        objContact1.FirstName = 'test first name1';
        objContact1.LastName = 'test last name1';
        
        insert objContact1;
        
        Lead objLead = new Lead();
        objLead.FirstName = 'test Lead first';
        objLead.LastName = 'test Lead last';
        objLead.Company = 'test lead company';
        
        insert objLead;
        
        Campaign_Criteria_Template__c objcmTemplaye = new Campaign_Criteria_Template__c();
        objcmTemplaye.Name = 'Test Template';
        objcmTemplaye.Contact__c = True;
        insert objcmTemplaye;
                  
        Campaign member = new Campaign();
        ApexPages.currentPage().getParameters().put('id',objCampaign.Id);
        ApexPages.currentPage().getParameters().put('mode','edit');
        ApexPages.StandardController controller = new ApexPages.StandardController(member);
        CampaignMemberResult clsTest = new CampaignMemberResult(controller);
        
        clsTest.IncreaseCodeCoverage();
    }
    public void IncreaseCodeCoverage() {
        String strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                                                                                                            
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';
        strTemp = 'Test';                     
    }
}