Git_WGBH_QC/src/objects/Batch_Job__c.object
<CustomObject>
    <description>This is a temporary table where email creates a record to fire a trigger which triggers a batch job</description>
    <fields>
        <fullName>Batch_Job_Name__c</fullName>
        <label>Batch Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Batch Job</label>
    <nameField>
        <displayFormat>BJ-{00000}</displayFormat>
        <label>Batch Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/classes/BatchJobs.cls
global class BatchJobs implements Database.Batchable<sObject>{
    global String query;

    global BatchJobs(){
        this.query = 'Select id, pledge_number__c From Opportunity';    	
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){       
        for(Sobject s : scope) {
        	Opportunity opp = (Opportunity) s;
            if(opp.pledge_number__c != null && opp.pledge_number__c.contains('.')) {
                opp.pledge_number__c = opp.pledge_number__c.split('\\.')[0];
            }
        }
       	update scope;  
    }

    global void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {'steven.lemmo@roundcorner.com'});
        mail.setReplyTo('steven.lemmo@roundcorner.com');
        mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process Completed');
        mail.setPlainTextBody('Batch Process has completed');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public static testMethod void testBatch() {
        Test.StartTest();
        BatchJobs batch = new BatchJobs();
        batch.query += ' LIMIT 2 ';
        ID batchprocessid = Database.executeBatch(batch);
        
        Batch_Job__c bj = new Batch_Job__c(
	        Batch_Job_Name__c = 'NoName'
	    );
	    insert bj;
        Test.StopTest();
    }
}