Git_WGBH_QC/src/objects/Bios__c.object
<CustomObject>
    <description>Object utilized for listing the various ways in which a Contact is related to the Organization and/or personal highlights that are important for profiling a person.  This object will has multiple record types and field dependencies to represent the different types of records.</description>
    <fields>
        <fullName>Program_Show__c</fullName>
        <label>Program/Show</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Interests</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bio</label>
    <nameField>
        <displayFormat>Bio-{00000000}</displayFormat>
        <label>Bio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bios</pluralLabel>
    <recordTypes>
        <fullName>Interest</fullName>
        <active>true</active>
        <label>Interest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Program__c.object
<CustomObject>
    <description>These are the programs that are showing on TV or playing on the radio.</description>
    <fields>
        <fullName>Series__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates whether the Show is a Series.</description>
        <label>Series</label>
        <type>Checkbox</type>
    </fields>
    <label>Program/Show</label>
    <nameField>
        <label>Program Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TesttrgBIOSAfterInsert.cls
@isTest
private class TesttrgBIOSAfterInsert{
    static testMethod void myTest() {       
        Program__c prg = new Program__c();
            prg.name = 'test show';
            prg.Series__c = true;
        insert prg;       
       
        List<RecordType> RecType = new List<RecordType>([select id from RecordType where DeveloperName = 'interest' and sObjectType = 'Bios__c']);
        Bios__c bio = new Bios__c();
            bio.RecordtypeId = RecType[0].Id;
            bio.Program_Show__c = prg.Id;
        insert bio;
    }
}