Git_WGBH_QC/src/objects/Campaign_Member_Report__c.object
<CustomObject>
    <fields>
        <fullName>IsProccessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Record Proccessed by Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Member Report</label>
    <nameField>
        <displayFormat>OVF-{0000}</displayFormat>
        <label>Campaign Member Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecCampainMemberReport.cls
global class BatchExecCampainMemberReport implements Database.Batchable<sObject>{
    global final String Query;

    global BatchExecCampainMemberReport(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(Query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
            
        DoBatchDataImport(scope);
    }
    
    global void DoBatchDataImport(List<sObject> scope) {
        List<Campaign_Member_Report__c> lstCampMemRpt = new List<Campaign_Member_Report__c>();
        
        for(sObject s : scope) {           
           lstCampMemRpt.add((Campaign_Member_Report__c)s);           
        }
        
        if(lstCampMemRpt.size() > 0){
            
            CampainMemberReport obj = new CampainMemberReport();
            lstCampMemRpt = obj.getCampainMember(lstCampMemRpt);
            lstCampMemRpt = obj.getclassificationsummary(lstCampMemRpt);
            lstCampMemRpt = obj.getaccountsummary(lstCampMemRpt);
            lstCampMemRpt = obj.getopportunitysummary(lstCampMemRpt);
            lstCampMemRpt = obj.getcceftaliassummary(lstCampMemRpt);
            lstCampMemRpt = obj.getbiosummary(lstCampMemRpt);
            
            for(Campaign_Member_Report__c cmr:lstCampMemRpt) {
                cmr.IsProccessed__c = true;
            }
            Update lstCampMemRpt;
        }
        

    }
    
    global void finish(Database.BatchableContext BC) {
       
       
        //System.debug('####Update Completed...');
    }

    /*static testMethod void TestBatchExecShopiniterItemGroupImport() {
       Test.startTest();

        Test.StopTest();     
    } */
}