Git_WGBH_QC/src/objects/Campaign_Criteria_Template__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Criteria Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Criteria Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Final_Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>CampaignMemberId__c</fullName>
        <label>CampaignMemberId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Final Search Result</relationshipLabel>
        <relationshipName>Final_Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Final Search Result</relationshipLabel>
        <relationshipName>Final_Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MemberStatus__c</fullName>
        <label>MemberStatus</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Search Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipName>Search_Result1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Campaign Criteria Template</label>
        <referenceTo>Campaign_Criteria_Template__c</referenceTo>
        <relationshipLabel>Final Search Result</relationshipLabel>
        <relationshipName>Final_Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Final Search Result</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Search Result #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Search Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Requested_Search__c.object
<CustomObject>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Finalize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Search</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Requested Search#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Request__c.object
<CustomObject>
    <fields>
        <fullName>Finalize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finalize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsExecuteNextBatch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsExecuteNextBatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NextBatchTime__c</fullName>
        <label>NextBatchTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Campaign_Criteria_Template__c</referenceTo>
        <relationshipLabel>Search Request</relationshipLabel>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Request</label>
    <nameField>
        <displayFormat>REQ-{0000000000}</displayFormat>
        <label>Search Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Result_Report__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Search Result Report</label>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecFinalizeSearchRequest.cls
global class BatchExecFinalizeSearchRequest implements Database.Batchable<sObject> {

    global final String Query;   
    global final ID RequestID;
    global final Boolean IsContact;
    global final ID CampaignId;
    global BatchExecFinalizeSearchRequest(String q,ID ReqID, Boolean IsCon, ID CampId){
        Query = q;
        RequestID = ReqID;
        IsContact = isCon;
        CampaignId = campId;
        system.debug('######## Query ' + Query);
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        DoBatchSearchContact(scope);
    }
    String NVL(String val){
        if(val == null){
            return '';
        }
        else{
            return val.trim();
        }
    }
    
    void DoBatchSearchContact(List<sObject> lstResult){
        try{            
            List<Final_Search_Result__c> lstFinal = new List<Final_Search_Result__c>();
            List<CampaignMember> lstMember;
            
            if(lstResult != null && lstResult.size()>0){                
                if(IsContact == true){
                    lstMember = [Select Id, ContactId, Status
                    From CampaignMember Where ContactId != null and CampaignId =: CampaignId];
                }
                else{
                    lstMember = [Select Id, LeadId, Status
                    From CampaignMember Where LeadId != null and CampaignId =: CampaignId];
                }
                for(sObject s:lstResult){
                    if(IsContact == true){
                        Contact c = new Contact();
                        CampaignMember objMember = new CampaignMember();
                        c = (Contact) s;
                        
                        Final_Search_Result__c result = new Final_Search_Result__c();
                        
                        result.Contact__c = c.Id;
                        result.CampaignMemberId__c = null;
                        result.MemberStatus__c = '';
                        result.Request__c = RequestID;
                        result.IsContact__c = true;
                        for(CampaignMember mem:lstMember){
                            if(c.Id == mem.ContactId){
                                result.CampaignMemberId__c = mem.Id;
                                result.MemberStatus__c = mem.Status;
                            }
                        }
                        lstFinal.add(result);
                    }
                    else {
                        Lead c = new Lead();
                        CampaignMember objMember = new CampaignMember();
                        c = (Lead) s;
                        
                        Final_Search_Result__c result = new Final_Search_Result__c();
                        
                        result.Lead__c = c.Id;
                        result.CampaignMemberId__c = null;
                        result.MemberStatus__c = '';
                        result.Request__c = RequestID;
                        result.IsLead__c = true;
                        for(CampaignMember mem:lstMember){
                            if(c.Id == mem.ContactId){
                                result.CampaignMemberId__c = mem.Id;
                                result.MemberStatus__c = mem.Status;
                            }
                        }
                        lstFinal.add(result);
                    }
                }
                if(lstFinal != null && lstFinal.size()>0){
                    insert lstFinal;
                }
            }
        }catch(Exception ex){
            //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        List<Search_Request__c> lstRequest = [Select CreatedBy.Email, Id, Template__r.name, IsExecuteNextBatch__c, NextBatchTime__c From Search_Request__c
        Where Id =: RequestID]; 
        Search_Result_Report__c reportURL = Search_Result_Report__c.getOrgDefaults();
        
        List<Requested_Search__c> lstPendingRequest = new List<Requested_Search__c>();        
        lstPendingRequest = [Select id From Requested_Search__c Where Status__c = 'Pending' And Request__c =:RequestID];
        
        if(lstPendingRequest.size()==0){
            
            List<Requested_Search__c> lstErrors = new List<Requested_Search__c>();        
            lstErrors = [Select id, Error_Description__c From Requested_Search__c Where Status__c = 'Error' And Request__c =:RequestID];
            
            List<String> toAddresses = new List<String>();
            //toAddresses.add('kamlesh.chauhan@roundcorner.com');
            toAddresses.add('dhaval.panchal@roundcorner.com');
            //system.debug('############# Created By ' + CreatedById);
            if(lstRequest != null && lstRequest.size()>0){
                toAddresses.add(lstRequest[0].CreatedBy.Email);
            }
            /*
            if(CreatedById != null && CreatedById != ''){
                List<User> lstUser = [Select Email From User Where Id=:CreatedById];
                if(lstUser != null && lstUser.size()>0){
                    toAddresses.add(lstUser[0].Email);
                }
            }*/
            //CampaignId
            String Body = '';
            Body += '<br/><br/>';
            if(lstRequest != null && lstRequest.size()>0){
                if(lstErrors != null && lstErrors.size()>0){
                    Body += 'Your batch has been completed with errors for Template : ' + lstRequest[0].Template__r.Name;
                }
                else{
                    Body += 'Your batch has been completed successfully for Template : ' + lstRequest[0].Template__r.Name;
                }
                Body += '<br/><br/>';
            }
            String CurrentURL = '';//ApexPages.currentPage().getHeaders().get('Host');
            String reqId = RequestID;
            if(reqId.trim().length()>15){
                reqId = reqId.substring(0,15);
            }
            //Body += 'https://c.cs0.visual.force.com/apex/CampaignMember?id=' + CampaignId + '&mode=batch&RequestID=' + RequestID;
            Body += '<br/>';
            Body += '<br/> To view Result click on below link';
            Body += '<br/>' + reportURL.Report_URL__c + reqId;
            Body += '<br/>';
            Body += '<br/> For Campaign Member click on below link';
            Body += '<br/> https://c.cs9.visual.force.com/apex/CampaignMember?id=' + CampaignId + '&mode=batch&RequestID=' + reqId;
            Body += '<br/><br/>';
            system.debug('############ to Address : ' + toAddresses);
            sendEmail(toAddresses,Body);
            /*
            if(lstRequest != null && lstRequest.size()>0){
                lstRequest[0].Status__c = 'Completed';
                lstRequest[0].Finalize__c = true;
                lstRequest[0].NextBatchTime__c = system.now().addMinutes(2);
                //lstNewRequest[0].Sub_Request__c = lstNewRequest[0].Id;                
            }
            */
        }
        /*
        else if(lstPendingRequest.size()>0){
            if(lstRequest != null && lstRequest.size()>0){
                lstRequest[0].Status__c = 'Pending';
                lstRequest[0].IsExecuteNextBatch__c = true;
                lstRequest[0].NextBatchTime__c = system.now().addMinutes(2);
                //lstNewRequest[0].Sub_Request__c = lstNewRequest[0].Id;                
            }
        }
        */
        if(lstRequest != null && lstRequest.size()>0){
            Update lstRequest;
        }
        System.debug('####Update Completed...');
    }

    void sendEmail(List<String> toAddresses, String strBody){
        Messaging.reserveSingleEmailCapacity(2);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        /*
        String DisplayName = System.Label.SenderDisplayName;
        List<OrgWideEmailAddress> lstOrg = [select id, Address, DisplayName from OrgWideEmailAddress Where DisplayName=:DisplayName];
        //setOrgWideEmailAddressId
        if(lstOrg != null && lstOrg.size()>0){
            mail.setOrgWideEmailAddressId(lstOrg[0].Id);
        }else{
            mail.setInReplyTo('wecare@sccc.co.th');
            mail.setReplyTo('wecare@sccc.co.th');
            // Specify the name used as the display name.              
            mail.setSenderDisplayName('wecare');
        }
        */
        mail.setToAddresses(toAddresses);
        //mail.setSubject('Birthday notification on ' + system.today().format());
        mail.setSubject('Campaign Member Status');
        mail.setUseSignature(false);
        mail.setPlainTextBody('Campaign Member Status');
        mail.setHtmlBody(strBody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });    
    }    
}