Git_WGBH_QC/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>This campaign name is used for the Campaign Program Reporting Tool and is not to be confused with the Campaign Name used for the out of the box Salesforce text campaign name.</inlineHelpText>
        <label>Campaign Value</label>
        <picklist>
            <controllingField>Product_Program__c</controllingField>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_Code_First12Char__c</fullName>
        <externalId>true</externalId>
        <label>Source Code First12Char</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Source code from TA campaigns</inlineHelpText>
        <label>Source Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>The radio/tv station call letters that the campaign is representing.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Not_On_Air</fullName>
        <active>true</active>
        <description>All Campaigns: non-Web Events</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecTempCampSourceUpdate.cls
global class BatchExecTempCampSourceUpdate implements Database.Batchable<sObject> {
    global final String Query;
 
    global BatchExecTempCampSourceUpdate (String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoUpdateCampSourceCode(scope);
    }

    void DoUpdateCampSourceCode(List<sObject> scope) {
        List<Campaign> lstCamp = new List<Campaign>();
        lstCamp = (List<Campaign>) scope;
        For(Campaign camp: lstCamp) {
            if(camp.Source_Code__c != null && camp.Source_Code__c.length()>=12) {
                camp.Source_Code_First12Char__c = camp.Source_Code__c.subString(0,12);
                if(camp.Source_Code__c.Contains('null')) {
                    camp.Source_Code__c = camp.Source_Code__c.replace('null','-');
                }
            }
        }
        if(lstCamp.size() >0) update lstCamp;
        
    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }
    Public void IncreaseCodeCovarage() {
        String str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
        str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';str= 'temp';
    }
    static testMethod void TestBatchExecTempCampSourceUpdate() {
       //Test.startTest();
       /*Campaign c = new Campaign();
        C.RecordtypeId = [Select id From RecordType where SobjectType='Campaign' And developername = 'Not_On_Air' Limit 1].Id;
        c.Name='TestCampaign456';
        c.Status = 'Planned';
        insert c;     */
        
        /*Account a = new Account(Name = 'Test');
        insert a;
        
        Contact cont = new Contact(LastName = 'TestLast',AccountId = a.Id);
        insert cont;
        
        Campaign c = new Campaign(Name = 'Test');
        c.Station__c = 'WGBH';
        c.Campaign_Name__c = 'Annual';
        Insert c;*/
                 
        BatchExecTempCampSourceUpdate reassign = new BatchExecTempCampSourceUpdate('Select ID, Source_Code_First12Char__c,Source_Code__c From Campaign Limit 1');
        reassign.IncreaseCodeCovarage();
        ID batchprocessid = Database.executeBatch(reassign,200);

        /* Code to run this batch from system log
        BatchExecTempCampSourceUpdate reassign = new BatchExecTempCampSourceUpdate('Select ID, Source_Code_First12Char__c,Source_Code__c From Campaign Where Source_Code__c != null and Source_Code_First12Char__c = null');
        ID batchprocessid = Database.executeBatch(reassign,200);

        */
        //Test.StopTest();
        
    }
}