Git_WGBH_QC/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Campaign Type; Annual, Capital, Auction, Event (this is the 2nd value in the source code i.e. HAM = WGBH, Annual, Major Gift</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Arts &amp; Drama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celtic &amp; Folk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classical Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jazz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kids &amp; Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lectures &amp; Screenings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museums &amp; Tours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theater &amp; Dance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Time_Date__c</fullName>
        <inlineHelpText>End date and time of the campaign</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Logo__c</fullName>
        <inlineHelpText>Insert the image or the event url by clicking into the image</inlineHelpText>
        <label>Event Image</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Url__c</fullName>
        <label>Event Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location_Latitude__c</fullName>
        <label>Location Latitude</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Longitude__c</fullName>
        <label>Location Longitude</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Capacity__c</fullName>
        <label>Maximum Capacity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Benefit_Discount_Logo__c</fullName>
        <label>Member Benefit Discount Logo</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Start_Time_Date__c</fullName>
        <inlineHelpText>Start Date and Time of the Overall Program</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject_Title__c</fullName>
        <label>Subject/Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_Information__c</fullName>
        <label>Ticket Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ticket_Url__c</fullName>
        <label>Ticket Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Venue_Name__c</fullName>
        <label>Venue Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postalcode__c</fullName>
        <label>Zip/Postalcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/classes/TestOnlineEventDetailWs.cls
@isTest
Private class TestOnlineEventDetailWs
{ 
        
     static testMethod void getEventByIdTest() 
    {
       string tag = 'abcd';
       string value = 'xyz';
       OnlineEventDetailWs.OnlineEventDetailWs_Result oedres = new OnlineEventDetailWs.OnlineEventDetailWs_Result();  
       String eventName = 'BRW: Test Campaign';
       Campaign testCampaign = new Campaign(
                           Name = 'BRW: Campaign 1', 
                           StartDate = date.parse('01/22/2005'), 
                           EndDate = date.parse('01/21/2006'), 
                           Subject_title__c = 'BRW: Test Campaign',
                           active__c = true
                           );
        
        insert testCampaign;
        
        String eventId = testCampaign.id;

        Campaign selectedCampaign = [SELECT id,description, Event_logo__c, Subject_title__c, Event_Url__c, Start_time_date__c, End_time_date__c,
                                        Ticket_Url__c, Ticket_information__c, Venue_name__c, street_address__c, city__c,Maximum_Capacity__c, Location_Latitude__c, Location_Longitude__c, 
                                        State_province__c, Zip_postalcode__c, Phone__c, Email__c, name__c, Member_Benefit_Discount_Logo__c 
                                        FROM Campaign where active__c=True AND id = :eventId];
        
        System.assertNotEquals(selectedCampaign, null);
        System.assertEquals(selectedCampaign.id, eventId);
        //OnlineEventDetailWs oedws = new OnlineEventDetailWs();
        OnlineEventDetailWs.getEventById(eventId);   
       // OnlineEventDetailWs.createElement(tag,value);                           
        //OnlineEventDetailWs.OnlineEventDetailWs_Result.createElement('test','test');
    }
    
    static testMethod void getEventByCriteriaTest()
    {
        OnlineEventDetailWs.OnlineEventDetailWs_Result oedres = new OnlineEventDetailWs.OnlineEventDetailWs_Result();
        String subject = 'BRW: Test Campaign 2';
        String city    = 'Boston';
        String genre   = 'Test Genre';
        String topic   = 'Test Topic';
        String startDateAndTime = '2010-01-20 18:00:00';//1/20/2011 6:00 PM';
        String endDateAndTime   = '2010-01-22 09:00:00'; //'1/22/2011 9:00 AM';
        boolean feature=true;
        //The String should use the standard date format “yyyy-MM-dd HH:mm:ss” in the local time zone. 
        Campaign testCampaign = new Campaign(
                           Name = 'BRW: Campaign 2',
                           Start_time_date__c =  Datetime.valueOf(startDateAndTime),
                           End_time_date__c = Datetime.valueOf(endDateAndTime),
                           Subject_title__c = subject,
                           Type = topic,
                           city__c = city,
                           Category__c = genre
                           );
        
        insert testCampaign;
        
        String eventId = testCampaign.id;
        
        String queryString = 'SELECT id, description, type, Category__c, Event_logo__c, Subject_title__c, Event_Url__c,'
                                   + 'Start_time_date__c, End_time_date__c, Ticket_Url__c,'
                                   + 'Ticket_information__c, Venue_name__c, street_address__c,'
                                   + 'city__c,Maximum_Capacity__c, Location_Latitude__c, Location_Longitude__c,'
                                   + 'State_province__c, Zip_postalcode__c, Phone__c, Email__c, name__c,'
                                   + 'Member_Benefit_Discount_Logo__c FROM Campaign  ';
                                   
       if ( subject != null && subject.length() > 0 )
       {
            queryString += ' AND Subject_Title__c = \'' + subject + '\'';
       }
       
       if ( topic != null && topic.length() > 0 )
       {
            queryString += ' AND Type = \'' + topic + '\'';
       }
       
       if ( city != null && city.length() > 0 )
       {
            queryString += ' AND City__c = \'' + city + '\'';
       }
       
       if ( genre != null && genre.length() > 0 )
       {
            queryString += ' AND Category__c = \'' + genre + '\'';
       }
        
       if ( startDateAndTime != null && startDateAndTime.length() > 0 )
       {
           //lastRun.lastRun__c.format('yyyy-MM-dd\'T\'HH:mm:ss')
            //Datetime stDateTime = getConvertDateTime(startDateAndTime);
            queryString += ' AND Start_Time_Date__c = ' + startDateAndTime + '';
       }
        
       if ( endDateAndTime != null && endDateAndTime.length() > 0 )
       {
            //DateTime endDateTime = getConvertDateTime(endDateAndTime);
            queryString += ' AND End_Time_Date__c = ' + endDateAndTime + '';
       }
        
        try 
        {
            List<Campaign> resultSet = Database.query(queryString);
            for(Campaign ca:resultSet)
            {
                System.assertEquals( ca.Subject_title__c, subject );
                System.assertEquals( ca.id, eventId );
                System.assertEquals( ca.type, topic );
                System.assertEquals( ca.Category__c, genre );
            }
        }
        catch (Exception ex)
        {
            System.debug(queryString);
        }
        OnlineEventDetailWs.getEventsByCriteria(subject,city,genre,topic,startDateAndTime,endDateAndTime,feature);
        OnlineEventDetailWs.getEvents();
    }
}