Git_WGBH_QC/src/objects/Campaign_Member_Report__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Contact__r.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Id__c</fullName>
        <label>Campaign Member Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Reports</relationshipLabel>
        <relationshipName>Campaign_Member_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Member Reports</relationshipLabel>
        <relationshipName>Campaign_Member_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsProccessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Record Proccessed by Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Member Report</label>
    <nameField>
        <displayFormat>OVF-{0000}</displayFormat>
        <label>Campaign Member Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/testBatchExecCampainMemberReport.cls
@istest
private  class testBatchExecCampainMemberReport
{
    static testMethod void testBatchExecCampainMemberReport()
    {
     Test.startTest();
     BatchExecCampainMemberReport reassign = new BatchExecCampainMemberReport('select id,Campaign_Member_Id__c,Contact__r.Account.id,Account_Id__c,Campaign__c,Contact__c from Campaign_Member_Report__c where IsProccessed__c = false  limit 1');
     ID batchprocessid = Database.executeBatch(reassign,1);
     
     Test.StopTest();     
    }
}