Git_WGBH_QC/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <inlineHelpText>Each individual contact is associated with a Household which lists information for the whole family.</inlineHelpText>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Description__c</fullName>
        <description>Description Name on a Program</description>
        <inlineHelpText>If the case is in reference to a program, search and select the applicable program.  One program may be selected per case.</inlineHelpText>
        <label>Program Description</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Cases (Program Description)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>If the case is in reference to a program, search and select the applicable program.  One program may be selected per case.</inlineHelpText>
        <label>TV/Radio Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>Specific station in which the case is in reference to. WGBH should be selected for non station-specific requests.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WGBH</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH News Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBH Classical Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>contact_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Contact Date</description>
        <inlineHelpText>Date case is opened, date of first contact.</inlineHelpText>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>program_code__c</fullName>
        <description>Program</description>
        <label>Program</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_interactions_Id__c</fullName>
        <description>TA Interactions external Id</description>
        <externalId>true</externalId>
        <label>TA Interactions Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Household__c.object
<CustomObject>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Program__c.object
<CustomObject>
    <description>These are the programs that are showing on TV or playing on the radio.</description>
    <fields>
        <fullName>program_description__c</fullName>
        <description>Program Description</description>
        <inlineHelpText>Program Description</inlineHelpText>
        <label>Program Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_program_id__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Program Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program/Show</label>
    <nameField>
        <label>Program Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchCaseProgramLink.cls
global class BatchCaseProgramLink implements Database.Batchable<sObject> {
    global String query;
    global Boolean chainFlag = false;
    
    global BatchCaseProgramLink(){
    	// original - 'WHERE ta_interactions_Id__c != null and program_code__c != null and Program__c = null';
        this.query = 
        	'Select id, ta_interactions_Id__c, program_code__c, Program__c, batch_process_count__c ' + 
        	'From Case ' +
        	'WHERE batch_process_count__c = 1';
    }
    global BatchCaseProgramLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }    

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Case c = (Case) s;
            //Batch condition.
            if(c.ta_interactions_Id__c != null && c.program_code__c != null && c.Program__c == null) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	c.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }        

    global void execute(List<sObject> scope){
    	List<Case> cases = (List<Case>)scope;
        List<String> programCodes = new List<String>();    	 	  	    	
        for(Case cas : cases) {
        	programCodes.add(cas.program_code__c);
        }
            	
        List<Program__c> programs = [SELECT id, ta_program_id__c FROM Program__c WHERE ta_program_id__c IN :programCodes];
        Map<String, ID> programMap = new Map<String, ID>();
        for(Program__c program : programs) {
            programMap.put(program.ta_program_id__c,program.Id);
        }
        
        for(Sobject s : scope){
            Case cas = (Case) s;        	
        	cas.Program__c = programMap.get(cas.program_code__c);
        	cas.batch_process_count__c--;
        }
        
        update scope;
    }
    
    public static testMethod void testBatch() {
    	Program__c p = new Program__c(Name='Hoops',ta_program_id__c='HOOPSTER', program_description__c='Basketball Show');
    	insert p;
    	
    	Case case1 = new Case(
    	   Origin='Email',
    	   Station__c='WGBH',
    	   Type='Jazz',
    	   Status='Open',
    	   program_code__c = 'HOOPSTER',
    	   contact_date__c=System.today(),
    	   ta_interactions_id__c = '12345_00_I_SO_ED',
    	   bulk_load__c = true,
    	   batch_process_count__c = 1
    	);   	
    	insert case1;     	    	  	 	
        
        Test.StartTest();
		BatchCaseProgramLink batch = new BatchCaseProgramLink();
		batch.query += ' AND ta_interactions_Id__c IN (\'12345_00_I_SO_ED\') LIMIT 10 ';
		ID batchprocessid = Database.executeBatch(batch);
		Test.StopTest();
		
		Case tcase1 = [SELECT ContactId, Household__c, Program__c, AccountId FROM Case WHERE ta_interactions_Id__c = :case1.ta_interactions_Id__c][0];
		System.Assert(case1.id == tcase1.id);
		System.Assert(tcase1.Program__c!=null);					
    }
    
    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchCaseProgramLink',chainFlag);
    }
}