Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <description>The merchant account</description>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Giving_Amount__c</fullName>
        <label>Giving Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation_Opportunity__c</fullName>
        <label>Parent Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Giving Installments</relationshipLabel>
        <relationshipName>Giving_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Giving Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>gift_kind__c</fullName>
        <label>Gift Kind</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustaining Gift</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>installment_amount__c</fullName>
        <description>Installment Amount</description>
        <inlineHelpText>Installment Amount</inlineHelpText>
        <label>Installment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO American Express DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Discover DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Master Card DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Visa DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Payment (Complimentary)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>schedule_start_date__c</fullName>
        <description>Schedule Start Date</description>
        <inlineHelpText>Schedule Start Date</inlineHelpText>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <formula>if( ISPICKVAL(Transaction_Type__c ,&apos;PAYMENT&apos;),HYPERLINK(&quot;/&quot;&amp;Giving_Id__r.CC_EFT_Alias__c, Giving_Id__r.CC_EFT_Alias__r.Name),
HYPERLINK(&quot;/&quot;&amp; Refund__r.CC_Alias__c, Refund__r.CC_Alias__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CC &amp; EFT Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EFT_ORIGINATOR_ID__c</fullName>
        <label>EFT ORIGINATOR ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Case ( Giving_Id__r.payment_method__c, &quot;Charge Card&quot;,&quot;Charge Card&quot;,
&quot;Electronic Funds Transfer&quot;, &quot;Electronic Funds Transfer&quot;,&quot;&quot;)</formula>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date__c</fullName>
        <formula>Giving_Id__r.schedule_start_date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/Transaction_Batch.cls
global class Transaction_Batch {
    Public static void Transaction_Batch() {
        String Query = '';
        
        Query += 'Select ID,Payment_Date__c,Payment_Amount__c,SFDC_GIVING_NUMBER__c,CC_EFT_Alias__r.GUID__c,';
        Query += ' CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c, CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c , AccountId , ';
        Query += ' installment_amount__c , Giving_Amount__c , payment_method__c , Recurring_Donation_Opportunity__c, ';
        Query += ' CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.GUID__c, ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c , ';
      
        Query += ' CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c, CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c ,CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c , ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c , ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c ';
   
        Query += ' from Opportunity Where ';
        Query += ' Status__c = \'PROCESS\' AND ';
        Query += ' StageName = \'Pledged\' AND ';
        Query += ' TRANSACTION_BATCH__c = null AND ' ;
        Query += ' (payment_method__c =\'Charge Card\' or payment_method__c = \'Electronic Funds Transfer\') AND ';
        Query += ' schedule_start_date__c <= Today AND ';
        //Query += ' (Gift_Kind__c = \'One Payment\' or Recurring_Donation_Opportunity__c != null)';
        Query += ' ((Gift_Kind__c = \'One Payment\' And Giving_Amount__c != null And Giving_Amount__c >0 ) Or (Recurring_Donation_Opportunity__c != null And installment_amount__c != null  And installment_amount__c >0))';
       
        if(Test.IsRunningTest()) {
            Query += ' limit 1';
        }

        if(!Test.IsRunningTest()) {
        
            BatchExecTransaction_Batch reassign = new BatchExecTransaction_Batch(Query);
            ID batchprocessid = Database.executeBatch(reassign,200);
        }
    }

    Public static void Transaction_Batch_SingleRecord(String TransID) {
        String Query = '';
        
        Query += 'Select ID,Payment_Date__c,Payment_Amount__c,SFDC_GIVING_NUMBER__c,CC_EFT_Alias__r.GUID__c,';
        Query += ' CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c, CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c , AccountId , ';
        Query += ' installment_amount__c , Giving_Amount__c , payment_method__c , ';
        Query += ' CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.GUID__c, ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c , ';
      
        Query += ' CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c, CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c ,CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c , ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c , ';
        Query += ' Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c ';
   
        Query += ' from Opportunity Where ';
        Query += ' Status__c = \'PROCESS\' AND ';
        Query += ' StageName = \'Pledged\' AND ';
        Query += ' TRANSACTION_BATCH__c = null AND ' ;
        Query += ' (payment_method__c =\'Charge Card\' or payment_method__c = \'Electronic Funds Transfer\') AND ';
        Query += ' schedule_start_date__c <= Today AND ';
        //Query += ' (Gift_Kind__c = \'One Payment\' or Recurring_Donation_Opportunity__c != null)';
        Query += ' ((Gift_Kind__c = \'One Payment\' And Giving_Amount__c != null And Giving_Amount__c >0 ) Or (Recurring_Donation_Opportunity__c != null And installment_amount__c != null  And installment_amount__c >0))';

        if(TransID!=null && TransID!='') Query += ' and ID=\'' + TransID + '\'';
        
        if(Test.IsRunningTest()) {
            Query += ' limit 1';
        }

        if(!Test.IsRunningTest()) {
        
            BatchExecTransaction_Batch reassign = new BatchExecTransaction_Batch(Query);
            ID batchprocessid = Database.executeBatch(reassign,200);
        }
    }
    
    static testMethod void  TestTransaction_Batch() {
      
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 20;                
        insert o1;
        
        Test.startTest();
        Transaction_Batch.Transaction_Batch();
        Test.StopTest();     
        
    }
}