Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <description>The merchant account</description>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Giving_Amount__c</fullName>
        <label>Giving Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation_Opportunity__c</fullName>
        <label>Parent Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Giving Installments</relationshipLabel>
        <relationshipName>Giving_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Giving Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>installment_amount__c</fullName>
        <description>Installment Amount</description>
        <inlineHelpText>Installment Amount</inlineHelpText>
        <label>Installment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO American Express DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Discover DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Master Card DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONVIO Visa DO NOT SELECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Payment (Complimentary)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transaction_type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <formula>if( ISPICKVAL(Transaction_Type__c ,&apos;PAYMENT&apos;),HYPERLINK(&quot;/&quot;&amp;Giving_Id__r.CC_EFT_Alias__c, Giving_Id__r.CC_EFT_Alias__r.Name),
HYPERLINK(&quot;/&quot;&amp; Refund__r.CC_Alias__c, Refund__r.CC_Alias__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CC &amp; EFT Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EFT_ORIGINATOR_ID__c</fullName>
        <label>EFT ORIGINATOR ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giving_Id__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Case ( Giving_Id__r.payment_method__c, &quot;Charge Card&quot;,&quot;Charge Card&quot;,
&quot;Electronic Funds Transfer&quot;, &quot;Electronic Funds Transfer&quot;,&quot;&quot;)</formula>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pledge_Number__c</fullName>
        <description>The pledge number from the pledge</description>
        <label>Pledge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecTransaction_Batch.cls
global class BatchExecTransaction_Batch implements Database.Batchable<sObject> {
    global final String Query;
 
    global BatchExecTransaction_Batch(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        if(!Test.IsRunningTest()) DoBatchTransactionbatchInsert(scope);
    }
    
    void DoBatchTransactionbatchInsert(List<sObject> scope) {
        List<Transaction_Batch__c> lstbatch = new List<Transaction_Batch__c>();
        
        Transaction_Batch__c TB;
        Set<Id> soppIds = new Set<Id>();
        for(sObject s : scope) {
            Opportunity ObjPledge = (Opportunity)s;
            TB = new Transaction_Batch__c();
            System.debug('pledgeid: '+ ObjPledge.Id );

            TB.Account__c = ObjPledge.AccountId;
            TB.Process_date__c = ObjPledge.Payment_Date__c;           
                       
            If(ObjPledge.Recurring_Donation_Opportunity__c != null) {
                if(ObjPledge.installment_amount__c != null && ObjPledge.installment_amount__c >0){
                   TB.Payment_Amount__c = ObjPledge.installment_amount__c;
                } else {
                    return;
                }
            } else {
               TB.Payment_Amount__c = ObjPledge.Giving_Amount__c;
            }
            TB.Pledge_Number__c = ObjPledge.SFDC_GIVING_NUMBER__c;
            TB.Giving_Id__c = ObjPledge.Id;
            if(ObjPledge.CC_EFT_Alias__c == null && ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__c != null) {
                TB.GUID__c = ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.GUID__c;
                if(ObjPledge.Payment_Method__c == 'Electronic Funds Transfer') {
                    TB.Merchant_ID__c = ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c;
                    TB.Merchant_Key__c =  ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c;
                    TB.EFT_ORIGINATOR_ID__c =  ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c;
                } else {
                    TB.Merchant_ID__c = ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c;
                    TB.Merchant_Key__c =  ObjPledge.Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c;
                }
            } else {
                TB.GUID__c = ObjPledge.CC_EFT_Alias__r.GUID__c;
                if(ObjPledge.Payment_Method__c == 'Electronic Funds Transfer') {
                    TB.Merchant_ID__c = ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_ID__c;
                    TB.Merchant_Key__c =  ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.EFT_Merchant_Key__c;
                    TB.EFT_ORIGINATOR_ID__c =  ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.EFT_ORIGINATOR_ID__c;
                } else {                
                    TB.Merchant_ID__c = ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c;
                    TB.Merchant_Key__c =  ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c;
                }
            }
            TB.Transaction_Type__c = 'PAYMENT';
            TB.Status__c = 'PROCESS';
            lstbatch.add(TB);
            soppIds.Add(ObjPledge.Id);
            
        }
        
        if(lstbatch != null && lstbatch.size()>0) 
        {
            Insert lstbatch;
            Map<Id,Opportunity> mapOpp = new Map<Id,Opportunity>([Select id,Transaction_batch__c,CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__c From Opportunity Where Id In:soppIds]);
            if(mapOpp.size() > 0) {
                for(Transaction_batch__c objtb:lstbatch) {
                    if(mapOpp.ContainsKey(objtb.Giving_Id__c) == true) {
                        mapOpp.get(objtb.Giving_Id__c).Transaction_batch__c = objtb.Id;
                        if(mapOpp.get(objtb.Giving_Id__c).CC_EFT_Alias__c == null) {
                           mapOpp.get(objtb.Giving_Id__c).CC_EFT_Alias__c = mapOpp.get(objtb.Giving_Id__c).Recurring_Donation_Opportunity__r.CC_EFT_Alias__c;
                        }
                    }
                }
                Update mapOpp.Values();
            }
        }

    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

   static testMethod void TestBatchExecTransaction_Batch() {
       Test.startTest();
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 16;                
        insert o1;
        
       
        BatchExecTransaction_Batch reassign = new BatchExecTransaction_Batch ('Select Id,Payment_Date__c,SFDC_GIVING_NUMBER__c,CC_EFT_Alias__r.GUID__c,Payment_Amount__c,CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c,CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c,AccountId, installment_amount__c , Giving_Amount__c ,CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__c, Recurring_Donation_Opportunity__r.CC_EFT_Alias__r.GUID__c from Opportunity Where Payment_Date__c = Today Limit 2');
        ID batchprocessid = Database.executeBatch(reassign,2);
 
        Test.StopTest();     
        
    }
}