Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <description>The merchant account</description>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Giving Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>gift_kind__c</fullName>
        <label>Gift Kind</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustaining Gift</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transaction_type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Giving__r.AccountId , Giving__r.Account.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Alias__c</fullName>
        <label>CC Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Giving__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Refund_Date__c</fullName>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Refund #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giving_Id__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pledge_Number__c</fullName>
        <description>The pledge number from the pledge</description>
        <label>Pledge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecBatch_Transactions.cls
global class BatchExecBatch_Transactions implements Database.Batchable<sObject> {
    global final String Query;
 
    global BatchExecBatch_Transactions(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchTransactionsInsert(scope);
    }
    
    void DoBatchTransactionsInsert(List<sObject> scope) {
        List<Transaction_Batch__c> lstbatch = new List<Transaction_Batch__c>();
        
        Transaction_Batch__c TB;
        Set<Id> sRefundIds = new Set<Id>();
        for(sObject s : scope) {
            Refund__c ObjPledge = (Refund__c)s;
            TB = new Transaction_Batch__c();
            TB.Account__c =  ObjPledge.Giving__r.Accountid;
            TB.Refund__c = ObjPledge.Id;
            TB.Process_date__c = ObjPledge.Refund_Date__c;
            TB.GUID__c = ObjPledge.CC_Alias__r.GUID__c;
            TB.Payment_Amount__c = ObjPledge.Refund_Amount__c;
            TB.Pledge_Number__c = ObjPledge.Giving__r.SFDC_GIVING_NUMBER__c;
            TB.Merchant_ID__c = ObjPledge.CC_Alias__r.Merchant_Account__r.Merchant_ID__c;
            TB.Merchant_Key__c =  ObjPledge.CC_Alias__r.Merchant_Account__r.Merchant_Key__c;
            TB.Giving_Id__c = ObjPledge.Giving__c;            
            TB.Transaction_Type__c = 'REFUND';
            TB.Status__c = 'PROCESS';
            lstbatch.add(TB);
            sRefundIds.Add(ObjPledge.Id);
        }
        
        if(lstbatch != null && lstbatch.size()>0) 
        {
            Insert lstbatch;
            
            Map<Id,Refund__c> mapRef = new Map<Id,Refund__c>([Select id,Transaction_batch__c From Refund__c Where Id In: sRefundIds]);
            if(mapRef.size() > 0) {
                for(Transaction_batch__c objtb:lstbatch) {
                    if(mapRef.ContainsKey(objtb.Refund__c) == true) {
                        mapRef.get(objtb.Refund__c).Transaction_batch__c = objtb.Id;
                    }
                }
                Update mapRef.Values();
            }
        }

    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }
    
   static testMethod void TestBatchExecBatch_Transactions() {
       Test.startTest();
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 150;
        o.Gift_Kind__c='One Payment';
        insert o;
        
        Refund__c rf = new Refund__c();
        rf.Refund_Amount__c = 15;
        rf.Refund_Date__c = system.today().addDays(10);
        rf.Giving__c = o.Id;
        insert rf;
        
        //Opportunity o1 = new Opportunity();
        //o1.Refund_Amount__c = 100;
        //o1.Refund_Date__c = system.today().addDays(10);
                     
        //insert o1;
        
       
        BatchExecBatch_Transactions reassign = new BatchExecBatch_Transactions ('Select ID,Refund_Date__c,CC_Alias__r.GUID__c,Refund_Amount__c,Giving__r.SFDC_GIVING_NUMBER__c,CC_Alias__r.Merchant_Account__r.Merchant_ID__c,CC_Alias__r.Merchant_Account__r.Merchant_Key__c,Giving__c,Giving__r.AccountID from Refund__c where ID=\'' + rf.id + '\'');
        ID batchprocessid = Database.executeBatch(reassign,2);
 
        Test.StopTest();     
        
    }
   
}