Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giving_Id__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UpdateCCDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdateCCDate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isCCDateExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto set Checked when Charge Card Date expired.</description>
        <inlineHelpText>Auto set Checked when Charge Card Date expired.Do not change this Fields.</inlineHelpText>
        <label>isCCDateExpired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>needToRePaymentReq__c</fullName>
        <defaultValue>false</defaultValue>
        <label>needToRePaymentReq</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecExtendCCDate_Batch.cls
global class BatchExecExtendCCDate_Batch implements Database.Batchable<sObject>,Database.AllowsCallouts {
    global final String Query;
 
    global BatchExecExtendCCDate_Batch(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoExtendCCdate(scope);
    }

    void DoExtendCCdate(List<sObject> scope) {
        Transaction_Batch__c ObjTrasBatch = (Transaction_Batch__c)scope[0];
        SageTransactionProcess.UpdateExpireDateAndRePayment(ObjTrasBatch.id);

    }  

    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }
    
     static testMethod void TestBatchExecExtendCCDate_Batch() {
       Test.startTest();
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 16;                
        insert o1;
        
        CC_Alias__c objcca = new CC_Alias__c ();
        objcca.GUID__c = 'test';
        insert objcca;
        
        Transaction_Batch__c tb = new Transaction_Batch__c();
        tb.Giving_Id__c = o1.Id;
        tb.Merchant_Id__c = o1.Id;
        tb.Merchant_Key__c = '66776666';
        tb.GUID__c = 'test';
        tb.UpdateCCDate__c = false;
        tb.needToRePaymentReq__c = false;
        tb.isCCDateExpired__c  = true;
        insert tb;        
        
        String query='SELECT  Id FROM transaction_batch__c Where UpdateCCDate__c = false and needToRePaymentReq__c = false And isCCDateExpired__c  = true';
        BatchExecExtendCCDate_Batch reassign = new BatchExecExtendCCDate_Batch (query);
       
        ID batchprocessid = Database.executeBatch(reassign,1);
 
        Test.StopTest();     
        
    }
}