Git_WGBH_QC/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <description>The merchant account</description>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <externalId>true</externalId>
        <label>Merchant ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <externalId>true</externalId>
        <label>Merchant Key</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRANSACTION_BATCH__c</fullName>
        <label>TRANSACTION BATCH</label>
        <referenceTo>TRANSACTION_BATCH__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>transaction_type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <formula>if( ISPICKVAL(Transaction_Type__c ,&apos;PAYMENT&apos;),HYPERLINK(&quot;/&quot;&amp;Giving_Id__r.CC_EFT_Alias__c, Giving_Id__r.CC_EFT_Alias__r.Name),
HYPERLINK(&quot;/&quot;&amp; Refund__r.CC_Alias__c, Refund__r.CC_Alias__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CC &amp; EFT Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giving_Id__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/testtrgUpdate_CCAlias_Transaction_Batch.cls
@IsTest
Public class testtrgUpdate_CCAlias_Transaction_Batch{

    public static testmethod void testtrgUpdate_CCAlias_Transaction_Batch()
    {
        Merchant_Accounts__c merchant = new Merchant_Accounts__c();
        merchant.Name='test';
        merchant.Merchant_ID__c='123456';
        merchant.Merchant_Key__c='123456';
        insert merchant;
        CC_Alias__c ccalias = new CC_Alias__c();
        ccalias.Merchant_Account__c=merchant.id;
        insert ccalias;
        Account acc= new Account(name='test');
        insert acc;

        Opportunity opp =new Opportunity ();
        opp.name='test';
        opp.accountid=acc.id;
        opp.stagename='tset';
        opp.CloseDate=system.today();
        //opp.CC_EFT_Alias__c=ccalias.id;
        
        insert opp;
        TRANSACTION_BATCH__c trans = new TRANSACTION_BATCH__c();
        trans.Transaction_Type__c='PAYMENT';
        trans.Status__c='FAIL';
        trans.Giving_id__c=opp.id;
        insert trans;        
        opp.CC_EFT_Alias__c=ccalias.id;
        update opp;
    }
    public static testmethod void testtrgUpdateGUID_Merchant_TransactionBatch()
    {
        Merchant_Accounts__c merchant = new Merchant_Accounts__c();
        merchant.Name='test';
        merchant.Merchant_ID__c='123456';
        merchant.Merchant_Key__c='123456';
        insert merchant;
        CC_Alias__c ccalias = new CC_Alias__c();
        //ccalias.Merchant_Account__c=merchant.id;
        insert ccalias;
        Account acc= new Account(name='test');
        insert acc;

        Opportunity opp =new Opportunity ();
        opp.name='test';
        opp.accountid=acc.id;
        opp.stagename='tset';
        opp.CloseDate=system.today();
        opp.CC_EFT_Alias__c=ccalias.id;
        
        insert opp;
        TRANSACTION_BATCH__c trans = new TRANSACTION_BATCH__c();
        trans.Transaction_Type__c='PAYMENT';
        trans.Status__c='FAIL';
        trans.Giving_id__c=opp.id;
        insert trans;        
        ccalias.Merchant_Account__c=merchant.id;
        update ccalias;
    }
    
}