Git_WGBH_QC/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Classification_Type__c</fullName>
        <description>Equates to the Record Type</description>
        <inlineHelpText>Select a classification type</inlineHelpText>
        <label>Classification Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appeal Preferences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Preferences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Preferences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Tagging &amp; Scores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Station Boards and Committees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Station Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey and Event Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer Preferences</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>Please select a station to relate to the classification or preference regarding the station.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>WGBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Stations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy of Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TesttrgClassificationAfterInsert.cls
@isTest
Private Class TesttrgClassificationAfterInsert {

    Public static testmethod void TestTrgClassification() {
        Test.startTest();
        List<RecordType> lstRecType = new List<RecordType>([select ID,Name,DeveloperName from RecordType where SobjectType= 'Classification__c']);
        if(lstRecType.size()>0) {
            
            list<Classification__c> lst = new  List<Classification__c>();
            for(RecordType rt:lstRecType) {
                Classification__c clsf = new Classification__c();
                clsf.RecordtypeId = rt.Id;
                clsf.Station__c = 'WGBH';
                clsf.start_date__c = system.Today();
                clsf.Classification_Type__c = rt.Name;
                lst.add(clsf);
            }
            if(lst.size()>0) {
                Insert lst;
            }
        }
        Test.StopTest();
    }
}