Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Salutation__c.object
<CustomObject>
    <description>TA Salutation</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Salutations</relationshipLabel>
        <relationshipName>Salutations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inside_salutation_1__c</fullName>
        <description>Inside Salutation 1</description>
        <inlineHelpText>This is the information that appears after the word Dear on the letter sent to the donor</inlineHelpText>
        <label>Inside Salutation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>salutation_code__c</fullName>
        <description>Salutation Code</description>
        <inlineHelpText>Salutation Code</inlineHelpText>
        <label>Salutation Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>salutation_line_1__c</fullName>
        <description>Salutation Line 1</description>
        <inlineHelpText>The first line of the address label when printing an envelope
Mr John Smith
Mrs Wilma Smith
1234 Main Street
Anytown, USA 11111</inlineHelpText>
        <label>Salutation Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Salutation</label>
    <nameField>
        <label>Salutation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salutations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/TA_Upload__c.object
<CustomObject>
    <description>This object contains TA updates to be syncronized</description>
    <fields>
        <fullName>INSIDE_SALUTATION_S1__c</fullName>
        <label>INSIDE_SALUTATION_S1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALUTATION_CODE_S1__c</fullName>
        <label>SALUTATION_CODE_S1</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALUTATION_LINE_1_S1__c</fullName>
        <label>SALUTATION_LINE_1_S1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALUTATION_LINE_2_S1__c</fullName>
        <label>SALUTATION_LINE_2_S1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALUTATION_LINE_3_S1__c</fullName>
        <label>SALUTATION_LINE_3_S1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_ID__c</fullName>
        <description>SalesForce Id</description>
        <label>SFDC_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_UPDATE_TYPE__c</fullName>
        <label>SFDC_UPDATE_TYPE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TA Upload</label>
    <nameField>
        <label>TA Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TA Upload Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TaUploadSalutations.cls
public class TaUploadSalutations {
	public static void upload(Map<Id,Salutation__c> oldMap, Salutation__c[] clazzes, Boolean isInsert, Boolean isUpdate) {
	}
    public static testMethod void testTaUploadSalutation() {
    	/** Insert **/
    	Contact contact = new Contact(
    	   FirstName = 'Joe', 
    	   LastName = 'Dirt', 
    	   TaContactId__c = '23456_01_I',
		   bulk_load__c=true				
    	);
    	insert contact;
    	 
		// Insert       	   	      	   	
		Salutation__c clazz = new Salutation__c(
			contact__c = contact.Id,
			salutation_code__c = '\\D',
			salutation_line_1__c = 'Mr & Mrs Joseph Dirt',
			inside_salutation_1__c = 'Mr. Dirt'		
			);
		insert clazz;
		System.debug(clazz);
		TA_Upload__c[] upload1 = [
			Select Id, SFDC_ID__c, 				
				SALUTATION_CODE_S1__c,
				INSIDE_SALUTATION_S1__c,
				SALUTATION_LINE_1_S1__c,
				SALUTATION_LINE_2_S1__c,
				SALUTATION_LINE_3_S1__c
			From TA_Upload__c
			Where SFDC_ID__c = :clazz.Id AND SFDC_UPDATE_TYPE__c = 'Salutation'
			];
		// Update        
		clazz.inside_salutation_1__c = 'Mrs. Dirt';
		update clazz;
		
		System.debug(clazz);
		TA_Upload__c[] upload2 = [
			Select Id, SFDC_ID__c, 				
				SALUTATION_CODE_S1__c,
				INSIDE_SALUTATION_S1__c,
				SALUTATION_LINE_1_S1__c,
				SALUTATION_LINE_2_S1__c,
				SALUTATION_LINE_3_S1__c
			From TA_Upload__c
			Where SFDC_ID__c = :clazz.Id AND SFDC_UPDATE_TYPE__c = 'Salutation'
			];
	}
}