Git_WGBH_QC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Pledges &amp; Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gift_date__c</fullName>
        <description>Gift Date</description>
        <inlineHelpText>Gift Date</inlineHelpText>
        <label>Gift Date OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gift_kind_value__c</fullName>
        <description>Gift Kind</description>
        <inlineHelpText>Gift Kind</inlineHelpText>
        <label>Gift Kind Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pledge_status_value__c</fullName>
        <description>Pledge Status Valu</description>
        <inlineHelpText>Pledge Status Valu</inlineHelpText>
        <label>Pledge Status Value</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transaction_type_value__c</fullName>
        <description>Transaction Type</description>
        <inlineHelpText>Transaction Type</inlineHelpText>
        <label>Transaction Type Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations and Pledges</description>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gift_date__c</fullName>
        <description>Gift Date</description>
        <inlineHelpText>Gift Date</inlineHelpText>
        <label>Gift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gift_kind_value__c</fullName>
        <description>Gift Kind</description>
        <inlineHelpText>Gift Kind</inlineHelpText>
        <label>Gift Kind Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pledge_status_value__c</fullName>
        <description>Pledge Status Valu</description>
        <inlineHelpText>Pledge Status Valu</inlineHelpText>
        <label>Pledge Status Value</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transaction_type_value__c</fullName>
        <description>Transaction Type</description>
        <inlineHelpText>Transaction Type</inlineHelpText>
        <label>Transaction Type Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <label>Recurring Pledge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchOppRecurringDonationLink.cls
global class BatchOppRecurringDonationLink implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchOppRecurringDonationLink() {
    	// original - WHERE tatransactions_id__c != null and transaction_type_value__c = \'PL\' and gift_kind_value__c IN (\'IN\', \'SG\') and pledge_status_value__c IN (\'PF\', \'UF\') and Recurring_Donation__c = null';
        this.query = 'SELECT id, Recurring_Donation__c, tatransactions_id__c, transaction_type_value__c, gift_kind_value__c, pledge_status_value__c, batch_process_count__c FROM Opportunity WHERE batch_process_count__c = 2 ';
    }
    
    global BatchOppRecurringDonationLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
   global void execute(Database.BatchableContext BC, List<sObject> scope){
   		List<sObject> scope2 = new List<sObject>();
   		List<sObject> scope3 = new List<sObject>();   		
        for(Sobject s : scope) {
            Opportunity opp = (Opportunity) s;
            //Batch condition.
            if(	opp.tatransactions_id__c != null && 
            	opp.transaction_type_value__c == 'PL' &&            		
            	( opp.gift_kind_value__c == 'IN' || opp.gift_kind_value__c == 'SG') &&             		
            	( opp.pledge_status_value__c == 'PF' || opp.pledge_status_value__c == 'UF') &&             		
            	opp.Recurring_Donation__c == null) {
            	scope2.add(s);	
            }
            else {
            	scope3.add(s);	            	
            	//todo: opp.batch_process_count__c--;	
            }
        }
        if(scope2.size()>0) {
        	execute(scope2); 
        }
        if(scope3.size()>0) {
        	update scope3;
        }         
   }        

    global void execute(List<sObject> scope){
        List<String> rdTaIds = new List<String>();
        
        // 0     1  2    3    4  5
        //328858_02_I_PLEDGE#_03_01
		Orphan__c[] orphans = new List<Orphan__c>();         
        for(Sobject s : scope){         
            Opportunity opp = (Opportunity) s;
            try {
	            String[] oData = opp.tatransactions_id__c.split('_');
	            rdTaIds.add(oData[0] + '_' + oData[1] + '_' + oData[2] + '_' + oData[3] + '_' + oData[4]);
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Opportunity',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchOppRecurringDonationLink',
        			ta_id__c=opp.TaTransactions_Id__c,
        			object_id__c=s.id)
        		);
        	}	            
        }
        
        List<Recurring_Donation__c> rds = [SELECT id, TaTransactions_Id__c FROM Recurring_Donation__c WHERE TaTransactions_Id__c IN :rdTaIds];
        Map<String, ID> rdsMap = new Map<String, ID>();
        for(Recurring_Donation__c rd : rds) {
            rdsMap.put(rd.TaTransactions_Id__c, rd.Id);
        }
        
        for(Sobject s : scope){
            Opportunity opp = (Opportunity) s;
            try {
	            String[] oData = opp.tatransactions_id__c.split('_');
	            opp.Recurring_Donation__c = rdsMap.get(oData[0] + '_' + oData[1] + '_' + oData[2] + '_' + oData[3] + '_' + oData[4]);
	            //todo: opp.batch_process_count__c--;	
            }
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Opportunity',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchOppRecurringDonationLink',
        			ta_id__c=opp.TaTransactions_Id__c,
        			object_id__c=s.id)
        		);
        	}	                
        }
        
        update scope;
		if(orphans.size()>0) insert orphans;           
    }
    
    public static testMethod void testBatch() {
        Opportunity o1 = new Opportunity(
           tatransactions_Id__c = '23456_01_I_1230987_03_01',
           Name = 'Test Contact Opporutnity',
           CloseDate = Date.today(),
           StageName = 'Cultivation',
           gift_date__c = Date.today(), 
           transaction_type_value__c = 'PL', 
           gift_kind_value__c = 'IN',
           pledge_status_value__c = 'PF',  
           bulk_load__c = true,
           batch_process_count__c = 2
        );
        insert o1;
        Recurring_Donation__c rd1 = new Recurring_Donation__c(
           TaTransactions_Id__c = '23456_01_I_1230987_03',
           Name = 'Test Contact RD',
           gift_date__c = Date.today(),
           bulk_load__c = true
        );
        insert rd1;
        
        Test.StartTest();
        BatchOppRecurringDonationLink batch = new BatchOppRecurringDonationLink();
        batch.query += ' AND tatransactions_Id__c = \'23456_01_I_1230987_03_01\' LIMIT 3 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Opportunity to1 = [SELECT Recurring_Donation__c FROM Opportunity WHERE tatransactions_Id__c = :o1.tatransactions_Id__c][0];
        System.AssertEquals(to1.Recurring_Donation__c, rd1.id);
    }    

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchOppRecurringDonationLink', chainFlag);
    }
}