Git_WGBH_QC/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>Lapsed_Date__c</fullName>
        <label>Lapsed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Yr_Status__c</fullName>
        <label>Member Yr Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TestBatchExecGivingSummaryLapsed.cls
@isTest
Private class TestBatchExecGivingSummaryLapsed
{ 
    static testMethod void TestBatchExecGivingSummaryLapsed() 
    {   
        Test.startTest();
        
        String Query;
        boolean IsTest;    
        
        List<sObject> scope = new List<sObject>(); 
        List<Giving_Summary__c> lstGivingSummary = new List<Giving_Summary__c>();
        
        //scope.add(Giving_Summary__c);
        Giving_Summary__c gs = new Giving_Summary__c(Member_Yr_Status__c = 'Lapsed');
        //Query = 'Select id from Giving_Summary__c limit 100';
        Query = 'Select ID,Member_Yr_Status__c from Giving_Summary__c where Member_Yr_Status__c=\'Grace\' AND  Lapsed_Date__c!=null AND Lapsed_Date__c<=TODAY limit 1';
        BatchExecGivingSummaryLapsed begsl = new BatchExecGivingSummaryLapsed(Query);
        ID batchprocessid = Database.executeBatch(begsl);
       scope=database.query(Query);
         begsl.execute(null,scope); 
        Test.stopTest();

    }
}