Git_WGBH_QC/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>Lapsed_Date__c</fullName>
        <label>Lapsed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Yr_Status__c</fullName>
        <label>Member Yr Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/TestBatchGivingSummaryLapsed.cls
@isTest
private class TestBatchGivingSummaryLapsed {
    static testMethod void myTest() {
       Test.startTest();
       //Giving_Summary__c g = new Giving_Summary__c();
       //g.Member_yr_Status__c = 'Grace';
       //g.Lapsed_Date__c = system.today();
       //insert g;
       BatchGivingSummaryLapsed.CallTestClass();
       //BatchGivingSummaryLapsed.BatchGivingSummaryLapsed();
       Test.StopTest();     
        
    }
}