Git_WGBH_QC/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>Member_Yr_Status__c</fullName>
        <label>Member Yr Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchExecGivingSummaryGrace.cls
global class BatchExecGivingSummaryGrace implements Database.Batchable<sObject> {
    global final String Query;
    global boolean IsTest;    
    global BatchExecGivingSummaryGrace (String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchGivingSummaryGrace(scope);
    }
    
    void DoBatchGivingSummaryGrace(List<sObject> scope) {
        List<Giving_Summary__c> lstGivingSummary = new List<Giving_Summary__c>();
        
        for(sObject s : scope) {
            Giving_Summary__c g= (Giving_Summary__c)s;
            g.Member_Yr_Status__c = 'Grace';
            lstGivingSummary.add(g);
        }
        if(lstGivingSummary.size()>0) update lstGivingSummary;
        system.debug('#####' +lstGivingSummary.size());
    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

  
}