Git_WGBH_QC/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>Grace_Date__c</fullName>
        <label>Grace Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>History__c</fullName>
        <defaultValue>false</defaultValue>
        <label>History</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Yr_Status__c</fullName>
        <label>Member Yr Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary_Count__c</fullName>
        <label>Summary Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchGivingSummaryGrace.cls
global class BatchGivingSummaryGrace {
    Public static void BatchGivingSummaryGrace() {
        String query = 'Select ID,Member_Yr_Status__c from Giving_Summary__c where (Member_Yr_Status__c=\'Active\' OR Member_Yr_Status__c=\'Grace\') and History__c=False and Summary_Count__c=0 AND  Grace_Date__c!=null AND Grace_Date__c<=TODAY ';
        if(Test.IsRunningTest()) query += ' Limit 1';        
        BatchExecGivingSummaryGrace reassign = new BatchExecGivingSummaryGrace (query);
        ID batchprocessid = Database.executeBatch(reassign,200);
    }
    
    Public static void BatchGivingSummaryGrace(String GivingSummaryID) {
        String query = 'Select ID,Member_Yr_Status__c from Giving_Summary__c where (Member_Yr_Status__c=\'Active\' OR Member_Yr_Status__c=\'Grace\') and History__c=False AND  Grace_Date__c!=null AND Grace_Date__c<=TODAY AND ID=\'' + GivingSummaryID + '\'';
        if(Test.IsRunningTest()) query += ' Limit 1';        
        BatchExecGivingSummaryGrace reassign = new BatchExecGivingSummaryGrace (query);
        ID batchprocessid = Database.executeBatch(reassign,200);
    }    
    
    public static void CallTestClass() {
    }
    
  
}