Git_WGBH_QC/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>History__c</fullName>
        <defaultValue>false</defaultValue>
        <label>History</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lapsed_Date__c</fullName>
        <label>Lapsed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Yr_Status__c</fullName>
        <label>Member Yr Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchGivingSummaryLapsed.cls
global class BatchGivingSummaryLapsed {

    Public static void BatchGivingSummaryLapsed() {
        String query = 'Select ID,Member_Yr_Status__c from Giving_Summary__c where Lapsed_Date__c!=null AND Lapsed_Date__c<=TODAY and History__c=false and Member_Yr_Status__c = \'Lapsed\'';
        if(Test.IsRunningTest()) query += ' Limit 1';        
        BatchExecGivingSummaryLapsed reassign = new BatchExecGivingSummaryLapsed (query);
        ID batchprocessid = Database.executeBatch(reassign,200);
    }
    
    Public static void BatchGivingSummaryLapsed(String GivingSummaryID) {
        String query = 'Select ID,Member_Yr_Status__c from Giving_Summary__c where Lapsed_Date__c!=null AND Lapsed_Date__c<=TODAY and History__c=false and Member_Yr_Status__c = \'Lapsed\' AND ID=\'' + GivingSummaryID + '\'';
        BatchExecGivingSummaryLapsed reassign = new BatchExecGivingSummaryLapsed (query);
        ID batchprocessid = Database.executeBatch(reassign,200);
    }    
    public static void CallTestClass() {
    }
}