Git_WGBH_QC/src/objects/Interaction__c.object
<CustomObject>
    <description>Will capture all the internal and the external attendees for any event.</description>
    <label>Interaction</label>
    <nameField>
        <label>Agenda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Interactions__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Interaction_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposals_Pledges__c</fullName>
        <label>Proposals/Pledges</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals_Pledges</relationshipLabel>
        <relationshipName>Interaction_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interactions</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction_Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/myInteractionController.cls
public class myInteractionController 
{     public myInteractionController(ApexPages.StandardSetController controller) 
      {    
      
      }    
      Interaction__c interaction;    
      Account account;    
      Contact contact;        
      public Account getAccount() 
       {        
         if(account == null) account = new Account();        
         return account;    
       }    
      public Contact getContact() 
       {        
            if(contact == null) contact = new Contact();       
            return contact;    
       }    
      public Interaction__c getInteraction() 
       {        
             if(interaction == null) interaction = new Interaction__c();       
             return interaction;    
       }        
      public PageReference cancel() 
       {        
              PageReference ContactPage = new PageReference('/' + ApexPages.currentPage().getParameters().get('id')); 
              ContactPage.setRedirect(true);       
              return ContactPage;    
       }        
      public PageReference save() 
       {        
               insert interaction;                
               Interactions__c interactions = new Interactions__c();        
               interactions.Proposals_Pledges__c = ApexPages.currentPage().getParameters().get('id');        
               interactions.Interaction__c = interaction.id;        
               insert interactions;                
               //PageReference ContactPage = new ApexPages.StandardController(contact).view();        
               PageReference ContactPage = new PageReference('/' + ApexPages.currentPage().getParameters().get('id'));        
               ContactPage.setRedirect(true);        
               return ContactPage;    
        }
    public static testMethod void testMyInteractionController() {
    	ApexPages.StandardSetController controller = null;
    	myInteractionController nic = new myInteractionController(controller);
    	Contact contact = nic.getContact();
    	System.assert(contact!=null);
    	Account account = nic.getAccount();
    	System.assert(account!=null); 
    	Interaction__c inter = nic.getInteraction();
    	System.assert(inter!=null);    	    	   	
    }        
}