Git_WGBH_QC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Benefit_Exists__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If there is a benefit on this opportunity there will be a check mark</description>
        <inlineHelpText>There is a benefit on this opportunity, click into the opportunity detail to see the related benefit.</inlineHelpText>
        <label>Benefit Exists</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <label>Recurring Donation</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Pledges &amp; Payments</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Git_WGBH_QC/src/objects/Orphan__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>batchname__c</fullName>
        <label>Batch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classname__c</fullName>
        <label>Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exception_message__c</fullName>
        <label>Exception Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>object_id__c</fullName>
        <label>Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orphan_type__c</fullName>
        <label>orphan_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ta_id__c</fullName>
        <label>TA Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Orphan or Disowned</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Pledge_Benefit__c.object
<CustomObject>
    <description>This includes the benefit details of the pledge</description>
    <fields>
        <fullName>Bulk_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bulk Load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Pledge__c</fullName>
        <label>Recurring Pledge</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Pledge Benefits</relationshipLabel>
        <relationshipName>Pledge_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <label>TaTransactions_Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pledge Benefits</relationshipLabel>
        <relationshipName>Pledge_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pledge Benefit</label>
    <nameField>
        <label>Pledge Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pledge Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Recurring Donations and Pledges</description>
    <fields>
        <fullName>Benefit_Exists__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The checked box means that there is a benefit associated to this recurring pledge.</description>
        <inlineHelpText>There is a benefit on this recurring pledge opportunity.</inlineHelpText>
        <label>Benefit Exists</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaTransactions_Id__c</fullName>
        <description>TA Transactions external Id</description>
        <externalId>true</externalId>
        <label>TA Transactions Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>batch_process_count__c</fullName>
        <description>This field is used for Apex batch processing for post processing ETL information</description>
        <label>Batch Process Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <label>Recurring Pledge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchPledgeBenefitParentUpdate.cls
global class BatchPledgeBenefitParentUpdate implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchPledgeBenefitParentUpdate(){
    	// original - where p.bulk_load__c = true';
        this.query = 'Select p.opportunity__r.Benefit_Exists__c, p.opportunity__c, p.Recurring_Pledge__r.Benefit_Exists__c, p.Recurring_Pledge__c, p.batch_process_count__c From Pledge_Benefit__c p where p.batch_process_count__c = 1';
    }
    
    global BatchPledgeBenefitParentUpdate(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){ 
    	Map<ID, Opportunity> opps = new Map<ID, Opportunity>();
    	Map<ID, Recurring_Donation__c> rds = new Map<ID, Recurring_Donation__c>();
		Orphan__c[] orphans = new List<Orphan__c>();      	
        for(Sobject s : scope){
            Pledge_Benefit__c pb = (Pledge_Benefit__c) s;
            try {
	            if(pb.opportunity__c != null) {
	                pb.opportunity__r.Benefit_Exists__c = true;
	                opps.put(pb.opportunity__c, pb.opportunity__r);
	            }
	            else if(pb.Recurring_Pledge__c != null) {
	                pb.Recurring_Pledge__r.Benefit_Exists__c = true;
	                rds.put(pb.opportunity__c, pb.Recurring_Pledge__r);
	            }
	            pb.batch_process_count__c--;
        	}
        	catch (Exception ex) {
        		orphans.add( new Orphan__c(
        			orphan_type__c='Object',
        			classname__c='Pledge_Benefit__c',
        			exception_message__c=ex.getMessage(),
        			batchname__c='BatchPledgeBenefitParentUpdate',
        			ta_id__c=pb.TaTransactions_Id__c,
        			object_id__c=s.id)
        		);
        	}	            
        }
        update scope;
        update opps.values();
        update rds.values();
		if(orphans.size()>0) insert orphans;           
    }

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchPledgeBenefitParentUpdate', chainFlag);
    }
    
    public static testMethod void testBatch() {
        Test.StartTest();
        BatchPledgeBenefitParentUpdate batch = new BatchPledgeBenefitParentUpdate();
        batch.query += ' LIMIT 2 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
    }
}