Git_WGBH_QC/src/objects/Requested_Search__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requested Search</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Requested Search#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Request__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Request</relationshipLabel>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Campaign_Criteria_Template__c</referenceTo>
        <relationshipLabel>Search Request</relationshipLabel>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Request</label>
    <nameField>
        <displayFormat>REQ-{0000000000}</displayFormat>
        <label>Search Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>ContactLookup__c</fullName>
        <label>ContactLookup</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LeadLookup__c</fullName>
        <label>LeadLookup</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Search Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Result</label>
    <nameField>
        <displayFormat>RES-{0000000000}</displayFormat>
        <label>Search Result#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchFinalizeSearchRequest.cls
global class BatchFinalizeSearchRequest{
    Public static void BatchFinalizeSearchRequest(ID RequestID) {
        ID batchprocessid;
        //BatchExecSearchRequest reassign;
        BatchExecFinalizeSearchRequest reassign;
        if(RequestID == null){
            return;
        }
        List<Search_Request__c> lstRequest = [Select id, Criteria__c, Campaign__c, IsContact__c, Template__c From Search_Request__c Where Id =: RequestId];
        
        String AdvanceFilter = '';
        Id CampaignId;
        Boolean IsContact;
        if(lstRequest != null && lstRequest.size()>0){
            List<AggregateResult> lstMax = [Select Max(Index__c) maxIndex From Requested_Search__c Where Request__c =: RequestID];
            Integer noOfquery = 1;
            if(lstMax != null && lstMax.size()>0){
                noOfquery = Integer.valueOf(String.valueOf(lstMax[0].get('maxIndex')));
            }
            AdvanceFilter = lstRequest[0].Criteria__c;
            CampaignId = lstRequest[0].Campaign__c;
            IsContact = lstRequest[0].IsContact__c;
            String Query = GenerateQuery(RequestId, IsContact, AdvanceFilter, noOfquery);
            system.debug('######## Query ' + Query);
            reassign = new BatchExecFinalizeSearchRequest(Query, RequestID, IsContact, lstRequest[0].Campaign__c);
            batchprocessid = Database.executeBatch(reassign);
        }
    }
    
    Static String Queryfields(Boolean IsContact){
        String fields = '';
        if(IsContact == false){
            fields = ' id, FirstName, LastName, Title, Company, Email ';
        }
        else if(IsContact == true){
            fields = ' id, FirstName, LastName, Title, Account.Name, Email, AccountId ';
        }
        return fields;
    }
    Static string GenerateQuery(ID queryRequestId, Boolean IsContact, String AdvanceFilter, Integer noOfConditions){
        List<sObject> lstFinal;
        String query = '';
        if(IsContact == true){
            query = 'Select ' + Queryfields(IsContact) + ' from Contact ';
        }
        else{
            query = 'Select ' + Queryfields(IsContact) + ' from Lead ';
        }
        String rQuery;
        if(IsContact == true){
            rQuery = 'Select ContactLookup__c From Search_Result__c';
        }else{
            rQuery = 'Select LeadLookup__c From Search_Result__c';
        }
        String strAdv = '';
        if(NVL(AdvanceFilter)!=''){
            strAdv = AdvanceFilter;
            if(noOfConditions > 0){
                for(integer i=1;i<=noOfConditions;i++){
                    strAdv = strAdv.replace(' ' + string.valueOf(i) + ' ', ' col' + string.valueOf(i) + '__c = true ');
                    strAdv = strAdv.replace('(' + string.valueOf(i) + ' ', '(col' + string.valueOf(i) + '__c = true ');
                    strAdv = strAdv.replace(' ' + string.valueOf(i) + ')', ' col' + string.valueOf(i) + '__c = true) ');
                    system.debug('################# strAdv : ' + strAdv);
                }
                
            }
        }else{
            if(noOfConditions > 0){
                for(integer i=1;i<=noOfConditions;i++){
                    //strAdv = strAdv.replace(string.valueOf(i) + ' ', 'col' + string.valueOf(i) + '__c ');
                    
                    strAdv = strAdv.replace(' ' + string.valueOf(i) + ' ', ' col' + string.valueOf(i) + '__c = true ');
                    strAdv = strAdv.replace('(' + string.valueOf(i) + ' ', '(col' + string.valueOf(i) + '__c = true ');
                    strAdv = strAdv.replace(' ' + string.valueOf(i) + ')', ' col' + string.valueOf(i) + '__c = true) ');
                    if(strAdv == ''){
                        strAdv = ' col' + string.valueOf(i) + '__c = true ';
                    }
                    else{
                        strAdv += ' or col' + string.valueOf(i) + '__c = true ';
                    }
                    system.debug('################# strAdv : ' + strAdv);
                }
            }
        }
        rQuery += ' Where (' + strAdv + ') And Request__c = \'' + queryRequestId + '\'';
        Query += ' Where id in(' + rQuery + ')';
        
        return Query;
    }
    Static String NVL(String val){
        if(val == null){
            return '';
        }
        else{
            return val.trim();
        }
    }
}