Git_WGBH_QC/src/objects/Requested_Search__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <picklist>
            <picklistValues>
                <fullName>Insert</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Requested Search</relationshipLabel>
        <relationshipName>Requested_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Search</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Requested Search#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Request__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Search Request</relationshipLabel>
        <relationshipName>Search_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Search Request</label>
    <nameField>
        <displayFormat>REQ-{0000000000}</displayFormat>
        <label>Search Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchSearchRequest.cls
global class BatchSearchRequest{
    Public static void BatchSearchRequest(ID RequestID, boolean isContact, String CampaignId) {
        ID batchprocessid;
        //BatchExecSearchRequest reassign;  
        BatchExecSearchRequestNew reassign;  
        if(RequestID == null){
            return;
        }
        //////////////
        String RequestedBy = '';
        List<Search_Request__c> lstRequest = [Select CreatedById From Search_Request__c Where Id=:RequestId];
        if(lstRequest != null && lstRequest.size()>0){
            RequestedBy = lstRequest[0].CreatedById;
        }
        //////////////
        
        String Query = 'Select Id, FieldName__c, Index__c, Query__c, Request__c, Status__c, Campaign__c, CreatedById, Operation__c From Requested_Search__c ';
        Query += 'Where Request__c = \'' + RequestID + '\' and Status__c = \'Pending\' Order by Index__c';
        /*
        reassign = new BatchExecSearchRequest(Query, RequestID, isContact, CampaignId, RequestedBy);
        batchprocessid = Database.executeBatch(reassign, 1);
        */        
        reassign = new BatchExecSearchRequestNew(Query, RequestID, isContact, CampaignId, RequestedBy);
        batchprocessid = Database.executeBatch(reassign, 1);
    }
}