Git_WGBH_QC/src/objects/Search_Request__c.object
<CustomObject>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Search Request</label>
    <nameField>
        <displayFormat>REQ-{0000000000}</displayFormat>
        <label>Search Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/objects/Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>ContactLookup__c</fullName>
        <label>ContactLookup</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadLookup__c</fullName>
        <label>LeadLookup</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Search Request</label>
        <referenceTo>Search_Request__c</referenceTo>
        <relationshipLabel>Search Result</relationshipLabel>
        <relationshipName>Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Result</label>
    <nameField>
        <displayFormat>RES-{0000000000}</displayFormat>
        <label>Search Result#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/BatchAddCampaignMember.cls
global class BatchAddCampaignMember{
    Public static void BatchSearchContact(ID RequestID, ID CampaignId, String Status, Boolean isContact) {
        ID batchprocessid;
        BatchExecAddCampaignMember reassign;  
        if(RequestID == null){
            return;
        }
        String Query;
        List<Search_Request__c> lstRequest = [Select Criteria__c From Search_Request__c Where Id=:RequestID];
        if(isContact == true){
            Query = 'Select ContactLookup__c From Search_Result__c Where Request__c = \'' + RequestID + '\' and Contact__c = true and Lead__c = false';
        }
        else{
            Query = 'Select LeadLookup__c From Search_Result__c Where Request__c = \'' + RequestID + '\' and Contact__c = false and Lead__c = true';
        }
        if(Test.isRunningTest()) Query += ' Limit 100';
        reassign = new BatchExecAddCampaignMember(Query, Status, isContact, CampaignId, RequestID);
        batchprocessid = Database.executeBatch(reassign, 400);
    }    
}