Git_WGBH_QC/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>Giving_Id__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TRANSACTION_BATCHS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVIEW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UpdateCCDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdateCCDate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isCCDateExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto set Checked when Charge Card Date expired.</description>
        <inlineHelpText>Auto set Checked when Charge Card Date expired.Do not change this Fields.</inlineHelpText>
        <label>isCCDateExpired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>needToRePaymentReq__c</fullName>
        <defaultValue>false</defaultValue>
        <label>needToRePaymentReq</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction Batch</label>
    <nameField>
        <displayFormat>TBR-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git_WGBH_QC/src/classes/ExtendCCDate_Batch.cls
global class ExtendCCDate_Batch {
    Public static Boolean IsTest;
    Public static void ExtendCCDate_Batch() {
        
        String strQ = '';        
        StrQ = 'SELECT  Id FROM transaction_batch__c Where Giving_Id__c != null AND (Status__c= \'PROCESS\' or Status__c = \'FAIL\' )  AND Transaction_Type__c = \'PAYMENT\' AND UpdateCCDate__c = false and needToRePaymentReq__c = false And isCCDateExpired__c  = true';
            
        BatchExecExtendCCDate_Batch reassign = new BatchExecExtendCCDate_Batch(strQ);

        if(IsTest!=true) ID batchprocessid = Database.executeBatch(reassign,1);
    }  
    
    static testMethod void  TestPayment_Batch() {

        Test.startTest();
        try {
            ExtendCCDate_Batch.IsTest = true;
            ExtendCCDate_Batch.ExtendCCDate_Batch();
            
        }
        Catch(Exception ex) {}
        Test.StopTest();     
        
    }
}